OWNERS

@brancz @mxinden this is needed if we want to use the openshift-merge-robot workflow.
(I added myself as a reviewer, but I'm fine with removing that)

owners: Add OWNERS file

---

Makefile

Since the default intent for building is to put this into a Docker
image, it should build with GOOS=linux by default.
If needed to build natively for the local OS, it can be done using
`make build GOOS=$(go env GOOS)`.

Set GOOS=linux to build binaries for Linux by default

---

pkg/manifests/manifests.go

Fixes https://github.com/openshift/cluster-monitoring-operator/pull/29#discussion_r192505078
@ironcladlou @mxinden @elad661

manifests: Fix default role to be in default namespace

---

pkg/client/client.go
pkg/manifests/manifests.go
pkg/tasks/prometheus.go

Fix the creation of the default rules. Default rules are now expressed as a
PrometheusRule object, but the manifest was still being unmarshalled into a
ConfigMap causing the creation of an empty ConfigMap rather than a
PrometheusRule.

Fix creation of default rules

---

pkg/manifests/config.go
pkg/manifests/manifests.go

This pull request make the Grafana and kube-state-metrics node selectors configurable, making all necessary components configurable now.
@mxinden 
cc @mrsiano 
Related https://github.com/openshift/openshift-ansible/issues/9102

manifests: Make node-selectors configurable

---

cmd/operator/main.go
hack/ocp-images.sh
manifests/cluster-monitoring-operator.yaml
pkg/operator/operator.go

This commit implements basic instrumentation for the Cluster Monitoring
Operator. The CMO will report how many errors it has gotten while
attempting to reconcile. The metrics endpoint is exposed on port 8080,
for consistency with the Prometheus Operator.
cc @mxinden @brancz

*: add basic instrumentation

---

Makefile

This commit prevents Make from logging errors to stderr when it
is checking if it should install go-jsonnet or not. These errors are of
the form:
```
which: no jsonnet in
(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin)
```
and are expected if jsonnet is not installed but can make it seem like
the build is failing.

Makefile: prevent which logs in stderr

---

.travis.yml
Dockerfile
Makefile

This commit modifies the Makefile dependency tree so that all utility
binaries are no longer automatically installed as direct dependencies of
the targets. This ensures that in a Docker container with no jsonnet,
for example, the entire static asset tree will not be regenerated. This
in turn allows us to avoid having to install extra tools like jq during
the container build process.
cc @brancz

Makefile: don't install binaries as direct deps

---

pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Currently, the node selector in the prometheus operator config is
ignored.
This fixes it
Fixes MON-270

pkg/manifests: add nodeSelector to prometheus operator config

---

.travis.yml
Dockerfile
Makefile

This commit allows the Docker build flow to compile the operator binary without any Make dependencies. This means the compilation during container build time depends exactly on the static assets that are checked into the repository and will not regenerate any assets if they are actually out of date.
cc @brancz

Makefile: container build operator with deps

---

assets/alertmanager/alertmanager.yaml
assets/node-exporter/daemonset.yaml
assets/prometheus-k8s/prometheus.yaml
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json

This mechanically bumps kube-prometheus assets to include
https://github.com/coreos/prometheus-operator/pull/1806
Fixes MON-285

assets: bump kube-prometheus assets

---

assets/cluster-monitoring-operator/cluster-role.yaml
jsonnet/cluster-monitoring-operator.jsonnet
manifests/cluster-monitoring-operator-role.yaml
pkg/manifests/bindata.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/clustermonitoringoperator.go

This ClusterRole can be used by users to bind against, to allow viewing
the cluster monitoring stack. This is useful for usability but also to
allow us to modify the specific roles at a later point in time, because
existing users that bind to it will continue to have the correct roles.
@mxinden @s-urbaniak @squat @metalmatze

Add cluster-monitoring-view ClusterRole

---

manifests/cluster-monitoring-operator.yaml

The version in the manifests does not start anymore and is outdated.

manifests: Set operator version to v0.1.0

---

jsonnet/main.jsonnet

For the images that OpenShift builds itself, we should make sure that the images actually exist before upgrading. Hence relying on the upstream dependencies is unsafe, as we might not yet have a Prometheus v2.4.2 available.
In the future this should be catched by the CI nonetheless. 
/cc @mxinden @squat @s-urbaniak @simonpasquier

jsonnet: Pin versions for OpenShift images

---

hack/cluster-monitoring-operator-role.yaml.in
manifests/02-role.yaml
pkg/client/client.go
pkg/manifests/config.go
pkg/operator/operator.go
pkg/tasks/telemeter.go

This PR adds an option to the Cluster Monitoring Operator
configuration file to disable the Telemeter client. Disabling the
Telemeter client will not just stop reconciling the deployment or set
the replica count to zero but rather will delete all related resources.
Note: The Cluster Monitoring Operator needs to be able to delete Service
objects in order to delete all Telemeter resources.
cc @s-urbaniak @mxinden @metalmatze

Add option to disable Telemeter

---

cmd/operator/main.go
pkg/client/client.go
pkg/operator/operator.go

After running `./scripts/deploy-on-openshift.sh` and everything being setup inside the cluster, we can scale down the cluster-monitoring-operator deployment to 0 replicas. Now it's possible to run the operator locally (after compiling the binary) and give it the kubeconfig for the cluster running against.
This allows for quicker development cycles by running the operator locally.
/cc @squat @brancz 
PS: I also feel like the whole instantiation for the kubernetes client should be done inside the main.go and not somewhere deep down, but that's just a nit :innocent:

Create config for Kubernetes' client-go from kubeconfig or in-cluster credentials

---

pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/tasks/telemeter.go

This prevents from starting telemeter if no config, cluster ID or
token is given.
cc @squat @brancz

pkg/tasks/telemeter: enable only cluster ID and token is given

---

pkg/client/client.go
pkg/manifests/manifests.go
pkg/operator/operator.go
pkg/tasks/configsharing.go

The idea is that console or users of console should not have permission to list all routes to discover the URLs of Prometheus and Alertmanager, therefore we publish the URLs in a configmap that is safe to be read by anyone in the cluster. More generally this is the "config sharing scheme" used in OpenShift going forward for different components to share non-secret information with other components.
https://jira.coreos.com/browse/MON-433
@mxinden @squat @s-urbaniak @metalmatze

Add config sharing scheme to share URLs with console

---

assets/grafana/deployment.yaml
jsonnet/grafana.jsonnet

This commit fixes an old issue that only began to manifest itself today.
In this project we add a proxy in front of Grafana, which occupies
Grarana's normal port of 3000, and move Grarana to 3001. However, we
did not redefine the named container port `http` from 3000 -> 3001.
The result was that once upstream jsonnet for Grafana added an HTTP
health check for port 3000, on our deployments this was actuall hitting
the proxy, which uses TLS, so the health check would fail.
cc @brancz @s-urbaniak

assets,jsonnet: fix grafana port

---

pkg/manifests/manifests.go

Changing this, as that's the convention in the console, and generally makes sense. (RE: https://github.com/openshift/cluster-monitoring-operator/pull/169#issuecomment-442399151)
@s-urbaniak @squat @metalmatze @mxinden @kyoto

manifests: Make URL uppercase in config sharing scheme

---

pkg/client/client.go

The namespace selector is being ignored when creating a client. It is getting defaulted to ""
which is equivalent to select all. During e2e test this is causing churn on prom operator as the pod is getting
redeployed continuosly with more new namespaces like this:
```console
piVersion: extensions/v1beta1
kind: Deployment
metadata:
annotations:
deployment.kubernetes.io/revision: "13"
creationTimestamp: 2018-12-10T08:47:45Z
generation: 20
labels:
k8s-app: prometheus-operator
name: prometheus-operator
namespace: openshift-monitoring
resourceVersion: "53430"
selfLink: /apis/extensions/v1beta1/namespaces/openshift-monitoring/deployments/prometheus-operator
uid: 4356b33f-fc58-11e8-852c-121e8f0b6b56
spec:
progressDeadlineSeconds: 600
replicas: 1
revisionHistoryLimit: 10
selector:
matchLabels: …
```

pkg/client: fix namespaceSelector being ignored when creating client

---

assets/grafana/dashboard-definitions.yaml

assets/grafana/dashboard-definitions.yaml was not in sync with what the
continuous integration system was generating. This patch updtes to the
corresponding version.
Seems like just the unicode encoding was somehow changed.

assets/grafana: Regenerate dashboard definitions

---

Makefile
test/e2e/main_test.go

In order to reintroduce the end-to-end tests and their continuous
execution, this patch disables the tests for now and replaces them with
a simple test connecting to the Kubernetes cluster.
Relates to https://github.com/openshift/release/pull/2383.
Let me know if this approach sounds reasonable to you. Happy for alternative suggestions.

test/e2e: Replace e2e tests with basic stub

---

test/e2e/main_test.go

Currently e2e tests fail with the following panic:
```
go test -v -timeout=20m ./test/e2e/ --operator-image=quay.io/openshift/cluster-monitoring-operator:6329040 --kubeconfig /tmp/admin.kubeconfig
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xf7cacd]
goroutine 1 [running]:
github.com/openshift/cluster-monitoring-operator/test/e2e.TestMain(0xc420531f00)
/go/src/github.com/openshift/cluster-monitoring-operator/test/e2e/main_test.go:35 +0x5d
main.main()
_testmain.go:40 +0xe9
FAIL	github.com/openshift/cluster-monitoring-operator/test/e2e	0.045s
make: *** [test-e2e] Error 1
```
This fixes it by referencing the recommended home file variable from client-go.
cc @squat

test/e2e: fix panic in parsing kubeconfig cli flag

---

pkg/client/client.go

Currently an API service object update fails, because we don't use the
persisted object. This fails because the resource version is missing
causing the following error:
```
E1221 15:31:51.753825       1 operator.go:211] Syncing "openshift-monitoring/cluster-monitoring-config" failed
E1221 15:31:51.753844       1 operator.go:212] sync "openshift-monitoring/cluster-monitoring-config" failed: running task Updating prometheus-adapter failed: reconciling PrometheusAdapter APIService failed: updating APIService object failed: apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```
cc @squat @brancz @metalmatze  @mxinden whoever is out there :-)

pkg/client/client.go: update API service using persisted object

---

pkg/operator/operator.go

When cluster-monitoring-operator failed to parse configmap, it does
not output the reason why it failed. In addition, it outptus info
level.
e.g - when failed to parse configmap:
```
I0110 06:16:18.665461       1 operator.go:270] Cluster Monitoring config could not be parsed. Using defaults.
```
Due to this, trouble shooting is difficult.
This patch adds error output the reason why it failed with appropriate level.

Output correct error message with appropriate level

---

manifests/04-deployment.yaml
manifests/image-references
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

OCP was created with `configmap-reloader` and that is more readable.
Origin is being changed to publish as configmap-reloader, and this
changes CMO to also be updated.
The v3.11 image location is not updated.
See https://github.com/openshift/release/pull/2603

configmap-reloader is usually published as 'reloader', not 'reload'

---

pkg/tasks/tasks.go

Current master logs look like:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cloud-credential-operator/21/pull-ci-openshift-cloud-credential-operator-master-e2e-aws/102/artifacts/e2e-aws/pods/openshift-monitoring_cluster-monitoring-operator-5f4c54c8c4-2hnqz_cluster-monitoring-operator.log.gz | gunzip | grep 'running task'
I0123 17:15:38.849228       1 tasks.go:37] running task Updating Prometheus Operator
I0123 17:16:10.316708       1 tasks.go:37] running task Updating Cluster Monitoring Operator
I0123 17:16:10.412633       1 tasks.go:37] running task Updating Grafana
I0123 17:16:31.052395       1 tasks.go:37] running task Updating Prometheus-k8s
I0123 17:17:09.241802       1 tasks.go:37] running task Updating Alertmanager
I0123 17:17:40.563233 …
```

pkg/tasks: More verbose task logging

---

manifests/05-clusteroperator.yaml
pkg/client/client.go
pkg/client/clusteroperator.go
pkg/operator/operator.go

ClusterOperator objects are supposed to be normalized to be just the components name. No "openshift" prefix or "operator" suffix.
@squat @s-urbaniak @metalmatze @mxinden

*: Rename cluster-operator object to "monitoring"

---

manifests/06-operatorgroup.yaml

Creating this OperatorGroup will allow preventing having another Prometheus Operator that reconciles on the same objects, which would yield undefined behavior. As the cluster-monitoring-operator is a higher run level than OLM, we can just put this object in our payload.
@metalmatze @squat @s-urbaniak @mxinden 
cc @alecmerdler @njhale @ecordell @jwforres

manifests: Add OperatorGroup

---

Makefile

Include both jsonnet templating and gobindata generation in the Makefile
'generate' target, which is included in the Travis builds.

Makefile: Include jsonnet and gobindata in 'generate' target -> master

---

manifests/06-operatorgroup.yaml

It looks like there are some missing fields on the OperatorGroup manifest. I've added them here:
- olm.providedAPIs: An annotation that contains a comma delimited list of GVKs provided by members of the OperatorGroup
- staticProvidedAPIs: True if OLM should not mutate the `olm.providedAPIs` annotation
Together, these fields prevent other intersecting OperatorGroups from installing any operators that provide the same GVKs, even if there are no CSVs that provide operators in the OperatorGroup's namespace.
The fix that provides this feature was merged early this week, staticProvidedAPIs is an additional field that was added to address CMO's specific usecase.

fix(operatorgroup): add missing static configuration

---

pkg/client/client.go

During an installation failure issue [1], the monitoring was reporting following error:
```
Error: running task Updating Grafana failed: waiting for Grafana Route to become ready failed: timed out waiting for the condition
```
`timed out waiting for the condition` does not indicate what was the last state that caused the wait to timeout. Reporting lastErr in cases of
timeout should provide better errors.
[1]: https://github.com/openshift/installer/issues/1219

pkg/client: update waits to report lastError than the timed-out error

---

manifests/06-operatorgroup.yaml

The `spec.selector` was missing `matchLabels`, and causing the `OperatorGroup` to target `all-namespaces` on the cluster instead of a subset.
Addresses https://jira.coreos.com/browse/ALM-913

Fix OLM `OperatorGroup`

---

manifests/image-references

These image-references don't seem to align with the images specified in the cluster-monitoring-operator deployment, so this PR fixes that. Hopefully this fixes the last issues regarding getting the right images replaced by the CVO.
https://bugzilla.redhat.com/show_bug.cgi?id=1678645
@squat @s-urbaniak @metalmatze @mxinden @smarterclayton

manifests: Fix grafana and oauth-proxy image-references

---

Dockerfile.generate
Makefile

Instead of running the Makefile `generate` target as root, run it as the
local user. Main benefit would be, that created files are not owned by
root, but by the local user instead.
Let me know what you think team.

Makefile: Don't run generate container as root

---

pkg/client/client.go
test/e2e/alertmanager_test.go
test/e2e/framework/framework.go
test/e2e/prometheus_test.go

Currently, when a volume claim template is specified for either
prometheus or alertmanager, a CRD validation error is generated.
See
https://github.com/coreos/prometheus-operator/issues/2399#issuecomment-466320464
for an envisioned resolution in prometheus operator.
Until then an upstream fix is ready, this is a bandaid.
Fixes MON-579
cc @brancz @mxinden @metalmatze

pkg/operator: set creationTimestamp for PVCs, add e2e tests

---

pkg/client/client.go
test/e2e/main_test.go
test/e2e/multi_namespace_test.go

As a follow up of https://github.com/openshift/cluster-monitoring-operator/pull/262#discussion_r
@mxinden @s-urbaniak

test/e2e: Cleanup and suffix namespace

---

Makefile
README.md
test/e2e/framework/framework.go
test/e2e/main_test.go

- Remove outdated `e2e-clean` and `run-docker-test-minikube` Makefile
target from Tectonic times.
- Clean up Makefile Phony entries.
- Remove `--operator-image` flag for end-to-end test invocation. This
flag is not used anymore and can't be inferred from the repository at
hand.
- Update `README.md` `## Testing` section.

*: Clean test invocation and documenation

---

test/e2e/framework/framework.go
test/e2e/framework/prometheus_client.go
test/e2e/framework/prometheus_client_test.go
test/e2e/main_test.go
test/e2e/multi_namespace_test.go

- Instead of counting the returned time series, inspect the first and only
returned value from a query. This enables checking specific timeseries values.
The previous behavior can still be achieved by using the `count` PromQL
function.
- Introduce `waitForQueryReturn{GreaterEqualOne,One}` helper functions for easier
access.
- Intialize Prometheus client at test framework creation time, as more function
will need to use it in the long run.
- Wait for Prometheus k8s before running any tests as multiple of them depend on
its existence.
I will follow up with a patch checking for firing alerts in a bit. This lays the groundwork for it.

test/e2e: Refactor framework setup & wait for query logic

---

pkg/tasks/prometheus.go

Currently, we only initially create the kubelet serving CA. This results
in outdated worker CA certificates causing prometheus to fail scraping
worker node kubelets.
This fixes it by create-or-updating the kubelet-serving-ca.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1679500#c12
cc @squat @mxinden @brancz
I am a bit sceptical here though. I verified locally that cert change are being synced down to the prometheus pod, but the targets still failed. Rekicking prometheus helped obviously.

pkg/tasks/prometheus: update kubelet serving CA if it changed

---

pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go

This PR removes the leftover configuration options, that are unnecessary now as etcd is always setup as static pods and we consistently monitor it.
As discussed on slack, we can either merge this as soon as e2e goes green on this, giving the etcd team an easier path to test this, or wait for them to provision the `openshift-monitoring/kube-etcd-client-certs` Secret with the appropriate client certificates, and then verify this works. I favor the first, as we can treat everything else as follow up/bugfix, but have no strong opinion (this is also a bugfix as we have an open bug, that these configurations don't work).
@mxinden @s-urbaniak @squat @metalmatze 
cc @hexfusion

*: Enable etcd monitoring by default

---

pkg/tasks/alertmanager.go
pkg/tasks/clustermonitoringoperator.go
pkg/tasks/grafana.go
pkg/tasks/kubestatemetrics.go
pkg/tasks/nodeexporter.go
pkg/tasks/prometheus.go
pkg/tasks/telemeter.go

This gives the possibility to postpone waiting for the prometheus
operator is actually available before proceeding with the actual
deployment artifacts of the task at hand.
This should give another performance gain during installation time.
Another potential improvement for https://bugzilla.redhat.com/show_bug.cgi?id=1678475
cc @mxinden @brancz @squat

pkg/tasks: create service monitor at the end of each tasks.

---

hack/generate-etcd-secret.sh

This adapt the `hack/` script we have to OpenShift 4.0, to immitate what the etcd management should do, so we can test the etcd integration out of band of the team doing this work.
(note there is more to getting etcd working, like the etcd team creating the right `Service` entries, but this is what enables etcd monitoring on our side so sufficient for testing https://bugzilla.redhat.com/show_bug.cgi?id=1662114 for example)
@s-urbaniak @squat @mxinden

hack: Adapt generate etcd secret script to 4.0

---

cmd/operator/main.go
manifests/04-deployment.yaml
pkg/client/clusteroperator.go
pkg/operator/operator.go

#278 introduced the actual mechanism that reports status as configured by the CVO. As we had previously created some plumbing for setting the version through a compiler flag, we should clean up our mechanism and align it with what's actually being done.
I'm putting a hold label on this, just so we can explicitly verify in the logs, that the right version is being reported. As this is dynamically set via the CVO I have a hard time coming up with a test for this, but if you have an idea, I'm more than happy to add a test.
/hold
@s-urbaniak @mxinden @squat

*: Cleanup release version plumbing

---

manifests/04-deployment.yaml

specifies system-cluster-critical priority for operator.
blocks passing smoke tests for ensuring control plane pods always schedule.
see: openshift/origin#22217

manifests: operator has system-cluster-critical priority

---

pkg/manifests/config.go
pkg/operator/operator.go

The installer already creates a secret in the cluster [1] and there is no requirement to fetch the pull secret from cluster-config-v1 config map.
This also unblocks https://github.com/openshift/installer/pull/1379 to fix https://bugzilla.redhat.com/show_bug.cgi?id=1686119
[1]: https://github.com/openshift/installer/blob/13a752ea0fcae927cba6795782f87ffa332d5b75/data/data/manifests/bootkube/pull.yaml.template
/cc @deads2k

operator: fetch the pull-secret directly from secret than cluster-config-v1

---

pkg/client/clusteroperator.go
pkg/client/condition.go
pkg/client/condition_test.go

Currently, we ignore the versions of the operator
and only set to progressing if the operator has been failing before.
This fixes it by also also respecting the current version of the operator.
If the target version is the same, the existing rules apply.
If the current version is different, we always set to progressing.
Fixes a part of https://bugzilla.redhat.com/show_bug.cgi?id=1690162
where the operator was launched with a new version but did not report
a progressing state.
cc @brancz @squat @metalmatze

pkg/client/condition: respect current and target version

---

pkg/operator/operator.go

Without this change logs are quite confusing.
Fixes MON-533

pkg/operator: do not print "Error" when log msg is a warning

---

Makefile

Change needed due to https://github.com/google/go-jsonnet/pull/266

use new instructions on how to build go-jsonnet

---

test/e2e/main_test.go

Only doing this so we can progress with other things while the masters
team fixes their instrumentation.
@mxinden @squat @s-urbaniak @metalmatze @paulfantom

test/e2e: Disable scheduler and controller-manager e2e until fixed

---

hack/build-jsonnet.sh

This change makes the script work on previous Bash versions, including the one shipped on MacOs.
To be able to run on Macs, the script also needs gawk installed since default awk errors out. One can install with `brew install gawk`.

Support previous bash versions (Mac included)

---

manifests/cluster-monitoring-operator.yaml

With previous version (v0.0.6) when the CMO got deployed into a `oc cluster up` cluster, Grafana was not deployed. With version v0.1.1, the monitoring stack was correctly deployed.
This was tested on a "Openshift on Footloose" that is a Docker in Docker deployment for it. Ref. https://github.com/carlosedp/openshift-on-footloose

Update cluster-monitoring-operator image

---

pkg/operator/operator.go

The operator should be using the openshift-config/pull-secret as the kube-system/coreos-pull-secret has been marked deprecated.
/cc @derekwaynecarr @smarterclayton

Bug 1697644: operator: use openshift-config/pull-secret to fetch the pull secret for cloud.openshift.com

---

pkg/client/client.go

Currently we are updating Service resource every 5 minutes which causes certificate renewal and in turn recreation of prometheus-adapter. This change prevents unnecessary updates of Service resource.
https://bugzilla.redhat.com/show_bug.cgi?id=1700037
Verification steps taken:
1. Disabled CVO and CMO in openshift cluster
2. Built and ran cluster-monitoring-operator from my machine
3. Got a prometheus-adapter secret just after starting cmo
```
$ oc -n openshift-monitoring get secrets | grep prometheus-adapter            
prometheus-adapter-dockercfg-4mbd9                kubernetes.io/dockercfg               1         2d
prometheus-adapter-f3opuef14ihn0                  Opaque                                4         24h
prometheus-adapter-tls                            kubernetes.io/tls …
```

pkg/client: compare Service object before updating it

---

pkg/client/client.go

Follow up to #328.
Check only spec, labels, and annotations instead of whole object.
@brancz @s-urbaniak @squat

pkg/client: compare only parts of Service resource instead of full object

---

assets/prometheus-adapter/cluster-role-aggregated-metrics-reader.yaml
jsonnet/jsonnetfile.lock.json
manifests/02-role.yaml
pkg/manifests/bindata.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/prometheusadapter.go
test/e2e/framework/framework.go
test/e2e/prometheusadapter_test.go

Currently, only cluster wide admins have the permissions to view metrics 
resources. This fixes it by adding a read-only cluster role which includes 
aggregation labels to synthesize permission rules for standard user-facing 
roles according to [1].
Note that only the "pods" resource is granted as reading "nodes" metrics 
requires a cluster wide permission.
[1] https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1701343

pkg/tasks/prometheusadapter: deploy aggregated cluster role

---

test/e2e/main_test.go

Removing these components to block our own e2e tests, as we don't control these components here and they're already being tested for in the e2e-aws job. Opening a PR to test for etcd metrics to be tested additionally in the e2e-aws job.
@s-urbaniak @squat @mxinden @metalmatze @paulfantom

test/e2e: Remove tests for components this repo is not responsible for

---

test/e2e/alertmanager_test.go
test/e2e/multi_namespace_test.go
test/e2e/prometheus_test.go
test/e2e/prometheusadapter_test.go

Since testing framework supports logging we should use it instead of using golang log module.
Spawned by #314

test/e2e: use built-in logger insted of 'log'

---

pkg/client/client.go

As SCC is moving to CRD resource we need to force the `application/json` content type for the client that create the SCC manifests in order for it to create the SCC.
/cc @deads2k 
/cc @sallyom

client: force JSON client for security client

---

manifests/01-namespace.yaml

Add some labels to the openshift-monitoring namespace so people can select with network policies.
(Network policies don't let you select by name - only by labels).

BUG 1707477: manifests: label namespace

---

.gitignore
.travis.yml
Dockerfile.generate
Makefile

Running `go get` in every CI pipeline leads to unpredictable problems due to lack of ability of locking version of downloaded binary. Instead of relying on `go get` we can use pre-built container image with already installed binaries. This is an attempt on using such container. 
Container is build from https://github.com/paulfantom/dockerfiles/blob/master/jsonnet/Dockerfile and stored in [quay.io](https://quay.io/repository/paulfantom/jsonnet-ci)
PR is built on top of #350
/cc @metalmatze @s-urbaniak

Refactor build system and use pre-built container image for make targets

---

.travis.yml

see: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

the sudo key is no longer needed

---

pkg/client/client.go
pkg/client/clusteroperator.go

Status report based on https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/pkg/operator/starter.go#L123-L129
This should pass following test: https://github.com/openshift/origin/blob/master/test/extended/operators/clusteroperators.go#L60-L77
After merging this should be cherry-picked to release-4.1 branch.

[BUG 1717634] pkg/client: add support for relatedObjects in status report

---

jsonnet/jsonnetfile.json

This will pin the currently used kube-prometheus and telemter branches to a compatible version for the cluster monitoring operator to make it as easy as running `jb update` to get bug fixes in.
/cc @squat @s-urbaniak @brancz @paulfantom

Bug 1721919: Pin kube-prometheus and telemeter to release branches

---

pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

This adds the ability to configure remote write endpoints for the cluster-monitoring Prometheus server to replicate its data to a remote write backend.
@squat @sichvoge

manifests: Allow configuring remote write endpoint

---

Makefile
pkg/manifests/manifests.go
test/e2e/framework/prometheus_client.go

This adds a "test-sec" target to the Makefile, which will trigger gosec. gosec will do static analysis on the go code to check for common security issues.
This PR also tags some low priority warnings so they don't appear as errors when triggering this test.

Add gosec for security code analysis

---

Makefile
manifests/0000_50_cluster_monitoring_operator_02-role.yaml

This commit fixes the rules added by the openshift-state-metics rule. It
seems like this file was built by hand instead of using the build
script. This is a result of the renaming of the generated role file: now
that the file has a different name, the make target was wrong.
This fixes the name of the target in the Makefile and regenerates the
file.
cc @paulfantom @wanghaoran1988

Makefile: fix openshift-state-metrics role rules

---

Makefile
hack/shellcheck.sh

We need a way of running shellcheck out of container to allow its usage in our CI system. This is providing such feature based on similar script from installer repo.
Needed by https://github.com/openshift/release/pull/4437
/cc @s-urbaniak @squat

hack: add script to run shellcheck in a container and outside of it

---

manifests/0000_50_cluster_monitoring_operator_04-deployment.yaml

This will reduce number of log messages in CMO logs and allow faster debugging. Especially message like one below won't show up anymore:
> Throttling request took 394.097693ms, request: PUT:https://172.30.0.1:443/api/v1/namespaces/openshift-monitoring/configmaps/grafana-dashboard-k8s-resources-workload
/cc @LiliC @s-urbaniak

manifests: reduce logs verbosity for cluster-monitoring-operator

---

pkg/tasks/tasks.go

The logs are very silent now. We can bump the verbosity for task updates to 3 so we know where the operator state is.
/cc @LiliC

pkg/tasks: set task verbosity to 3

---

pkg/client/client.go
pkg/manifests/manifests.go
test/e2e/alertmanager_test.go
test/e2e/prometheus_test.go
vendor/modules.txt

The Daemonset, and Deployment API promoted to apps/v1
but we are still referencing v1beta2.
This fixes it
/cc @LiliC

pkg/client,pkg/manifests: bump to k8s.io/api/apps/v1

---

pkg/client/condition.go
pkg/client/condition_test.go
pkg/client/status_reporter.go
pkg/client/status_reporter_test.go
pkg/operator/operator.go
pkg/strings/strings.go
pkg/strings/strings_test.go
pkg/tasks/tasks.go

As mentioned in the https://bugzilla.redhat.com/show_bug.cgi?id=1732939, we are not setting the `Reason`.

pkg/client: Set Reason in ClusterOperatorStatusCondition

---

pkg/client/status_reporter.go
pkg/client/status_reporter_test.go

We should not set OperatorUpgradeable to false during rollout.
As per the docs:
An operator reports Upgradeable as false when it wishes to prevent
an upgrade for an admin-correctable condition. The component should
include a message that describes what must be fixed.
See docs for [this](https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md
). From what I understand we should *never* really set upgradable to false. As this prevents an upgrade and even if we fail with any reason in CMO operator, we will always be able to upgrade as well we just reconcile to the desired state anyways. But I could be missing something?
CVO seems to be backporting the new ClusterOperatorFlapping to 4.1 but from what I could tell we did not backport the Upgradeable status …

Bug 1743257: pkg/client/status_reporter.go: Set OperatorUpgradeable to true

---

manifests/0000_90_cluster_monitoring_operator_00-operatorgroup.yaml

We have been seeing errors when trying to create OperatorGroup resource when using the old API version, I think that API bug might already be fixed in 4.2, but nonetheless we can bump to using the `v1` API. See [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1740838) for background.
I asked the OLM devs and they said there should be no differences between the two versions so we are safe to bump to using the newer API version.
cc @s-urbaniak @paulfantom

Bug 1746793: manifests: Bump operators.coreos.com API version to v1

---

pkg/tasks/tasks.go

This way we only return errors when they are present, so we can bubble
up the error and actually return the task error to the call function.
cc @s-urbaniak @paulfantom

pkg/tasks/tasks.go: Return error only when its not nil

---

manifests/0000_50_cluster_monitoring_operator_04-deployment.yaml

`extensions/v1beta1` has been deprecated and might be removed in the future versions

changes apiversion of the deployment to apps/v1

---

pkg/client/clusteroperator.go
pkg/client/condition.go
pkg/client/condition_test.go
pkg/operator/operator.go
pkg/strings/strings.go
pkg/strings/strings_test.go
pkg/tasks/tasks.go

This backports the setting of the `Reason` field to release-4.1 branch. See PR https://github.com/openshift/cluster-monitoring-operator/pull/431 for the background.
cc @s-urbaniak @paulfantom

Bug 1741055: pkg/client: Set Reason in ClusterOperatorStatusCondition

---

pkg/manifests/manifests.go
pkg/tasks/configsharing.go

This is important for the OpenShift console is it reads that configmap,
sourcing route URLs for monitoring components.
/cc @LiliC @paulfantom @kyoto

pkg/tasks/configsharing: add thanos route

---

manifests/cluster-monitoring-operator.yaml

We already removed limits in 4.x, so I don't see any reason not to do that in 3.11.
/cc @brancz @s-urbaniak

Bug 1763046: manifests: remove setting limits on CMO

---

pkg/manifests/config.go

This prefixes user workload settings explicitly as tech preview.
/cc @bparees @paulfantom @LiliC @brancz

manifests/config: name user workload settings as tech preview

---

jsonnet/jsonnetfile.lock.json

Follow-up of https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/294

jsonnet: bump kubernetes-mixin to latest version

---

pkg/client/status_reporter.go

This should collect all data in `openshift-monitoring` namespace as well as all ServiceMonitor, PrometheusRule, Alertmanager, Prometheus CR across namespaces.
Checked it locally and we gather much more information.

Bug 1741685: pkg/client: add more relatedObjects to improve data from must-gather

---

test/e2e/prometheusadapter_test.go

/cc @openshift/openshift-team-monitoring 
Let's disable that test for now as something has changed in origin that quickly reconciles away the changes we do on the `requestheader-client-ca-file` content of `kube-system/extension-apiserver-authentication`.
Generally this is good, but renders this test intrinsically racy and thus flaky.

test/e2e/prometheusadapter: disable rotation test

---

pkg/manifests/manifests.go

Fix mounting trusted CA bundle by mounting it in grafana-proxy container (where it is needed) instead of grafana one.
Fixing mistake from https://github.com/openshift/cluster-monitoring-operator/pull/530
Tested manually on 4.3.0-0.ci-2019-11-22-122829 with proxy configuration enabled and grafana UI is accessible.

Bug 1776085: pkg/manifests: mount trustedCA bundle in grafana-proxy container

---

test/e2e/framework/route_client.go
test/e2e/main_test.go
test/e2e/prometheusadapter_test.go

This reenables the requestheader CA rotation e2e test
by using a different method.
It deletes the CSR signer secrets causing the extension-apiserver-authentication
configmap to be reissued.

test/e2e/prometheusadapter: reenable CA rotation test

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Currently, if a custom remote write configuration is provided
and telemetry remote write is enabled,
the latter is overwritten by the custom remote write configuration.
This fixes it by appending the custom remote write configuration
to the telemetry remote write configuration.

pkg/manifests: don't overwrite telemetry remote write

---

pkg/manifests/config.go
pkg/manifests/manifests_test.go

We were incorrectly defaulting the telemeter URL since we merged #617. 
@LiliC @s-urbaniak

pkg/manifests: Correctly default telemeter URL

---

.github/ISSUE_TEMPLATE/release.md

github: add release checklist issue template

---

pkg/manifests/manifests.go

Currently we are manipulating but not changing them. This fixes it.
The current symptom is that the new metrics configuration scheme
is effectively not enabled.

Bug 1794616: pkg/manifests: set modified telemeter-client command line arguments

---

pkg/client/client.go

If the user configures a PVC before Prometheus is created
it fails because of validation errors.
This fixes it.

Bug 1804179: pkg/client: set CreationTimestamp at create time, not only at update time

---

pkg/manifests/manifests.go

Note this PR does not re-enable telemetry by default, it merely if enabled fine tunes the remote write config. With this config we neither require resharding nor does remote write fall behind trying to replicate the data to the remote which did happen with the previous configuration. Additionally this drives the req/s per Prometheus down to ~4req/s.
@LiliC @s-urbaniak @paulfantom @simonpasquier @pgier

pkg/manifests: Configure remote write more conservatively

---

Makefile

This changes the make dependencies so that the docker image will
automatically be rebuilt when the operator is build.

rebuild docker image when the operator binary changes

---

pkg/manifests/manifests.go

pkg/manifests/telemeter: bump size limit to 5mb

---

pkg/manifests/manifests.go

When a value for a prometheus-operator arg is empty, the
default value in the manifest should be used.

override prometheus-operator args only when not empty

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

cc @openshift/openshift-team-monitoring @benjaminapetersen

Bug 1807100: pkg/manifests: rename shared config's keys to include 'Public'

---

cmd/operator/main.go

Follow-up to https://github.com/openshift/cluster-monitoring-operator/pull/686
127.0.0.1 also works with IPv6 networks due to some kernel magic and usage of a hostname (localhost) is not recommended by [golang docs](https://golang.org/pkg/net/#Listen).

expose /metrics only on localhost

---

pkg/manifests/tls.go
pkg/tasks/thanos_ruler_user_workload.go

Instead let thanos ruler use the existing Prometheus tls server cert.
This is due to the thanos restriction of only being able to pass one
grpc-client-server-name.

pkg: Remove thanos ruler server TLS cert

---

pkg/client/client.go
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go

If the current cluster's platform is `IBMCloud`, Kubernetes control plane rules are skipped.

Bug 1809353: Exclude Kubernetes control plane rules when running on IBM Cloud

---

hack/merge_cluster_roles.py

Newer versions (>= 5.1) of python-yaml (pyyaml) deprecate calling yaml.load() with no Loader argument.
https://msg.pyyaml.org/load
This fixes deprecation warnings in merge_cluster_roles.py and uses the
SafeLoader.

hack/merge_cluster_roles.py: fix deprecation warnings

---

pkg/client/status_reporter.go

We don't have such resource so it shouldn't be reported. Everything necessary is already covered by `{Resource: "namespaces", Name: namespace},`
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1817860

Bug 1817938: Do not report 'all' in relatedObjects

---

pkg/manifests/manifests.go

Bug 1819565: pkg/manifests: set correct server name for UWM prom-op service monitor

---

pkg/manifests/config.go

This isn't used anywhere and most probably a copy/paste from the Prometheus/Alertmanager configuration.
cc @pgier @lilic who worked on this part before.

pkg/manifests: remove Hostport from Thanos ruler config

---

pkg/manifests/manifests.go

This is no longer needed after cleanup in #700

Bug 1821146: pkg/manifests: remove thanos ruler rbac proxy secret

---

test/e2e/alertmanager_test.go
test/e2e/framework/framework.go
test/e2e/user_workload_monitoring_test.go

This is to help debugging failures for tests that rely on port forwarding.

test/e2e: log errors from port forwarding

---

Documentation/data-collection.md
manifests/0000_50_cluster_monitoring_operator_04-config.yaml

The OCM team relies on these queries for reporting metrics to customers
and would like to be notified when they change so that the cluster
service can adapt.

OCM: Add OpenShift Cluster Manager team

---

pkg/operator/operator.go

We already react on changes on any resources we need to reconcile on,
the resync interval should be there to just reconcile. Every 5 minutes
is too much, as we most of the time don't do anything.
We have been seeing a lot of CPU usage on every resync, this at least
lowers how often we spike.
@openshift/openshift-team-monitoring

pkg/operator/operator.go: Bump resync interval to 15 minutes

---

.github/ISSUE_TEMPLATE/release.md

No need to do a release of an upstream project as there is already a release cadence set up.

.github: remove mention of cutting upstream prometheus-operator release

---

pkg/client/client.go
pkg/tasks/thanos_ruler_user_workload.go

Clean up some remaining resources when user workload monitoring is
disabled.

Bug 1821666: cleanup thanos ruler resources

---

pkg/tasks/thanos_ruler_user_workload.go

We cannot remove this secret as it is also used by thanos querier.

Bug 1827489: pkg/tasks: do not remove GRPC secret as it is used by querier

---

pkg/tasks/prometheus.go
pkg/tasks/thanos_querier.go
pkg/tasks/thanos_ruler_user_workload.go

The grafana-datasource secret can be created in parallel with other resources which depend on it.  This might be causing test flakes.

Bug 1829974: wait for grafana datasource secret

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

This makes it easier for us to track what we changed in the current
release, and saves us time when writing release notes and talking
with customer support or writing docs. This is informational only and
OpenShift release notes should serve as the official changelog.
Also adds a reminder to fill in the CHANGELOG as part of PR templates.

CHANGELOG.md,.github/: Add CHANGELOG process for monitoring stack

---

pkg/manifests/manifests.go
pkg/tasks/alertmanager.go
pkg/tasks/grafana.go
pkg/tasks/helpers.go
pkg/tasks/prometheus.go
pkg/tasks/telemeter.go
pkg/tasks/thanos_querier.go
pkg/tasks/thanos_ruler_user_workload.go
test/e2e/alertmanager_test.go
test/e2e/thanos_querier_test.go

This change ensures that the operator waits for the trusted CA bundle
ConfigMap to be populated before proceeding with the deployment of the
monitoring components.
Note that it should fail the `e2e-aws-operator` until https://bugzilla.redhat.com/show_bug.cgi?id=1827530 is fixed.
Update May 6: https://bugzilla.redhat.com/show_bug.cgi?id=1827530 is now fixed and the CI passes.

Bug 1828702: wait for trusted CA bundle to be created

---

pkg/client/client.go
pkg/tasks/helpers.go
pkg/tasks/prometheus.go
pkg/tasks/prometheus_user_workload.go
pkg/tasks/thanos_querier.go
pkg/tasks/thanos_ruler_user_workload.go

Thanos ruler should cleanup hashed ca bundle configmaps.
In order to do this, the client library needs to handle deleting
hashed configmaps in namespaces other than the one currently set in the
k8s client.

Bug 1821666: pkg/tasks: thanos ruler cleanup

---

test/e2e/framework/client.go

The e2e tests sometimes fail while [waiting](https://github.com/openshift/cluster-monitoring-operator/blob/bb01b7d11bc965a908be5135a34607fd109d3c45/test/e2e/main_test.go#L103) for the stack to be deployed.
```
go test -v -timeout=20m ./test/e2e/ --kubeconfig /tmp/admin.kubeconfig
2020/04/10 16:07:22 wait for prometheus-k8s: error executing prometheus query: unexpected status code response, want 200, got 403: timed out waiting for the condition
FAIL	github.com/openshift/cluster-monitoring-operator/test/e2e	63.161s
FAIL
make: *** [test-e2e] Error 1 
```
Logging the HTTP response might help to identify the issue.

test/e2e/framework: log HTTP response body on non-OK status code

---

pkg/client/client.go
pkg/tasks/thanos_ruler_user_workload.go

* [ X ] No user facing changes, so no entry in CHANGELOG was needed.

Bug 1845825: Cleanup thanos ruler route when user workload monitoring is disabled

---

CHANGELOG.md
cmd/operator/main.go
examples/config/config.yaml
examples/user-workload/cluster-monitoring-configmap.yaml
pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
pkg/tasks/prometheus.go
pkg/tasks/prometheus_user_workload.go
pkg/tasks/prometheusoperator_user_workload.go
pkg/tasks/telemeter.go
pkg/tasks/thanos_querier.go
pkg/tasks/thanos_ruler_user_workload.go
test/e2e/user_workload_monitoring_test.go

Allow user workload monitoring configuration ConfigMap to be created in UWM ns

---

pkg/manifests/tls.go
pkg/manifests/tls_test.go
pkg/tasks/clustermonitoringoperator.go
pkg/tasks/prometheus.go
pkg/tasks/prometheus_user_workload.go
pkg/tasks/thanos_querier.go
pkg/tasks/thanos_ruler_user_workload.go
test/e2e/user_workload_monitoring_test.go

This is the initial implementation for a graceful rotation based on the simplified scheme. Please take a look. It still misses a small e2e test which enforces rotation.

pkg/manifests: rotate grpc key material gracefully

---

OWNERS

Move squat and metalmatze to [emeritus_approvers](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#emeritus) to stop assigning them as reviewers of PRs.

*: cleanup OWNERS file

---

examples/user-workload/README.md
examples/user-workload/configmap.yaml

@s-urbaniak As per your suggestion, PTAL

examples/user-workload/README.md: Detail user workload monitoring flow

---

hack/uwm_setup.sh
hack/uwm_setup_files/example-app-alerting-rule.yaml
hack/uwm_setup_files/example-app-service-monitor.yaml
hack/uwm_setup_files/prometheus-example-app.yaml

This Bash script added to ./hack/ configures user workload monitoring in OpenShift Container Platform 4.6 (or later) test environments. I am assuming no changelog entry is required for this.
* [*] No user facing changes, so no entry in CHANGELOG was needed.

Bash script to setup user workload monitoring OpenShift 4.6 test envs

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go

The 'hostport' parameter should be removed because it has no use in
OpenShift.

pkg: remove 'hostport' configuration

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/configsharing.go

The `sharing-config` configmap in the `openshift-monitoring` namespace
isn't needed anymore and it should be deleted by CMO.
In 4.7, the code managing this configmap can be removed.
cc @lilic what we discussed already a few minutes ago.

pkg: delete deprecated configmap

---

Makefile

We are using `openshift/origin-release:golang-1.14` as a base image in CI. This image is setting `GOFLAGS="-mod=vendor"` which in turn prevents tooling installation.

Makefile: reset GOFLAGS when installing tooling

---

Makefile

Makefile: increase timeout of e2e tests to 30m

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go

pkg/manifests: Allow users to configure EnforcedSampleLimit for user

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

We were not consistent when CMO had to update containers from
deployments, daemonsets, and so on. Containers were either accessed by
index or by name.
This change standardizes on names because it's more obvious to
understand what is being modified.

pkg/manifests: update containers consistently

---

test/e2e/framework/framework.go
test/e2e/user_workload_monitoring_test.go

There might be a race between when we retrieve the token of the service
account used for end-to-end testing and when the secret containing the
token is effectively created.
This might solve the issue we're seeing in https://github.com/openshift/release/pull/10377

test/e2e: wait until the token for e2e tests is ready

---

pkg/client/client.go
pkg/operator/operator.go

The operator didn't trigger the reconciliation loop when the
"user-workload-monitoring-config" configmap was changed because it
didn't watch for configmap resources in the
"openshift-user-workload-monitoring" namespace.
This change also ensures that the additional informers on the
"kube-system", "openshift-config-managed" and "openshift-config"
namespaces are started and synced.
This explains why the e2e test for the `TestUserWorkloadMonitoringNewConfig` test was frequently failing: because CMO wasn't triggered when changes were made to the `user-workload-monitoring-config` configmap`, the test relied on the fact that the reconciliation loop wakes up every 5 minutes even without change.

pkg/operator: add informer on configmap in user-workload namespace

---

pkg/manifests/manifests.go

This setting got lost in the large user workload monitoring ConfigMap PR changes, so this fixes the already existing field.

Bug 1852846: pkg/manifests/manifests.go: Set logLevel for prometheus Operator

---

pkg/tasks/thanos_ruler_user_workload.go
test/e2e/user_workload_monitoring_test.go

Bug 1853253: remove expired TLS secret for Thanos Ruler

---

test/e2e/user_workload_monitoring_test.go

We expect a constant number of 5 secrets
as per https://github.com/openshift/cluster-monitoring-operator/blob/f9567c5be644a867e41e2312f93c7183d5aa9c10/test/e2e/user_workload_monitoring_test.go#L894
However the underlying `countGRPCSecrets` method only lists secrets
having the `monitoring.openshift.io/hash` label set
which excludes `grpc-tls`.
It is flaky because, during GRPC TLS rotation, there are indeed
sometimes 5 secrets with the above hash label (pre- and post-rotation secrets).
The fix is to expect 4 secrets only which is the what the rotation has to converge against.

Bug 1857192: test/e2e: don't count central grpc-tls

---

CONTRIBUTING.md
Makefile
go.mod
vendor/modules.txt

Putting requirements section into CONTRIBUTING.md to show which packages are needed to be installed before doing a contribution.
Re-adding `make generate-in-docker` as a workaround solution until we remove python dependency.
/cc @s-urbaniak @lilic

Bug 1862896: add requirements section and generate-in-docker target

---

Dockerfile

- Fixing maintainer label to end with @redhat.com as this is expected
- Overriding summary label as it is inherited from base image and results with an incorrect value
- explicit switch to golang 1.14 in Dockerfile
- rearranged Dockerfile layout to be similar to others

Bug 1867510: fix CVP issues due to incorrect labels set

---

manifests/0000_50_cluster_monitoring_operator_05-deployment.yaml

Follow-up to https://github.com/openshift/cluster-monitoring-operator/pull/900

Bug 1858198: manifests: fix ciphers for CMO kube-rbac-proxy

---

Documentation/data-collection.md

Removing references to 'Developer Preview' from the 'OpenShift 4 Data Collection' document, now that OpenShift 4 is generally available.
This relates to the following:
Bug 1819097 - Telemetry Doc Still References "Developer Preview"
https://bugzilla.redhat.com/show_bug.cgi?id=1819097
[1819097] Telemetry Doc Still References "Developer Preview"
https://issues.redhat.com/browse/OCPBUGSM-1384

Bug 1819097: Removing 'Developer Preview' references from telemetry doc

---

OWNERS
cmd/operator/main.go
manifests/0000_50_cluster_monitoring_operator_05-deployment.yaml
pkg/client/client.go
pkg/tasks/tasks.go

With `-v=3`, the logs are spammed by client-go telling that client requests have been throttled. Looking at the Kubernetes code, we won't lose anything useful by lowering the verbosity level.
The change also increases the QPS and burst settings (respectively 5->20 and 10->40) because the default values aren't suited for CMO that runs lots of tasks in parallel. With QPS=100 and Burst=200, the throttling logs disappeared but we felt that these values were too high for the API server.

Bug 1860889: decrease CMO log verbosity from 3 to 2

---

assets/prometheus-adapter/service-monitor.yaml
jsonnet/prometheus-adapter.jsonnet
pkg/manifests/bindata.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/prometheusadapter.go

Bug 1862432: unmask prometheus-adapter service monitor

---

pkg/manifests/manifests.go

As discussed in the architecture call.
I am using a bug name just to circumvent bugzilla bug requirements. After this is merged I'll close a bug as WONTFIX.

Bug 1822442: Note about telemeter config

---

pkg/client/client.go
pkg/client/status_reporter.go
pkg/client/status_reporter_test.go
pkg/operator/operator.go
test/e2e/framework/framework.go

Previously CMO was only referencing the "openshift-monitoring" namespace
as a related object.
This change adds "openshift-user-workload-monitoring" namespace as well
as all the ThanosRuler and PodMonitor objects.

Bug 1881061: Add UWM namespace to the operator's related objects

---

pkg/operator/operator.go

Our reconciliation period is 15 minutes now and it seems we forgot to update our log msg. This should fix the issue.

pkg/operator: fix log msg about reconciliation interval

---

Dockerfile

Updating cluster-monitoring-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/cluster-monitoring-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating cluster-monitoring-operator builder & base images to be consistent with ART

---

hack/tools/go.mod
hack/tools/go.sum

Pinning to released version of jsonnet doesn't make much sense due to how releases for jsonnet work. More on the topic in https://github.com/prometheus-operator/kube-prometheus/pull/608
This is bringing the same go-jsonnet version as used in kube-prometheus to this repo.

update go-jsonnet to faster version

---

OWNERS

OWNERS: add dgrisonnet

---

Makefile
hack/merge_cluster_roles.py

The sort command produces different output on my system than in the CI
job, reversing the order of
`assets/prometheus-operator-user-workload/cluster-role.yaml` and
`assets/prometheus-operator/cluster-role.yaml`. This seems to be
caused by a difference in evaluating the `-` and `/`
characters. Moving the filename sort into python produces stable
output.
See early versions of #971 for an example of the difference in output
caused by the unstable sort.

make role manifest sort stable

---

OWNERS
cmd/operator/main.go
manifests/0000_50_cluster_monitoring_operator_05-deployment.yaml
pkg/client/client.go
pkg/tasks/tasks.go

Manual cherry-pick of #913. The automatic cherry-pick [didn't work](https://github.com/openshift/cluster-monitoring-operator/pull/913#issuecomment-708961885).

Bug 1888542: decrease CMO log verbosity from 3 to 2

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/configsharing.go
test/e2e/config_test.go
test/e2e/user_workload_monitoring_test.go

With 4.7 onwards we do not support techPreview configuration, so code that handles that can be removed. Users had one release to migrate, as agreed beforehand. I added a log warning users if they still use that that it will simply not work. We will also mention this in the CHANGELOG as well as in the docs for 4.7, in 4.6 we do not mention the old techPreview configuration anyways.

Remove deprecated user workload configuration

---

pkg/operator/operator.go

@paulfantom found that now we log the following by :
> ConfigMap to configure stack does not exist. Reconciling with default config every 900000000000 minutes.
This is incorrect, this adjusts it to include minutes and seconds format, see preview [here](https://play.golang.org/p/NAV03uZYEo4).
New format should be:
> ConfigMap to configure stack does not exist. Reconciling with default config every 15m0s.
This should work for all further changes to the resyncPeriod, if we change it to seconds or hours. :)

pkg/operator/operator.go: Adjust log format of resyncPeriod

---

jsonnet/cmo.jsonnet

The cmo.jsonnet file seems to have been added inadvetently. Since we
don't use it anywhere, we should remove it.

jsonnet: remove unused file

---

manifests/0000_50_cluster-monitoring-operator_00_0user-priority-class.yaml

Apparently this file is generated by hand. I tried to run make generate and it didnt changed.

Add missing default cluster profile annotation

---

cmd/operator/main.go

Increase rest config QPS value to reflect what is set in upstream
prometheus-operator.
Also, it was reported that CMO is producing a lot of throttling error
logs when it is run in an environnement with a lot CRDs. To fix that, we
can align with the value set in other component that encountered the
same issue. For instance, in `oc` the burst value was set to 200.

Bug 1899582: Increase rest config burst and QPS rate limits

---

test/e2e/thanos_querier_test.go
test/e2e/user_workload_monitoring_test.go
test/e2e/utils.go

test/e2e: Add Thanos Query Watchdog Alert test

---

test/e2e/framework/framework.go

test/e2e: fix port-forward command

---

Makefile
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
assets/prometheus-k8s/service-thanos-sidecar.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
assets/prometheus-user-workload/service-thanos-sidecar.yaml
hack/local-cmo.sh
jsonnet/prometheus-user-workload.jsonnet
jsonnet/prometheus.jsonnet
pkg/manifests/manifests.go
test/e2e/prometheus_test.go
test/e2e/user_workload_monitoring_test.go

Bug 1904985: fix TLS secrets for Thanos sidecars

---

Makefile
assets/prometheus-k8s/rules.yaml
jsonnet/rules.jsonnet

Bug 1904161: Use alertmanager_integrations metric instead of alertmanager_notifications_total for AlertmanagerReceiversNotConfigured

---

Makefile
assets/prometheus-k8s/rules.yaml
jsonnet/rules.jsonnet
test/rules/bz1879520.yaml
test/rules/bz1903464.yaml

Fixing many-to-many matching. Following rules are fixed:
- `cluster:kube_persistentvolumeclaim_resource_requests_storage_bytes:provisioner:sum`
- `cluster:kubelet_volume_stats_used_bytes:provisioner:sum`
Still working on unit tests. I will rebase it on top of https://github.com/openshift/cluster-monitoring-operator/pull/953 once it is merged.

Bug 1903464: jsonnet: fix recording rules with many-to-many matching errors

---

assets/prometheus-operator-user-workload/cluster-role-binding.yaml
assets/prometheus-operator-user-workload/cluster-role.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator-user-workload/service-account.yaml
assets/prometheus-operator-user-workload/service-monitor.yaml
assets/prometheus-operator-user-workload/service.yaml
assets/prometheus-operator/cluster-role-binding.yaml
assets/prometheus-operator/cluster-role.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-operator/prometheus-rule-validating-webhook.yaml
assets/prometheus-operator/service-account.yaml
assets/prometheus-operator/service-monitor.yaml
assets/prometheus-operator/service.yaml
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

Bump prometheus-operator to v0.44.0 to unblock https://github.com/openshift/prometheus-operator/pull/101

jsonnet: bump prometheus-operator to v0.44.0

---

assets/node-exporter/daemonset.yaml
jsonnet/node-exporter.jsonnet

The init container can now view wtmp so the new node_boots metric
can be read via a text collector. This exposes no additional security
risk except potentially allowing the node_exporter init processes
to see the users who have been logged into the system during startup.
Used by https://github.com/openshift/node_exporter/pull/74

Bug 1906570: Mount /var/log/wtmp into node_exporter init container

---

assets/prometheus-k8s/rules.yaml
jsonnet/rules.jsonnet

For all pending, running, or unknown pods report a 0 if the pod is
unready and a 1 if a pod ready. Use that to build two aggregate
average readiness fractions for openshift-* and !openshift-*
namespace pods, which we will use to measure impact of upgrades
on pod availability before, during, and after the change.
The fundamental rule can be used in the future for alerting when
the aggregate readiness drops below a threshold after we identify
a minimum bar.
This adds 2 series to telemetry for monitoring the impact of
upgrades.

Bug 1908562: Add a recording rule measuring pod readiness

---

assets/thanos-ruler/thanos-ruler.yaml
jsonnet/thanos-ruler.jsonnet
test/e2e/user_workload_monitoring_test.go

The user configuration was not propagated correctly as we were modifying the container resources via merging directly, but thanos ruler CR exposes this configuration so we should use that instead.
Opening PR to test easier, but plan on adding a test for this as well in our e2e UWM stack.

Bug 1899839: jsonnet/thanos-ruler.jsonnet: Set resources to the native spec field

---

assets/prometheus-k8s/rules.yaml
jsonnet/rules.jsonnet
test/rules/workload_cpu_usage.yaml

These recording rules report in a standard fashion the CPU available
for workloads on cluster, including generating a counter metric that
is more resilient to service disruptions and makes aggregation at
higher levels off cluster easier.
The rolling min, max, and counter rules are exposed to telemetry via
cluster:usage:* naming to indicate that these become "official" APIs
for tracking usage of the cluster.
Note that the counter is still experimental while we identify and fix issues in prometheus and thanos that make it non-optimal.  If necessary we would remove it in a subsequent change, but the cost is low and the two rolling bounds allow us to identify where gaps exist in large scale deployment.
End users will be able to compare these calculations to the values assessed in usage …

Bug 1905647: Calculate physical CPU core seconds used for consumption and report via telemetry

---

assets/prometheus-k8s/rules.yaml
jsonnet/rules.jsonnet

The overall rates of ingress traffic to the cluster are relevant in
assessing health and usage - these rules add calculations for the
rate of requests that error (5xx and other types of errors) across
the frontends, the total requests passing across the frontends, the
bandwidth used in both directions, and the number of open connections.
Error rate is split for openshift and workloads (like CPU is) in order
to better categorize trends before, during, and after upgrades.
This data is relevant for both admins and engineering teams to classify
and categorize the overall health and traffic of the cluster. This adds
seven new series to telemetry via the cluster:usage: prefix.

Bug 1907475: Add recording rules for ingress traffic and error rate

---

assets/prometheus-k8s/rules.yaml
jsonnet/rules.jsonnet

The denominator of the recording rule should be `increase`, like
the numerator, instead of `irate`. `increase` is more stable over
the intervals we are testing. Introduced due to a copy and paste
error as the rule was being refactored, and when assessing the
impact in 4.7 clusters I realized we had fractions > 1 showing up.

Bug 1913554: Ingress recording rule for error fraction is incorrect

---

hack/cluster-monitoring-operator-role.yaml.in
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
manifests/0000_50_cluster-monitoring-operator_03-role-binding.yaml

Bug 1905393: manifests: use rbac.authorization.k8s.io/v1

---

Documentation/data-collection.md
assets/grafana/dashboard-definitions.yaml
hack/cluster-monitoring-operator-role.yaml.in
jsonnet/add-release-annotation.libsonnet
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0user-priority-class.yaml
manifests/0000_50_cluster-monitoring-operator_01-namespace.yaml
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
manifests/0000_50_cluster-monitoring-operator_03-role-binding.yaml
manifests/0000_50_cluster-monitoring-operator_04-config.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
manifests/0000_50_cluster-monitoring-operator_06-clusteroperator.yaml
manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

This partially implements phase 1 of
https://github.com/openshift/enhancements#482 and does not change behavior.
Initially, all cluster-monitoring-operator manifests are included in the
single-node-developer cluster profile. Follow-on PRs may exclude any of
these that are not needed in the profile.

Bug 1915473: Annotate manifests for single-node-developer cluster profile

---

assets/prometheus-k8s/rules.yaml
jsonnet/rules.jsonnet

The number of schedulable nodes reporting ready is a key measurement
of the disruption upgrades incur as well as being an effective way
to assess whether our software is available on the hardware users
provide. Report a rolling average of node readiness measured across
all schedulable nodes and one across all nodes, using both readiness
and reachability. Also report a more general node readiness average
which matches the API view and should be higher than reachability.
This info will help assess more accurately how often we are ready
and identify future areas to improve in both reporting and practice.

Bug 1915003: Add a rule for calculating rolling node readiness

---

assets/prometheus-k8s/rules.yaml
jsonnet/main.jsonnet

Bug 1914090: jsonnet: remove Ceph block devices in rules

---

assets/prometheus-k8s/kube-rbac-proxy-secret.yaml
jsonnet/alertmanager.jsonnet
jsonnet/cluster-monitoring-operator.jsonnet
jsonnet/grafana.jsonnet
jsonnet/kube-state-metrics.jsonnet
jsonnet/main.jsonnet
jsonnet/node-exporter.jsonnet
jsonnet/prometheus-adapter.jsonnet
jsonnet/prometheus-operator-user-workload.jsonnet
jsonnet/prometheus-operator.jsonnet
jsonnet/prometheus-user-workload.jsonnet
jsonnet/prometheus.jsonnet
jsonnet/rules.jsonnet
jsonnet/thanos-querier.jsonnet
jsonnet/thanos-ruler.jsonnet

Removing ksonnet dependency. Tracked in [MON-1294](https://issues.redhat.com/browse/MON-1294).

jsonnet: remove ksonnet

---

assets/grafana/dashboard-definitions.yaml
assets/prometheus-k8s/rules.yaml
jsonnet/jsonnetfile.lock.json
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Based on upstream etcd PR https://github.com/etcd-io/etcd/pull/12600, removing the etcd v2 specific alerts from CMO as it's no longer referred for OCP 4.x clusters.
* Removed etcd-mixin deps from `jsonnet/jsonnet.lock.json`
* Ran `make jsonnet/vendor --always-make`
* Ran `make generate`

Bug 1913006: Removing etcd v2 specific alerts

---

assets/prometheus-user-workload/prometheus.yaml
jsonnet/prometheus-user-workload.jsonnet

Bug 1913386: allow only /metrics for kube-rbac-proxy in front of UWM prometheu

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

When a global Proxy with https enabled is present in an OpenShift
cluster, prometheus OAuth proxy doesn't mount the trustedCA which
results in the Prometheus route being inaccessible via OAuth.

Bug 1920901: pkg/manifests: fix prometheus-proxy trustedCA

---

assets/prometheus-k8s/prometheus.yaml
jsonnet/prometheus.jsonnet

Bug 1929277: [master] jsonnet/prometheus.jsonnet: Apply openshift-user-critical class to cluster Prometheus 

---

assets/prometheus-k8s/prometheus.yaml
jsonnet/prometheus.jsonnet

Bug 1929278: [4.7]: jsonnet/prometheus.jsonnet: Apply openshift-user-critical class to cluster Prometheus 

---

assets/prometheus-k8s/rules.yaml
jsonnet/main.jsonnet
jsonnet/rules.jsonnet

The upstream etcd alert is incorrect because it only excludes instance labels, but OpenShift runs etcd in a pod and therefore the pod label must be excluded.
Exclude the upstream alert, improve the resiliency of the alert expression, target the alert to the expected job for the cluster etcd
(job="etcd"), update the description and health text to include a clearer description of what insufficient members means and consequences and some impact actions, and separate the alert into its own rule group to prepare (in the future) of moving the alert into the cluster-etcd-operator repo.

Bug 1929944: etcdInsufficientMembers is wrong when etcd is in a pod

---

assets/prometheus-k8s/rules.yaml
jsonnet/main.jsonnet
jsonnet/rules.jsonnet

The KubeDeploymentReplicasMismatch alert fires after 15m, but deployments that run on all three control plane nodes may see disruption that lasts for 3 x 20m = 1h during upgrades of slow to reboot metal hardware. Instead, prevent the alert rule from firing when a control plane nodes are unready (which should be covered by other alerts). While this may mask failures that occur on non control plane nodes, once the control plane is recovered that alert will begin to fire. Provide the alert with a more accurate description.
A future alert may be able to leverage a better metric such as "1 if and only if the control plane is not being upgraded and has been progressing for less than X budget per machine", but that would only be slightly less accurate and simpler may be better.
Found while …

jsonnet/rules: Mask KubeDeploymentReplicasMismatch alert for upgrade

---

pkg/manifests/assets.go

cc @paulfantom I've got a `fatal error: concurrent map read and map write` panic while testing the operator locally.

pkg/manifests: fix data race when accessing assets

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Backport of #1047 to release-4.7.

Bug 1926876: pkg/manifests: fix prometheus-proxy trustedCA

---

jsonnet/control-plane.libsonnet
jsonnet/remove-runbook-urls.libsonnet

It seems that we only run `make shellcheck` in CI and not `make format`. I'll open a tech-debt issue to fix that.

Run jsonnet-fmt

---

Makefile

To test alerting rules we create a temporary file `tmp/rules.yaml` with all alerts and recording rules. This file was created incorrectly and it was missing a lot of rules leading to issues like one seen in CI in https://github.com/openshift/cluster-monitoring-operator/pull/1072. This PR should fix that issue.
Before fix:
```
$ make tmp/rules.yaml 
$ wc -l tmp/rules.yaml 
1537 tmp/rules.yaml
```
After fix:
```
$ make tmp/rules.yaml 
$ wc -l tmp/rules.yaml 
2638 tmp/rules.yaml
```

*: include all groups when testing prometheus rules

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/exclude-rules.libsonnet
jsonnet/rules.libsonnet

The TargetDown alert fires today when multiple nodes are upgraded
in sequence and one or more daemonsets are successively out for
longer than 10m. Since upgrade is normal behavior and we know that
nodes will be upgrading continuously as the control plane rolls
out, alter the alert to exclude unschedulable nodes (a reasonably
accurate proxy for a node being upgraded today that can be improved
later), wait a longer period of time before firing (60m of
continuous availability), and describe the alert in more detail.
TargetDown is still useful as a bedrock symptom-based alert for
target disruption since it is likely to catch a very wide range
of problems related to running in Kubernetes, so we don't restrict
it further. In investigation this alert fires commonly in clusters
(90% of fires last …

Bug 1933805: TargetDown should exclude unschedulable nodes

---

pkg/manifests/manifests.go

Backport of #1047 to release-4.6.

Bug 1920898: [4.6] pkg/manifests: fix prometheus-proxy trustedCA

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json

jsonnet: fix etcd mixin import

---

Makefile
hack/check-rec-rule-usage.sh
hack/find-rules.sh

This script aggregates all recording rules from the assets directory and
checks whether they are used on alerts or dashboards.

hack: add check script for unused rules

---

assets/prometheus-k8s/prometheus-rule.yaml
assets/thanos-querier/prometheus-rule.yaml
assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
jsonnet/patch-rules.libsonnet

Bring the following upstream fix https://github.com/thanos-io/thanos/commit/95b2fe908b29977a20f695afac33f6257bb2d3ea that should prevent the ThanosSidecarUnhealthy alert from firing in CI.
Also readjust the Thanos sidecar alerts to `warning` severity and their duration to `1h` as per the recent discussions around alerting in OCP.

Bug 1921335: Fix and adjust ThanosSidecarUnhealthy alert

---

CHANGELOG.md
assets/thanos-querier/prometheus-rule.yaml
jsonnet/patch-rules.libsonnet

This change tweaks the upstream alerts to comply with the OpenShift
requirements:
* The severity is set to "warning" for all alerts.
* The "for" duration is increased to 1h for all alerts.
* The latency alerts are removed.

Bug 1934163: adjust Thanos querier alerting rules

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet
pkg/operator/operator.go

/cc @openshift/openshift-team-monitoring 
@simonpasquier does that reflect what you had in mind?

Bug 1932624: jsonnet/rules,pkg/operator: use gauge based reconcilation state metrics and alerting

---

assets/kube-state-metrics/deployment.yaml
jsonnet/kube-state-metrics.libsonnet

To be able to merge the https://github.com/openshift/kube-state-metrics/pull/47 cleanly, we need to remove this flag first as it was changed in 2.0 release.
cc @simonpasquier please have a look. Thank you!

Remove kube-state-metrics flag temporary

---

assets/control-plane/prometheus-rule.yaml
jsonnet/patch-rules.libsonnet

Bug 1943667: increase for duration of KubeDaemonSetRolloutStuck

---

CHANGELOG.md
assets/alertmanager/pod-disruption-budget.yaml
assets/control-plane/prometheus-rule.yaml
assets/grafana/dashboard-definitions.yaml
assets/kube-state-metrics/cluster-role-binding.yaml
assets/kube-state-metrics/cluster-role.yaml
assets/kube-state-metrics/deployment.yaml
assets/kube-state-metrics/prometheus-rule.yaml
assets/kube-state-metrics/service-account.yaml
assets/kube-state-metrics/service-monitor.yaml
assets/kube-state-metrics/service.yaml
assets/prometheus-adapter/config-map.yaml
assets/prometheus-k8s/pod-disruption-budget.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-k8s/role-specific-namespaces.yaml
assets/prometheus-user-workload/pod-disruption-budget.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/prometheus-user-workload/role-specific-namespaces.yaml
jsonnet/jsonnetfile.lock.json
jsonnet/kube-state-metrics.libsonnet
jsonnet/main.jsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

/hold
Taking over https://github.com/openshift/cluster-monitoring-operator/pull/1093

  Bump kube-state-metrics to v2.0.0-rc.1

---

assets/control-plane/prometheus-rule.yaml
jsonnet/patch-rules.libsonnet
pkg/manifests/manifests_test.go

Kubernetes scheduler and Kubernetes controller rules are managed by their respective operators [1][2]:
* https://github.com/openshift/cluster-kube-scheduler-operator/pull/180
* https://github.com/openshift/cluster-kube-controller-manager-operator/pull/298
There was already a [pull request](https://github.com/openshift/cluster-monitoring-operator/pull/516) to remove these rules from CMO but it never merged because at the time, it wasn't easy to customize the CMO assets.

Bug 1944974: remove KubeControllerManagerDown and KubeSchedulerDown alerts

---

assets/control-plane/prometheus-rule.yaml
jsonnet/patch-rules.libsonnet

 Bug 1943667: fix alert description

---

assets/thanos-querier/deployment.yaml
jsonnet/thanos-querier.libsonnet

Looking at a recent e2e test run, the p90 value of CPU usage is closer to 10m than 5m so increasing the value a bit.

Bug 1938465: increase CPU requests for Thanos querier

---

assets/prometheus-k8s/prometheus.yaml
jsonnet/prometheus.libsonnet

Switch the priorityclass to system-cluster-critical again

Bug 1934516: Change prometheus priority class to system-cluster-critical again

---

Makefile
hack/build-jsonnet.sh
jsonnet/ibm-cloud-managed-profile.libsonnet
jsonnet/main.jsonnet
manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml

Part 2 of cluster profiles support for IBM Cloud.
Introduces a directory that will contain profile-specific patches.
Profile-specific manifests are generated with 'make profile-manifests'
(which is called by 'make generate'). The generate test should verify
that the profiles are up to date.
On IBM Cloud the monitoring operator needs to run on worker nodes, thus the
master node selector needs to be removed from the operator deployment
manifest.

IBM Cloud manifest profile patch

---

assets/kube-state-metrics/service-monitor.yaml
jsonnet/kube-state-metrics.jsonnet

Bug 1945851: Backport Remove the "instance" and "pod" labels for kube-state-metrics metrics

---

assets/kube-state-metrics/cluster-role.yaml
assets/kube-state-metrics/deployment.yaml
jsonnet/kube-state-metrics.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml

Follow-up of #1099, requires https://github.com/openshift/kube-state-metrics/pull/47
/hold

Update denied metrics for kube-state-metrics 

---

assets/prometheus-adapter/api-service.yaml
assets/prometheus-adapter/cluster-role-aggregated-metrics-reader.yaml
assets/prometheus-adapter/cluster-role-binding-delegator.yaml
assets/prometheus-adapter/cluster-role-binding.yaml
assets/prometheus-adapter/cluster-role-server-resources.yaml
assets/prometheus-adapter/cluster-role.yaml
assets/prometheus-adapter/config-map.yaml
assets/prometheus-adapter/deployment.yaml
assets/prometheus-adapter/role-binding-auth-reader.yaml
assets/prometheus-adapter/service-account.yaml
assets/prometheus-adapter/service-monitor.yaml
assets/prometheus-adapter/service.yaml
jsonnet/main.jsonnet

Bug 1920700: Bump prometheus-adapter to v0.8.4

---

CHANGELOG.md
assets/control-plane/prometheus-rule.yaml
jsonnet/patch-rules.libsonnet

According to what we've seen in CI, it might take more time for the
apiservice to claim the aggregated API during upgrades than what has
been set in the upstream alert. It might take up to 15 minutes for the
aggregated API to be claimed during upgrades. Thus, we need to increase
the `for` clause to 15m to reflect that.
Note that from the CI failures, we might need to re-increase the duration to
30m for SNO clusters, but the alert might be firing for good reasons there.
The apiserver is heavily degraded and a lot more aggregated API than
usual are reported to be down. Even Prometheus seems to be degraded
as the following message is outputted:
```
Watchdog alert had missing intervals during the run, which may be a sign of a Prometheus outage in violation of the prometheus query SLO of 100% …
```

Bug 1940933: jsonnet: make AggregatedAPIDown more resilient to OCP upgrades

---

assets/alertmanager/alertmanager.yaml
assets/grafana/deployment.yaml
assets/kube-state-metrics/deployment.yaml
assets/node-exporter/daemonset.yaml
assets/openshift-state-metrics/deployment.yaml
assets/prometheus-adapter/deployment.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/telemeter-client/deployment.yaml
assets/thanos-querier/deployment.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/add-workload-annotation.libsonnet
jsonnet/main.jsonnet
manifests/0000_50_cluster-monitoring-operator_01-namespace.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml

In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.

Add management workload annotations

---

pkg/client/status_reporter.go
pkg/client/status_reporter_test.go

Bug 1948082: Set unavailable message

---

assets/prometheus-adapter/deployment.yaml
assets/thanos-querier/deployment.yaml
jsonnet/prometheus-adapter.libsonnet
jsonnet/thanos-querier.libsonnet

Apply the following HA conventions to thanos-querier and
prometheus-adapter:
- 2 replicas
- Hard pod anti-affinity on hostname
- Set the maxUnavailable rollout strategy to 25%

Bug 1948711: jsonnet: apply HA conventions

---

assets/prometheus-adapter/deployment.yaml
assets/thanos-querier/deployment.yaml
jsonnet/prometheus-adapter.libsonnet
jsonnet/thanos-querier.libsonnet

This reverts commit ade82fcbd3e4cf69ab0b62d5a21f496e66d7fbae.
This reverts commit 68f595a3f40829d1be19f0b0eaf87539849b96a4.

Bug 1950761: Revert: jsonnet: apply HA conventions

---

CHANGELOG.md
pkg/manifests/config.go
pkg/operator/operator.go
pkg/tasks/prometheus_user_workload.go
pkg/tasks/prometheusoperator_user_workload.go
pkg/tasks/thanos_querier.go
pkg/tasks/thanos_ruler_user_workload.go

Remove `techPreviewUserWorkload` from CMO's configmap as it is deprecated in 4.8.

Bug 1951505: Remove deprecated techPreviewUserWorkload

---

assets/control-plane/service-monitor-kubelet.yaml
jsonnet/control-plane.libsonnet

Bug 1951052: drop CRI-O image metrics

---

jsonnet/ibm-cloud-managed-profile.libsonnet
jsonnet/main.jsonnet

This is partly preparation of the upcomming jsonnet-fmt ci job, partly
just maintanence.

Bug 1952032: jsonnet: add format changes made by make jsonnet-fmt

---

assets/prometheus-adapter/deployment.yaml
assets/thanos-querier/deployment.yaml
jsonnet/prometheus-adapter.libsonnet
jsonnet/thanos-querier.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Apply the following HA conventions to thanos-querier and
prometheus-adapter:
- 2 replicas
- Hard pod anti-affinity on hostname
- ~~Set the maxUnavailable rollout strategy to 25%~~ Set maxUnavailable rollout strategy to 1
For non-HA topology, we remove the anti-affinity constraints as they are not needed with 1 replica.

Bug 1948711: Apply HA conventions to prometheus-adapter and thanos-ruler

---

assets/prometheus-k8s/prometheus.yaml
jsonnet/prometheus.jsonnet

Reverts openshift/cluster-monitoring-operator#1062
Once https://github.com/openshift/kubernetes/pull/642 merges, `system-cluster-critical` pods will not have -997 OOM score making it easily killable by OOMKiller.

Bug 1945856: Revert "Bug 1934516: [4.7]: jsonnet/prometheus.jsonnet: Apply system-cluster-critical class to cluster Prometheus "

---

assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/prometheus.yaml
jsonnet/anti-affinity.libsonnet
jsonnet/main.jsonnet
jsonnet/prometheus-adapter.libsonnet
jsonnet/thanos-querier.libsonnet

Add hard anti-affinity constraints on hostname to the platform
and user-workload-monitoring Prometheuses to comply with the
high-availability conventions.

Bug 1949262: jsonnet: add hard anti-affinity to Prometheuses

---

assets/control-plane/service-monitor-kubelet.yaml
jsonnet/control-plane.libsonnet

The `container_memory_failures_total` metric isn't used anywhere and it generates at least 4 series per container.

Bug 1955457: drop container_memory_failures_total metric

---

assets/control-plane/service-monitor-kubelet.yaml
jsonnet/control-plane.libsonnet

There was a stupid typo in #1125 (the source label to match should be `__name__`).

Bug 1955445: fix dropped crio metrics

---

CHANGELOG.md
assets/control-plane/prometheus-rule.yaml
jsonnet/patch-rules.libsonnet

This reverts commit 0746d65ac8ce639f769d88ed623fb2931e355eab.
Revert the previous attempt to fix `AggregatedAPIDown` alerts during OCP upgrades. It turned out that the alert wasn't at cause, but rather prometheus-adapter not being highly-available. There is a separate on-going effort to make it HA in #1119.

Bug 1940933: Revert "jsonnet: make AggregatedAPIDown more resilient"

---

assets/node-exporter/daemonset.yaml
jsonnet/node-exporter.libsonnet

The node_exporter's mountstats collector gathers low-level metrics from
NFS mountstats (such as operation timings, transport and event
statistics). When available, these metrics can have high-cardinality
(for one cluster, we've seen that it can account for half of *all* the
series) though they aren't used by any rule or dashboard.
The mountstats collector had been enabled in #409 following a customer
request for enhancement. But looking at the history, the customer was
asking for the kubelet_volume_* metrics which weren't supported by their
storage provider at this time (it's been fixed since then NetApp/trident#134). The
mountstats metrics don't fill the same need and are superfluous.

Bug 1955467: remove node_mountstats_nfs_* metrics

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

`kube_node_status_capacity` is updated in [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/CHANGELOG.md) 2.0. New change need us to use unit label to retrieve the metric

Bug 1955051: Update kube node status capacity metric

---

assets/kube-state-metrics/deployment.yaml
jsonnet/main.jsonnet

Bug 1955478: drop high-cardinality metrics from kube-state-metrics which aren't used

---

assets/kube-state-metrics/deployment.yaml
jsonnet/kube-state-metrics.libsonnet

No changelog entry as this is a feature we already had, but it went away with KSM v2 update.

Bug 1950908: Allow all pod labels in metric labels

---

test/e2e/alertmanager_test.go
test/e2e/prometheus_test.go
test/e2e/user_workload_monitoring_test.go

The end-to-end tests validating persistent storage configuration
explicitly required the 'gp2' storage class which is AWS specific. By
removing any requirement on storage class, we ensure that the end-to-end
tests can be truly agnostic.

Bug 1957832: remove dependency of e2e tests on AWS

---

assets/control-plane/service-monitor-kubelet.yaml
jsonnet/control-plane.libsonnet

`container_runtime_crio_image_pulls_by_name_skipped` was still collected.

Bug 1955445: drop more CRI-O metrics

---

assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
jsonnet/prometheus-operator-user-workload.libsonnet
jsonnet/prometheus-operator.libsonnet

Bug 1958015: jsonnet: fix setting resource limits on config-reloader containers

---

assets/prometheus-adapter/pod-disruption-budget.yaml
hack/cluster-monitoring-operator-role.yaml.in
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/client/client.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/prometheusadapter.go

In high-availability topology, prometheus-adapter need to have a PodDisruptionBudget to align with OpenShift `Upgrades and Reconfiguration` conventions. https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#upgrade-and-reconfiguration

Bug 1953647: Add prometheus-adapter PodDisruptionBudget

---

Makefile

Download the bianry of go-jsonnet instead of building it as it requires
golang 1.10+ and we are only running golang 1.9 in CI.
Also pin gojsontoyaml to a particular commit to use yaml.v2 2.3.0
instead of yaml.v2 2.4.0 which provide a fix that changes the
indentation we had previously.

[release-3.11]: Fix make generate

---

assets/prometheus-k8s/service-monitor-kubelet.yaml
jsonnet/prometheus.jsonnet

Backport of #1125, #1133 and #1148 (the automatic cherrypick isn't possible because the `jsonnet` layout has changed a lot).

[4.7] Bug 1955449: drop crio image metrics

---

assets/prometheus-adapter/config-map.yaml
jsonnet/main.jsonnet

This PR overrides the nodeQueries in the prometheus-adapter config-map to include windows_exporter queries in order to retrieve resource metrics: CPU and memory for Windows nodes. 
This fix has been merged upstream in [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus/pull/1058)
Ran commands:
`make generate`
This PR has been opened in an effort to merge this fix into release-4.7 since it is not included in release-0.7 of kube-prometheus.

Bug 1952149: oc adm top reporting unknown status for Windows node

---

assets/prometheus-k8s/service-monitor-kubelet.yaml
jsonnet/prometheus.jsonnet

The container_memory_failures_total metric isn't used anywhere and it generates at least 4 series per container.

Bug 1955462: drop container_memory_failures_total metric backport

---

assets/node-exporter/daemonset.yaml
jsonnet/node-exporter.jsonnet

The node_exporter's mountstats collector gathers low-level metrics from
NFS mountstats (such as operation timings, transport and event
statistics). When available, these metrics can have high-cardinality
(for one cluster, we've seen that it can account for half of all the
series) though they aren't used by any rule or dashboard.
The mountstats collector had been enabled in #409 following a customer
request for enhancement. But looking at the history, the customer was
asking for the kubelet_volume_* metrics which weren't supported by their
storage provider at this time (it's been fixed since then NetApp/trident#134). The
mountstats metrics don't fill the same need and are superfluous.
Backported from #1139

Bug 1955469: remove node_mountstats_nfs_* metrics

---

assets/kube-state-metrics/deployment.yaml
jsonnet/kube-state-metrics.jsonnet

Manual backport of #1142 because the jsonnet directory has diverged a lot between 4.7 and 4.8.

[4.7] Bug 1955482: Drop high-cardinality metrics from kube-state-metrics which aren't used

---

pkg/client/client.go
pkg/tasks/prometheus_user_workload.go

The ServiceMonitor for the user-workload Prometheus instance was
renamed from `prometheus` to `prometheus-user-workload` in #1044.  The
old ServiceMonitor should be removed now.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1959278

Bug 1959278: Remove obsolete user-workload ServiceMonitor

---

Makefile
hack/check-assets.sh
hack/cluster-monitoring-operator-role.yaml.in
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/client/client.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/alertmanager.go
pkg/tasks/prometheus.go
pkg/tasks/prometheus_user_workload.go

Added management of PodDisruptionBudget objects
Added a script to check if all objects in `assets/` are referenced in `pkg/manifests/manifests.go`.

Bug 1933847: Manage PodDisruptionBudget objects

---

assets/kube-state-metrics/deployment.yaml
jsonnet/jsonnetfile.lock.json

Bug 1955478: fix regex patterns in kube-state-metrics deny list

---

assets/alertmanager/alertmanager.yaml
assets/kube-state-metrics/deployment.yaml
assets/node-exporter/daemonset.yaml
assets/prometheus-adapter/deployment.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-operator/deployment.yaml
assets/thanos-querier/deployment.yaml
jsonnet/alertmanager.libsonnet
jsonnet/kube-state-metrics.libsonnet
jsonnet/node-exporter.libsonnet
jsonnet/prometheus-adapter.libsonnet
jsonnet/prometheus-operator.libsonnet
jsonnet/prometheus.libsonnet
jsonnet/thanos-querier.libsonnet
manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml

This PR is a follow up of https://github.com/openshift/cluster-monitoring-operator/pull/1158 and further adjusts memory requests for monitoring components.

Bug 1962261: further adjust memory usage

---

assets/grafana/deployment.yaml
jsonnet/grafana.libsonnet

Before this PR, `/metrics` endpoint of Grafana deployment is not protected and anyone can see the live prometheus metrics. Though it is not a super critical security bug, it is good to protect it from unauthorised access.

Bug 1960767: Protect Grafana metrics endpoint

---

pkg/tasks/prometheus_user_workload.go

`NewPodDisruptionBudget` may return nil PodDisruptionBudget when `!f.infrastructure.HighlyAvailableInfrastructure()`:
https://github.com/openshift/cluster-monitoring-operator/blob/cddf199b164c64b365867cdcc449e6c75825337a/pkg/manifests/manifests.go#L2430-L2432
this would cause a segfault later when `DeletePodDisruptionBudget` was
called with that nil `PodDisruptionBudget`, causing Single Node clusters
to fail to install.

Bug 1963833: don't attempt to delete nil PodDisruptionBudget object

---

assets/alertmanager/pod-disruption-budget.yaml
assets/prometheus-adapter/pod-disruption-budget.yaml
assets/prometheus-k8s/pod-disruption-budget.yaml
assets/prometheus-user-workload/pod-disruption-budget.yaml
jsonnet/alertmanager.libsonnet
jsonnet/prometheus-adapter.libsonnet
jsonnet/prometheus-user-workload.libsonnet
jsonnet/prometheus.libsonnet

The policy/v1 `apiVersion` is supported starting from Kubernetes 1.21.
As a consequence, we cannot make the change directly in kube-prometheus
since it would break backward compatibility.

Bug 1961081: update PodDisruptionBudget api version to policy/v1

---

assets/kube-state-metrics/deployment.yaml
jsonnet/kube-state-metrics.jsonnet

Bug 1955482: fix kube-state-metrics regexp patterns

---

pkg/client/client.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Pull request #1176 updated the assets managed by the operator
to use the policy/v1 version for all pod disruption budgets.
This was not sufficient to make the operator use the v1 version.
This commit updates the operator code to use the v1 client-go APIs
to make sure no deprecation warnings show in the logs.

Bug 1961081: update pdb apiversion to v1

---

assets/prometheus-k8s/rules.yaml
jsonnet/main.jsonnet

This PR is a partial backport of https://github.com/openshift/cluster-monitoring-operator/pull/1044 to remove unactionable KubeClientCertificateExpiration alert.

Bug 1950290: remove KubeClientCertificateExpiration alert rule

---

assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/prometheus.yaml
jsonnet/prometheus-user-workload.jsonnet
jsonnet/prometheus.jsonnet

Backport of https://github.com/openshift/cluster-monitoring-operator/pull/1135 to release-4.7.
I couldn't cherry-pick the commit because of the changes made to kube-prometheus in 4.8.

Bug 1957703: [4.7]: Add hard anti-affinity constraints to Prometheuses

---

pkg/operator/operator.go

It looks like when the watch for the etcd-metric-serving-ca ConfigMap
was added in 632cddad, there was a typo in the name used for the
watch, but not elsewhere, e.g. when actually retrieving the object.

Bug 1965367: pkg/operator: Fix typo in etcd-metric-serving-ca resource name

---

assets/prometheus-k8s/prometheus.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/thanos-ruler/thanos-ruler.yaml
cmd/operator/main.go
jsonnet/main.jsonnet
jsonnet/prometheus-operator-user-workload.libsonnet
jsonnet/prometheus-operator.libsonnet
jsonnet/prometheus-user-workload.libsonnet
jsonnet/prometheus.libsonnet
jsonnet/thanos-ruler.libsonnet
pkg/client/client.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
pkg/tasks/prometheusoperator.go
pkg/tasks/prometheusoperator_user_workload.go
test/e2e/framework/framework.go

Instead of the `--namespaces` and `deny-namespaces` flags to specify
which namespaces the Prometheus operator should watch/not watch, we
configure the Prometheus resources with the proper namespace selectors.
In practice, the Prometheus `k8s` resource looks for all namespaces with
the `openshift.io/cluster-monitoring=true` label and The Prometheus
`user-workload` resource for all namespaces without the
`openshift.io/cluster-monitoring=true` label.
The goal is to decrease the number of listers/watchers that the operator
needs to maintain which should reduce the load on the API server.
Concretely with the `--namespaces` flag, the operator would create
40 listers/watchers (1 per namespace) per watched object type (secret,
prometheus, statefulset, ...). With namespace selectors, the
operator …

Bug 1957190: use NamespaceSelector instead of explicit allow/deny list

---

assets/alertmanager/alertmanager.yaml
assets/prometheus-k8s/prometheus.yaml
assets/thanos-querier/deployment.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/alertmanager.libsonnet
jsonnet/prometheus.libsonnet
jsonnet/thanos-querier.libsonnet
jsonnet/thanos-ruler.libsonnet

Currently the /metrics endpoint of alertmanager/prometheus/thanos-querier are accessible without any authentication. This must be fixed to avoid any leakage of any sensitive metrics details.

Bug 1964334: guard monitoring related /metrics endpoint from unauthorised access

---

assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/thanos-querier/cluster-role-binding.yaml
assets/thanos-querier/cluster-role.yaml
assets/thanos-querier/deployment.yaml
assets/thanos-querier/grpc-tls-secret.yaml
assets/thanos-querier/kube-rbac-proxy-rules-secret.yaml
assets/thanos-querier/kube-rbac-proxy-secret.yaml
assets/thanos-querier/oauth-cookie-secret.yaml
assets/thanos-querier/oauth-htpasswd-secret.yaml
assets/thanos-querier/prometheus-rule.yaml
assets/thanos-querier/route.yaml
assets/thanos-querier/service-account.yaml
assets/thanos-querier/service-monitor.yaml
assets/thanos-querier/service.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/main.jsonnet

The following PR bumps thanos to v0.20.2
https://github.com/openshift/thanos/pull/58

Bug 1945500: Bump thanos version to v0.20.2

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

Bug 1933708: Add deployment config in recording rule

---

assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/prometheus.yaml
jsonnet/prometheus-user-workload.jsonnet
jsonnet/prometheus.jsonnet

Revert #1150 because it can cause regressions for clusters using persistent storage. More details in https://bugzilla.redhat.com/show_bug.cgi?id=1967614

Bug 1967966: Switch back anti-affinity to soft from hard for Prometheus

---

assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/prometheus.yaml
jsonnet/anti-affinity.libsonnet
test/e2e/prometheus_test.go

Reverts https://github.com/openshift/cluster-monitoring-operator/pull/1135/files
**Why revert?**
CMO fails repeatedly because the prometheus-k8s statefulset never converges to the desired state
https://bugzilla.redhat.com/show_bug.cgi?id=1967614#c0

Bug 1967614: Revert anti-affinity to soft

---

assets/prometheus-operator/prometheus-rule-validating-webhook.yaml
jsonnet/prometheus-operator.libsonnet

The default failurePolicy(fail) prevents the CVO from reconciling the deletion of openshift-monitoring namespace.

Bug 1949711: Ignore failures from prometheusrules.openshift.io webhook

---

assets/control-plane/prometheus-rule.yaml
jsonnet/patch-rules.libsonnet

Reduce threshold of AggregatedAPIDown alert from 85 to 70 to be more
resilient to DNS rollouts and CA rotations. A time window of 1m30 was
too tight when facing these, so we want to increase the window to 3m.

Bug 1970624: jsonnet: reduce threshold of AggregatedAPIDown

---

CHANGELOG.md
assets/grafana/config.yaml
assets/grafana/dashboard-datasources.yaml
assets/grafana/dashboard-definitions.yaml
assets/grafana/dashboard-sources.yaml
assets/grafana/deployment.yaml
assets/grafana/service-monitor.yaml
assets/grafana/service.yaml
jsonnet/main.jsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

This patch bumps up the Grafana version to 7.5.5 and updates all
related asserts and manifests.
See also: https://bugzilla.redhat.com/show_bug.cgi?id=1931277

Bug 1967803: update Grafana version to 7.5.5

---

Makefile
hack/local-cmo.sh

This patch
* Adds a `make run-local` target that builds the operator and runs
hack/local-cmo.sh
* fixes the old behaviour that overwrote all the existing `spec.overrides` in
clusterversion/version with just CMO in umanaged state to append CMO
disable to the existing `overrides`
* validates if all required tools are installed before modifying the cluster
* fixes disabled shellcheck lints

More robust local CMO script

---

hack/uwm_setup_files/prometheus-example-app.yaml
test/e2e/user_workload_monitoring_test.go

We've started publishing images to GitHub's containers registry under
the RHOBS organization for the prometheus-example-app.  This uses the
new images in place of the previous ones from a personal account.

hack,test: Use new ghcr.io images for prometheus-example-app

---

test/e2e/alertmanager_test.go
test/e2e/framework/client.go
test/e2e/user_workload_monitoring_test.go

Follow-up of #1194
@bison I knew that other places were still looking for improvements and https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/1227/pull-ci-openshift-cluster-monitoring-operator-master-e2e-agnostic-operator/1405453185732055040 reminded me which ones :smiley:

test/e2e: make tests more resilient to hiccups

---

pkg/manifests/config.go
pkg/manifests/manifests_test.go

Correct the serverName for json tag.
Signed-off-by: clyang82 <chuyang@redhat.com>

Correct serverName json tag

---

Makefile

With https://github.com/openshift/release/pull/17927 the test-rule
target is now its own ci case. No need to run test-rules within the
test-unit target anymore.
This also adds the test-rules target to the test target for convenience.

Makefile: drop test-rules from test-unit target

---

assets/prometheus-adapter/deployment.yaml
jsonnet/alertmanager.libsonnet
jsonnet/main.jsonnet
jsonnet/prometheus-adapter.libsonnet
jsonnet/prometheus-operator.libsonnet
jsonnet/prometheus-user-workload.libsonnet
jsonnet/prometheus.libsonnet
jsonnet/thanos-querier.libsonnet

Running sslscan against the prometheus adapter secure port reports two
insecure SSL ciphers, ECDHE-RSA-DES-CBC3-SHA and DES-CBC3-SHA.
This commit removes those ciphers from the list.
It is not enough to pull in changes from the [kube-prometheus PR](https://github.com/prometheus-operator/kube-prometheus/pull/1216) since we override the prometheus-adapter args completely:

Bug 1970147: jsonnet: disable insecure cypher suites for prometheus-adapter

---

assets/control-plane/prometheus-rule.yaml
assets/grafana/dashboard-definitions.yaml
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Sync with kube-prometheus

---

Makefile

Upstream sha version for jsonnet code are kept in the
`jsonnet/jsonnetfile.lock.json`. This file is not a dependency for
generating assets and running make generate can lead to generating assets
from stale jsonnet code.
This commit adds the `jsonnet/jsonnetfile.lock.json` as a dependency of the
`$(JSONNET_VENDOR)` Makefile target. With this we ensure the
`jsonnet/vendor` folder is refetched every time a new version of an
upstream jsonnet dependency has been commited.

Makefile: update $(JSONNET_VENDOR) dependencies

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

Reverts openshift/cluster-monitoring-operator#1245
We're not entirely sure this PR is related, but we're seeing a bunch of `KubeDeploymentReplicasMismatch` firing in CI (e.g. [here][1]), so rolling this back to see if it helps.
[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oc/843/pull-ci-openshift-oc-master-e2e-aws-upgrade/1408423006006415360

Revert "alert:KubeDeploymentReplicasMismatch: only fire if cluster is in ready state"

---

test/e2e/alertmanager_test.go
test/e2e/config_test.go
test/e2e/framework/client.go
test/e2e/framework/framework.go
test/e2e/framework/secret.go
test/e2e/main_test.go
test/e2e/multi_namespace_test.go
test/e2e/priority_class_test.go
test/e2e/prometheus_test.go
test/e2e/prometheusadapter_test.go
test/e2e/thanos_querier_test.go
test/e2e/user_workload_monitoring_test.go
test/e2e/validatingwebhook_test.go

As in title [MON-1251](https://issues.redhat.com/browse/MON-1251)
This is first PR to remove context.TODO() and replace with real context in tests

Remove context.TODO() from client_go method calls

---

Makefile

Add a Makefile rule called `check-runbooks` to verify that the links
specified in the runbook_url annotation of alerts shipped in OpenShift
aren't broken.
/cc @paulfantom

Makefile: add check to verify runbook urls

---

assets/control-plane/prometheus-rule.yaml
jsonnet/patch-rules.libsonnet

This pull request reverts [a patch](https://github.com/openshift/cluster-monitoring-operator/pull/1211) to version 4.8 that mitigates a problem when upgrading monitoring components from 4.7 to 4.8: AggregatedAPIDown is triggered due to a long period of unavailability of prometheus adapter. Both deployments are offline at the same time during the upgrade.
After integrating these 2 PRs([PR1](https://github.com/openshift/cluster-monitoring-operator/pull/1149), [PR2](https://github.com/openshift/cluster-monitoring-operator/pull/1124)) into 4.8 release, Prometheus Adapter is able to keep itself always available during the upgrade process. We can set back the alert threshold to its default value 85%.

AggregatedAPIDown alert threshold set back to 85%

---

pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

This PR provides a way to the user to set alertmanager logLevel as described in the [openshift doc](https://docs.openshift.com/container-platform/4.7/monitoring/configuring-the-monitoring-stack.html#setting-log-levels-for-monitoring-components_configuring-the-monitoring-stack).

Allow configuration of the log level for Alertmanager in the CMO configmap

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

Bug 1974830: Update KubeDeploymentReplicasMismatch alert

---

.github/ISSUE_TEMPLATE/release.md
Makefile
assets/alertmanager/alertmanager.yaml
assets/kube-state-metrics/deployment.yaml
assets/node-exporter/daemonset.yaml
assets/openshift-state-metrics/deployment.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/telemeter-client/deployment.yaml
assets/thanos-querier/deployment.yaml
hack/generate-versions.sh
jsonnet/alertmanager.libsonnet
jsonnet/main.jsonnet
jsonnet/openshift-state-metrics.libsonnet
jsonnet/prometheus-user-workload.libsonnet
jsonnet/prometheus.libsonnet
jsonnet/telemeter-client.libsonnet
jsonnet/thanos-querier.libsonnet
jsonnet/versions.json

During a release process, we need to pin version numbers of operands to ensure correct metadata is assigned to k8s objects managed by CMO. To improve this process and make it error-prone I created a simple bash script to poll every downstream fork for `VERSION` file and use the content of those files to create a simple JSON map put into `versions.json`. This JSON file is then imported into the jsonnet codebase and used to generate correct metadata.
Since the `versions.json` file can be treated as a source of truth (to some degree) it should improve our ability to discover which operand version is shipped with which OpenShift release. Additionally, in the future, it opens an easy path to use the file in some sort of documentation generator. 
Waiting for …

*: improve discovery of currently used component versions

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

When the Prometheus pods are redeployed and persistent storage is used,
the recording rules used to report telemetry about monitoring would
double count for 5 minutes (at most). It happens because of how
Prometheus handles staleness: the individual metrics would be present
for both the old and new pods if their `instance` labels have changed
(e.g. their IP addresses are different). To avoid this artifact, the
rules aggregate away the `instance` label.
Original `openshift:prometheus_tsdb_head_series:sum` recording rule
The modified query on the same dataset

Improve monitoring telemetry rules

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

Reverts openshift/cluster-monitoring-operator#1253
Seems to have broken again:
```console
$ w3m -dump -cols 200 'https://search.ci.openshift.org/?search=alert+KubeDeploymentReplicasMismatch+fired&maxAge=336h&type=junit' | grep -o '[0-9]* days ago' | sort -n | uniq -c
2 3 days ago
171 4 days ago
211 5 days ago
185 6 days ago
25 7 days ago
1 9 days ago
4 11 days ago
2 12 days ago
4 13 days ago
```
shows us recovering after the previous alert.  And:
```console
$ w3m -dump -cols 200 'https://search.ci.openshift.org/?search=alert+KubeDeploymentReplicasMismatch+fired&maxAge=336h&type=junit' | grep -o '[0-9]* hours ago' | wc -l
264
```
shows us breaking again after #1253 landed.

Revert "Bug 1974830: Update KubeDeploymentReplicasMismatch alert"

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/cluster-monitoring-operator.libsonnet
jsonnet/main.jsonnet
jsonnet/remove-runbook-urls.libsonnet
jsonnet/rules.libsonnet

Add an alert to detect if two instances of a highly available component are
running on the same node and have persistent volumes attached. Since we
can't fix this issue ourselves, we alert administrators that they will
need to take action for the cluster to really be highly available.
Since the actions to be taken are complex, a dedicated runbook will be
appended to the alert to help administrators mitigate this issue.
cc @jan--f @wking @smarterclayton @ravisantoshgudimetla

Bug 1974832: Add HighlyAvailableWorkloadIncorrectlySpread alert

---

assets/node-exporter/daemonset.yaml
jsonnet/node-exporter.libsonnet

The node_exporter cpufreq collector seems to be causing high load on
some machines with lots of cores.  This disables it temporarily as a
workaround until the issue can be addressed upstream.  We don't seem
to rely on these metrics anywhere.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1972076

Bug 1972076: jsonnet: Disable cpufreq collector in node_exporter

---

assets/prometheus-operator-user-workload/cluster-role-binding.yaml
assets/prometheus-operator-user-workload/cluster-role.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator-user-workload/service-account.yaml
assets/prometheus-operator-user-workload/service-monitor.yaml
assets/prometheus-operator-user-workload/service.yaml
assets/prometheus-operator/cluster-role-binding.yaml
assets/prometheus-operator/cluster-role.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-operator/prometheus-rule.yaml
assets/prometheus-operator/service-account.yaml
assets/prometheus-operator/service-monitor.yaml
assets/prometheus-operator/service.yaml
jsonnet/versions.json

Follow-up PR to https://github.com/openshift/prometheus-operator/pull/131

Bug 1977435: jsonnet: bump prometheus-operator to v0.49.0

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
assets/control-plane/prometheus-rule.yaml
jsonnet/main.jsonnet
jsonnet/rules.libsonnet

Logging metrics have been moved from the logging namespace to
openshift-logging, so we can now remove logging from the namespace
selector used by all the mixins.

Remove logging from the mixins namespace selectors

---

pkg/operator/operator.go
pkg/tasks/tasks.go

This PR adds Three commits, that aim to improve our reconcile loop:
1. Update `prometheus-operator` first and wait for it to finish before updating the other operands concurrently.
2. Allow the reconcile loop three attempts before calling `SetFailed` and thus reporting `available=false`.
3. Back-off more aggressively in case of failures. The `DefaultControllerRateLimiter`s default back-off is a bit slow and it also adds per bucket back-off tracking, which we don't use due to only ever queuing one event. Instead this introduces an instance of `ItemExponentialFailureRateLimiter`, which is also used by `DefaultControllerRateLimiter`, but with more aggressive rate limiting settings.

Bug 1949840: Improve update and status reporting

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet
test/rules/workload_incorrectly_spread.yaml

Improve HighlyAvailableWorkloadIncorrectlySpread alert to only fire when
all instances of a workload are on the same node. Ultimately what we
want to catch with this alert are single points of failures and even if
multiple instances end up on the same node, if one of them is correctly
spread, then the workload is highly available.

Bug 1974832: Improve HighlyAvailableWorkloadIncorrectlySpread to detect single point of failure

---

assets/thanos-querier/deployment.yaml
jsonnet/thanos-querier.libsonnet
pkg/manifests/manifests.go

This adds the argument to thanos-querier to enable the new federated
targets functionality.  When user workload monitoring is enabled,
targets will be fetched from that Prometheus instance as well as from
the platform Prometheus.

jsonnet: Enable federated targets in thanos-querier

---

pkg/client/status_reporter.go

We always set the OperatorUpgradeable status condition on the
ClusterOperator resource to True, but we sometimes change the message
to indiciate errors.  This has proved confusing for users because the
errors are also indicated in the other status condition messages and
the Upgradeable condition has not actually changed values.  This
always sets the Upgradeable condition to true with an "AsExpcted"
reason.

client: Always set OperatorUpgradeable reason to AsExpected

---

pkg/client/client.go
vendor/k8s.io/client-go/util/retry/util.go
vendor/modules.txt

**Why this change?**
The operator goes Degraded and Unavailable for a short period of time, the reason being '... Deployment failed: creating Deployment object failed after update failed: object is being deleted: deployments.apps "xxx" already exists'. Trying to fix conflict in updating deployment with this change.

Bug 1956308: Fix deployment update with retry option

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
test/e2e/user_workload_monitoring_test.go

This adds support for configuring the EnforcedTargetLimit for the
user-workload Prometheus instance.  This lets admins set an overall
limit on the number of targets scraped.

pkg/manifests: Add EnforcedTargetLimit for user-workload monitoring

---

cmd/operator/main.go
pkg/client/client.go
pkg/client/client_test.go
pkg/client/status_reporter.go
pkg/client/status_reporter_test.go
pkg/operator/operator.go
pkg/tasks/prometheusadapter.go
test/e2e/framework/framework.go

As in title [MON-1251](https://issues.redhat.com/browse/MON-1251)
This is second PR after https://github.com/openshift/cluster-monitoring-operator/pull/1240 to remove context.TODO() calls

Remove context.TODO() and propagate real context

---

assets/thanos-querier/deployment.yaml
jsonnet/thanos-querier.libsonnet

The exec probe is timing out intermittently. This coud be caused in part
by the timing on the probe not being sufficient, or there may be an underlying
issue with the (exec, cri-o) combo.
This change takes the config for httpGet probes from upstream thanos and proxies
to thanos via the oauth-gateway where we bypass the health check endpoints.
The HTTP probe cannot directly ping thanos since it listens on localhost
and is unreachable from kubelet. This is by design.
I have not increased the timeout here because if there is an issue with query after setting the rest of the config to match what is upstream, I would prefer to observe that as an issue and report it upstream to find out when/why it might occur. We will of course, see some additional latency by going through the proxy but I …

BUG 1980888: jsonnet: Favour http probes for thanos querier

---

hack/generate-versions.sh

Running `make format` throws the following error:
```
./hack/generate-versions.sh:28:3: note: See if you can use ${variable//search/replace} instead. [SC2001]
make: *** [Makefile:144: shellcheck] Error 1
```
The expression which causes the error is https://github.com/openshift/cluster-monitoring-operator/blob/master/hack/generate-versions.sh#L28
This commit replaces the expression with the one recommended by shellcheck[1] in order to make the `format` target work again.
[1] https://github.com/koalaman/shellcheck/wiki/SC2001

Fix shellcheck errors

---

CHANGELOG.md
pkg/client/status_reporter.go
pkg/client/status_reporter_test.go
pkg/manifests/config.go
pkg/operator/operator.go

When persistent storage is not configured for prometheus, upgrades and cluster disruptions can lead to data loss. 
In order to make cluster admins aware of this problem, this PR adds a message to the degraded condition indicating this problem. The value of the condition is kept as `degraded=false` since there is no real degradation with the cluster monitoring.

Bug 1978662: Set a degraded message when persistent storage is not configured

---

CHANGELOG.md
assets/control-plane/prometheus-rule.yaml
assets/control-plane/service-monitor-kubelet.yaml
assets/grafana/dashboard-definitions.yaml
jsonnet/jsonnetfile.lock.json
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

This pulls in https://github.com/prometheus-operator/kube-prometheus/pull/1250 and in doing so drops high cardinality and non required metrics that are scrapped from cAdvisor.
Testing on a nightly cluster this decreases the metric count for cAdvisor by ~12k

jsonnet: Sync with kube-prometheus

---

jsonnet/grafana.libsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Fixes https://issues.redhat.com/browse/ODC-6066
I added a list of dashboard we want show in developer console (OCP) and a new label (`"console.openshift.io/odc-dashboard": "true")` if the Grafana dashboard is part of that list.
(At least no facing changes without the additional changes we will do in developer console.

Add new label to show grafana dashboards in ODC

---

Documentation/cluster-monitoring.md

s/monitoring the Cluster cluster itself/monitoring the cluster itself

Documentation: fix a typo

---

CHANGELOG.md
pkg/manifests/amcfg.go
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/prometheus.go
pkg/tasks/prometheus_user_workload.go
pkg/tasks/thanos_ruler_user_workload.go
test/e2e/framework/framework.go
test/e2e/thanos_ruler_test.go
test/e2e/user_workload_monitoring_test.go
vendor/k8s.io/client-go/tools/portforward/doc.go
vendor/k8s.io/client-go/tools/portforward/portforward.go
vendor/modules.txt

This commit is a follow up on the work done in https://github.com/openshift/cluster-monitoring-operator/pull/1132 and allows users to configure additional Alertmanagers for the Prometheus instance and the Thanos Ruler in User Workload Monitoring.

Allow configuring additional alertmanagers for UWM Prometheus and Thanos

---

assets/control-plane/service-monitor-kubelet.yaml
jsonnet/control-plane.libsonnet

The metrics have been dropped manually because we were not able to
configure them. Now https://github.com/cri-o/cri-o/pull/5061 has been
merged and the list of enabled metrics will be handled in the Machine
Config Operator.
No user facing change required if merged together with https://github.com/openshift/machine-config-operator/pull/2678

Remove manual CRI-O metrics modification

---

assets/grafana/dashboard-definitions.yaml
assets/node-exporter/prometheus-rule.yaml
jsonnet/main.jsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

https://github.com/openshift/cluster-monitoring-operator/pull/1214 introduced a change in the node_exporter recording rules that breaks the console. And since node_exporter metrics are scraped every 15 seconds, a time range of 1m is a correct choice.

Bug 1978091: fix node_exporter recording rules for cluster network dashboards

---

assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/thanos-querier/cluster-role-binding.yaml
assets/thanos-querier/cluster-role.yaml
assets/thanos-querier/deployment.yaml
assets/thanos-querier/grpc-tls-secret.yaml
assets/thanos-querier/kube-rbac-proxy-rules-secret.yaml
assets/thanos-querier/kube-rbac-proxy-secret.yaml
assets/thanos-querier/oauth-cookie-secret.yaml
assets/thanos-querier/oauth-htpasswd-secret.yaml
assets/thanos-querier/pod-disruption-budget.yaml
assets/thanos-querier/prometheus-rule.yaml
assets/thanos-querier/route.yaml
assets/thanos-querier/service-account.yaml
assets/thanos-querier/service-monitor.yaml
assets/thanos-querier/service.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/versions.json

Downstream thanos bump PR: https://github.com/openshift/thanos/pull/63

Bug 1973576: Bump thanos to v0.22.0

---

pkg/client/client.go

Bug 1986375: adding check for node exporter daemon set

---

assets/node-exporter/daemonset.yaml
jsonnet/node-exporter.jsonnet

Cherry-pick https://github.com/openshift/cluster-monitoring-operator/pull/1272

[release-4.7] Bug 1986591: node exporter calls /proc/cpuinfo multiple times causing the node to freeze

---

assets/prometheus-k8s/prometheus-rule.yaml
jsonnet/patch-rules.libsonnet

This is a back port of https://github.com/thanos-io/thanos/pull/4342. Originally got into 4.9 as part of https://github.com/openshift/cluster-monitoring-operator/pull/1244/files#diff-9f32475601d9c279cd63600ea04308adf63ac5809e2b483526ae4105e8c3670cL289

Bug 1943565: ThanosSidecarUnhealthy will never fire if the sidecar is never healthy

---

assets/prometheus-k8s/cluster-role-binding.yaml
assets/prometheus-k8s/cluster-role.yaml
assets/prometheus-k8s/prometheus-rule.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-k8s/role-binding-config.yaml
assets/prometheus-k8s/role-binding-specific-namespaces.yaml
assets/prometheus-k8s/role-config.yaml
assets/prometheus-k8s/role-specific-namespaces.yaml
assets/prometheus-k8s/service-account.yaml
assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
assets/prometheus-k8s/service-monitor.yaml
assets/prometheus-k8s/service-thanos-sidecar.yaml
assets/prometheus-k8s/service.yaml
assets/prometheus-user-workload/cluster-role-binding.yaml
assets/prometheus-user-workload/cluster-role.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/prometheus-user-workload/role-binding-config.yaml
assets/prometheus-user-workload/role-binding-specific-namespaces.yaml
assets/prometheus-user-workload/role-config.yaml
assets/prometheus-user-workload/role-specific-namespaces.yaml
assets/prometheus-user-workload/service-account.yaml
assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
assets/prometheus-user-workload/service-monitor.yaml
assets/prometheus-user-workload/service-thanos-sidecar.yaml
assets/prometheus-user-workload/service.yaml
jsonnet/versions.json

This is a follow-up PR to update prometheus resource label after https://github.com/openshift/prometheus/pull/89.

Bug 1987143: Update prometheus resources label to 2.28.1

---

pkg/client/client.go

Allow retry for daemon set creation as commented in https://github.com/openshift/cluster-monitoring-operator/pull/1257/#pullrequestreview-700719930
cc: @dgrisonnet @simonpasquier

Bug 1988291: pkg/client/client.go: Add retry logic for daemonset create

---

pkg/client/client.go

Allow retry for daemonset creation.
Backport of https://github.com/openshift/cluster-monitoring-operator/pull/1307
cc:  @simonpasquier @dgrisonnet

Bug 1988991: pkg/client/client.go: Add retry logic for daemonset create

---

Makefile

Noticed during https://github.com/openshift/release/pull/20887 development. Without this, on clean repository `make versions` fails as it cannot install `gojsontoyaml` dependency due to incorrectly named make targets.
Additionally, I added a note of deprecating `generate-in-docker` as it is no longer needed after we switched to use jsonnet and not python script.
`$(GOBINDATA_BIN)` wasn't used for a long time (I think around 4.6 we did a switch).

Bug 1990258: cleaning up Makefile

---

assets/alertmanager/prometheus-rule.yaml
jsonnet/patch-rules.libsonnet

Fixing this by patching in CMO since this doesn't look to be ideal candidate for backporting in upstream alertmanager repo
Upstream fix in master https://github.com/prometheus/alertmanager/pull/2613

Bug 1976765:Update AlertmanagerMembersInconsistent rule

---

CHANGELOG.md
pkg/client/client.go
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
pkg/tasks/alertmanager.go
pkg/tasks/clustermonitoringoperator.go
pkg/tasks/configsharing.go
pkg/tasks/prometheus.go
pkg/tasks/prometheusoperator_user_workload.go
pkg/tasks/thanos_ruler_user_workload.go
test/e2e/alertmanager_test.go
test/e2e/framework/assertions.go
test/e2e/framework/framework.go

The ACM would like to funnel all alerts from a fleet of OpenShift
clusters through a single external Alertmanager. As a result, they
would like to trim down the monitoring stack and disable the local
alertmanager.
This commit exposes a binary field in the cluster-monitoring-configmap
which allows users to fully disable the built-in alertmanager.

MON-1749: Allow users to disable the local Alertmanager

---

assets/thanos-querier/deployment.yaml
jsonnet/thanos-querier.libsonnet

This is cherry pick of #1277 which backports to 4.8.z

Bug 1982778: jsonnet: thanosquery: Use HTTP probes as opposed to exec

---

CHANGELOG.md
assets/alertmanager/prometheus-rule.yaml
assets/control-plane/prometheus-rule.yaml
assets/kube-state-metrics/prometheus-rule.yaml
assets/node-exporter/prometheus-rule.yaml
assets/prometheus-k8s/prometheus-rule.yaml
assets/thanos-querier/prometheus-rule.yaml
assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
jsonnet/patch-rules.libsonnet

Ready to review and merge :D
[Bugzilla #1986981](https://bugzilla.redhat.com/show_bug.cgi?id=1986981)
After reviewing critical alerts in OCP, we find out the 21 alerts that need adjustments:
(✅ for already modified alerts, 🛠 for work in progress)
Recommend changing Critical to Warning: 13
- KubePersistentVolumeErrors✅
- PrometheusBadConfig✅
- PrometheusRemoteStorageFailures✅
- PrometheusRuleFailures✅
- AlertmanagerMembersInconsistent✅
- AlertmanagerClusterFailedToSendAlerts✅
- AlertmanagerConfigInconsistent✅
- AlertmanagerClusterDown✅
- KubeStateMetricsListErrors✅
- KubeStateMetricsWatchErrors✅
- ThanosRuleSenderIsFailingAlerts✅
- ThanosRuleHighRuleEvaluationFailures✅
- ThanosNoRuleEvaluations✅
Recommend removing alert: 2
- PrometheusErrorSendingAlertsToAnyAlertmanager✅
- …

Bug 1986981: Update Alert Configs

---

pkg/client/status_reporter.go
pkg/operator/operator.go
pkg/tasks/tasks.go

Currently when there are task failures , the operator reports only one of the task failures even if there are multiple tasks failing. This PR will log and report all task failures.

MON-1099 Improving error reporting to show all task failures

---

pkg/tasks/nodeexporter.go

Bug 1993055: Fix node_exporter task error message

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

This changes makes us compliant with https://github.com/openshift/enhancements/blob/01422f157a206463c5581362aec69c401bc67ae5/enhancements/monitoring/alerting-consistency.md#documentation-required

Bug 1992493: jsonnet:rules: Adds missing summary and description to rules.

---

assets/prometheus-adapter/api-service.yaml
assets/prometheus-adapter/cluster-role-aggregated-metrics-reader.yaml
assets/prometheus-adapter/cluster-role-binding-delegator.yaml
assets/prometheus-adapter/cluster-role-binding.yaml
assets/prometheus-adapter/cluster-role-server-resources.yaml
assets/prometheus-adapter/cluster-role.yaml
assets/prometheus-adapter/config-map.yaml
assets/prometheus-adapter/deployment.yaml
assets/prometheus-adapter/pod-disruption-budget.yaml
assets/prometheus-adapter/role-binding-auth-reader.yaml
assets/prometheus-adapter/service-account.yaml
assets/prometheus-adapter/service-monitor.yaml
assets/prometheus-adapter/service.yaml
jsonnet/versions.yaml

Updating manually to block the Bugzillas fixed by the new version from moving ON_QA without the labels being updated.

Bug 1956830: Update prometheus-adapter to v0.9.0

---

CHANGELOG.md
assets/grafana/dashboard-definitions.yaml
jsonnet/jsonnetfile.lock.json
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

EDIT: reduced scope of this PR to only include issues related to the bug.

Bug 1984365: Dashboard Prometheus/Overview can't filter instance by job

---

assets/control-plane/prometheus-rule.yaml
assets/node-exporter/prometheus-rule.yaml
assets/prometheus-k8s/prometheus-rule.yaml
assets/thanos-querier/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

This PR includes 2 amendments to PR#1310:
1. This PR patches Thanos-related alerts to warning severity and triggering time window to 1h. In PR#1310 I have introduced a bug in the patching function that does not take empty alert/record name as an all-matching wildcard. 😅
2. remove patch for "expr" field in rules KubePersistentVolumeFillingUp, NodeFilesystemFilesFillingUp, and NodeFilesystemSpaceFillingUp, leaving it to upstream

Bug 1986981: Alert Config update - Patch to PR#1310

---

CHANGELOG.md
assets/prometheus-user-workload/prometheus.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/main.jsonnet
test/e2e/framework/client.go
test/e2e/user_workload_monitoring_test.go
test/e2e/utils.go

This adds support for setting an `openshift.io/user-monitoring` label
on namespaces to exclude them from user-workload monitoring.  This is
in addition to the exclusion of namespaces that have set a `true`
value for the `openshift.io/cluster-monitoring` label.

jsonnet: Support exluding namespaces from user-workload monitoring

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
assets/control-plane/prometheus-rule.yaml
assets/thanos-querier/prometheus-rule.yaml
jsonnet/components/thanos-querier.libsonnet
jsonnet/rules.libsonnet
jsonnet/utils/sanitize-rules.libsonnet

All OpenShift alerts should include a namespace label for routing.
We've queried Telemeter data and identified several shipped by CMO
that don't include a namespace.  This adds the labels to these by
either adjusting the expressions in the rules, or simply adding static
labels were appropriate.
See: https://issues.redhat.com/browse/MON-939

jsonnet: Add missing namespace labels to alerting rules

---

assets/thanos-querier/deployment.yaml
jsonnet/components/thanos-querier.libsonnet
manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml

Fix "beta.kubernetes.io/os" is deprecated since v1.14
Other upstream changes I made are pulled in https://github.com/openshift/cluster-monitoring-operator/pull/1340/files but kube-thanos couldn't since its not available in [0.22 release](https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/jsonnetfile.json#L58) hence patching it in jsonnet here
cc: @simonpasquier

Bug 1995614: Fix beta.kubernetes.io/os deprecated warning

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
assets/control-plane/prometheus-rule.yaml
hack/check-rec-rule-usage.sh
jsonnet/rules.libsonnet
jsonnet/utils/sanitize-rules.libsonnet

The recording rules that are not unused in alerts, telemetry metrics, console, or dashboard definitions are removed.
The following rules are removed:
- build_error_rate
- cluster_quantile:apiserver_request_duration_seconds:histogram_quantile
- code:registry_api_request_count:rate:sum
- instance:node_cpu:ratio
- kube_pod_status_ready:etcd:sum
- kube_pod_status_ready:image_registry:sum
- namespace:container_spec_cpu_shares:sum
- node:node_num_cpu:sum
- pod:container_spec_cpu_shares:sum

Bug 1996785: [MON-1536]Remove unused rules.

---

assets/alertmanager/prometheus-rule.yaml
assets/cluster-monitoring-operator/prometheus-rule.yaml
assets/control-plane/prometheus-rule.yaml
assets/node-exporter/prometheus-rule.yaml
assets/prometheus-k8s/prometheus-rule.yaml
assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet
test/rules/bz1974830.yaml

All critical alerts in OpenShift should have an associated runbook. We've recently added basic runbooks for all critical alerts shipped by CMO: https://github.com/openshift/runbooks/pull/16 -- This adds links to these in the `runbook_url` annotation.

Bug 2000490: Add runbooks for all critical alerts

---

test/e2e/framework/framework.go
test/e2e/prometheus_test.go
test/e2e/utils.go

This only adds a test for an unencrypted enpoint. An mTLS test will follow in a separate PR, but use the same test function.

test/e2e: add remote_write http e2e test

---

assets/control-plane/prometheus-rule.yaml
assets/grafana/config.yaml
assets/grafana/dashboard-datasources.yaml
assets/grafana/dashboard-sources.yaml
assets/grafana/deployment.yaml
assets/node-exporter/prometheus-rule.yaml
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
pkg/manifests/manifests.go

The goal of this PR is to pick changes related to https://github.com/prometheus-operator/kube-prometheus/pull/1357.  It also updates jsonnet dep version to master as we are on 4.10 track.

Bug 1987263: fsSpaceFillingUpWarningThreshold not aligned to Kubernetes Garbage Collection Threshold

---

assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/prometheus.yaml
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet

Bug 1997028: drop [$(POD_IP)] from --grpc-address argument for thanos sidecar

---

go.mod
test/e2e/config_test.go
test/e2e/framework/assertions.go
test/e2e/framework/helpers.go
test/e2e/user_workload_monitoring_test.go
test/e2e/uwm_helpers.go
vendor/modules.txt

See [#MON-1170](https://issues.redhat.com/browse/MON-1170) for context on change.
This change splits the growing UWM e2e table driven tests into their own individual tests. The downside to this is there is a lot of setup/teardown to UWM so it is going to take longer to run.
I have deleted some tests since they were already covered by the config tests for uwm. I have moved a test into the config test suite where it is more appropriate and have extracted common functions used across the suite into their own file.

test:e2e: Split UWM tests and cleanup duplicated tests across e2e config

---

assets/kube-state-metrics/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

We don't configure sharding for kube-state-metrics, so there's no
reason to ship the critical alerts for them, or maintain runbooks for
them, etc. This drops the two critical alerts related to sharding.

Bug 2000490: jsonnet: Drop unnecessary kube-state-metrics alerts

---

assets/kube-state-metrics/deployment.yaml
assets/kube-state-metrics/kube-rbac-proxy-secret.yaml
jsonnet/components/kube-state-metrics.libsonnet
jsonnet/utils/generate-secret.libsonnet
pkg/manifests/manifests.go
pkg/tasks/kubestatemetrics.go

MON-1679: adding static auth to KSM

---

assets/prometheus-operator/prometheus-rule.yaml
jsonnet/main.jsonnet

Bug 2001566: enabling alerts for prometheus operator in uwm

---

.github/ISSUE_TEMPLATE/release.md

The old links work fine (forwarded) but might as well fix it to reduce confusion.
This can wait.

issue template kube-prometheus location: coreos -> prometheus-operator

---

.gitignore

Duriing one of the many rebases of https://github.com/openshift/cluster-monitoring-operator/pull/1280 I seem to have accidentally committed an empty stray file

Remove extraneous file commited during rebase

---

assets/openshift-state-metrics/deployment.yaml
assets/openshift-state-metrics/kube-rbac-proxy-secret.yaml
jsonnet/components/openshift-state-metrics.libsonnet
pkg/manifests/manifests.go
pkg/tasks/openshiftstatemetrics.go

static auth changes for osm

---

pkg/client/client.go

Bug 1989438: changing error message to indicate deployment status

---

assets/node-exporter/daemonset.yaml
assets/node-exporter/kube-rbac-proxy-secret.yaml
jsonnet/components/node-exporter.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/nodeexporter.go

static auth changes for node-exporter

---

assets/control-plane/service-monitor-kubelet.yaml
jsonnet/jsonnetfile.lock.json

This is a backport of https://github.com/openshift/cluster-monitoring-operator/pull/1291 which pulls in https://github.com/prometheus-operator/kube-prometheus/pull/1353

Bug 1999057: jsonnet: Sync with kube-prometheus

---

pkg/client/client.go

Bug 2004051: changing the condition for error in daemon set creation

---

assets/control-plane/service-monitor-kubelet.yaml
jsonnet/jsonnetfile.lock.json

Pulls in changes from https://github.com/prometheus-operator/kube-prometheus/pull/1396

Bug 2007677: Reinstate dropped metrics

---

CHANGELOG.md
assets/thanos-querier/deployment.yaml
jsonnet/components/thanos-querier.libsonnet
test/e2e/framework/client.go
test/e2e/user_workload_monitoring_test.go

Expose /api/v1/labels end point for Thanos query.
End point for /api/v1/label/<name>/values is added but not working yet, need to update kube-rbac-proxy to support at least trailing wildcard patterns. 
This PR requires the 2 PRs below done before merge, and they are merged now:
1. [This PR](https://github.com/brancz/kube-rbac-proxy/pull/135) is merged for allowing trailing wildcard in kube-rbac-proxy  --allow-paths .
2. [This PR](https://github.com/openshift/kube-rbac-proxy/pull/50) is merged for version bump to 0.11.

[MON-1695] expose /api/v1/labels end point for Thanos query.

---

CHANGELOG.md
assets/control-plane/service-monitor-kubelet.yaml
jsonnet/components/control-plane.libsonnet
jsonnet/jsonnetfile.lock.json

This change drops pod-centric metrics that have a non empty `container` label.  For context it is best to look at the detailed discussion on https://github.com/prometheus-operator/kube-prometheus/pull/1402 and the issues it links to

Bug 2007677: Adjust dropped cAdvisor metrics

---

jsonnet/components/cluster-monitoring-operator.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/client/client.go
pkg/manifests/apiserver_config.go
pkg/manifests/apiserver_config_test.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
pkg/tasks/prometheusoperator.go
pkg/tasks/prometheusoperator_user_workload.go
test/e2e/framework/framework.go
test/e2e/tls_security_profile_test.go

OpenShift exposes a cluster-scoped resource called APIServer which
admins can use to configure TLS security settings for all openshift
components. Admins can choose from three predefined profiles, old,
intermediate and modern, or define custom TLS settings themselves.
This commit implements logic in CMO to apply the TLS settings defined in
the APIServer resource to the PM and UWM prometheus-operator.

Configure prometheus operator TLS based on the cluster APIServer config

---

CONTRIBUTING.md
Documentation/development.md

Explains:
*  how to run CMO locally
*  Update jsonnet bundles

docs: new development doc for new comers

---

manifests/0000_50_cluster-monitoring-operator_01-namespace.yaml

Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-monitoring` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz

podsecurity: enforce privileged for openshift-monitoring namespace

---

assets/telemeter-client/deployment.yaml
assets/telemeter-client/kube-rbac-proxy-secret.yaml
jsonnet/components/telemeter-client.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/telemeter.go

static auth changes for telemeter client

---

assets/control-plane/service-monitor-kubelet.yaml
jsonnet/jsonnetfile.lock.json

Reverts openshift/cluster-monitoring-operator#1360

Revert "Bug 1999057: jsonnet: Sync with kube-prometheus"

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet
test/rules/bz2006561.yaml

This PR fixes the [bug 2006561](https://bugzilla.redhat.com/show_bug.cgi?id=2006561), caused by rule evaluation of "HighlyAvailableWorkloadIncorrectlySpread".

Bug 2006561:  Prometheus when installed on the cluster shouldn't have failing rules evaluation

---

assets/kube-state-metrics/deployment.yaml
jsonnet/components/kube-state-metrics.libsonnet

Customer need this label for custom alerting which was available in previous OCP versions which went away with KSM v2 update. Adding it back by allowing in metric label allow list

Bug 2011698: Allow namespace label in metric allow list

---

assets/prometheus-user-workload/cluster-role.yaml
assets/prometheus-user-workload/kube-rbac-proxy-secret.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
assets/prometheus-user-workload/service-monitor.yaml
jsonnet/components/prometheus-user-workload.libsonnet
pkg/manifests/manifests.go
pkg/manifests/tls.go
pkg/operator/operator.go
pkg/tasks/metrics_client_ca.go
pkg/tasks/prometheus_user_workload.go

The UWM Prometheus kube-rbac-proxy currently works with subject access
reviews to verify whether the caller is allowed to access Prometheus endpoints.
This commit changes the authentication method to a static one based on
the CN in the certificate of the caller.

Change kube-rbac-proxy authentication for UWM Prometheus

---

pkg/manifests/manifests.go
pkg/tasks/controlplane.go
pkg/tasks/prometheus.go
pkg/tasks/prometheus_user_workload.go

This change removes code that was needed to delete service monitors and
Prometheus rules that don't exist anymore in 4.10.

pkg: remove dead code

---

assets/alertmanager/alertmanager.yaml
assets/thanos-querier/deployment.yaml
jsonnet/components/alertmanager.libsonnet
jsonnet/components/thanos-querier.libsonnet
jsonnet/versions.yaml
test/e2e/framework/client.go
test/e2e/user_workload_monitoring_test.go

This commit enables the new prom-label-proxy flag in order to return an
error in case a label would have been silently replaced. Before the user
would simply see a result that would not respond to the query. Returning
an error follows the principle of least surprise.

Bug 1808240: prom-label-proxy: set --error-on-replace

---

assets/control-plane/service-monitor-kubelet.yaml
jsonnet/components/control-plane.libsonnet

Bug 2018455: Keep container_fs_usage_bytes metric

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/kubestatemetrics.go
test/e2e/tls_security_profile_test.go

This PR only covers kube-rbac-proxy in KSM since we wanted to break it down the changes in smaller chunks
This PR implements TLS security profile for kube-rbac-proxy in kube-state-metrics
[MON-1651](https://issues.redhat.com/browse/MON-1651)

pkg: add tlsSecurityProfile to kube-rbac-proxy in KSM

---

CHANGELOG.md
assets/kube-state-metrics/deployment.yaml
jsonnet/components/kube-state-metrics.libsonnet

Bug 2015386: jsonnet: Add PodDisruptionBudget to KSM metric allow list

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/tls_security_profile_test.go

This PR only covers kube-rbac-proxy in OSM since we wanted to break it down the changes in smaller chunks
test: Add tests for osm-rbacproxy tlssecurityprofile
This commit implements TLS security profile for kube-rbac-proxy in openshift-state-metrics
[MON-1651](https://issues.redhat.com/browse/MON-1651)

pkg: add tlsSecurityProfile to kube-rbac-proxy in OSM

---

hack/local-cmo.sh

The existing local dev flow makes uses of `-images` flag from existing deployment. However retrieval of `-images` flag produces erroneous argument when I apply local manifests for testing(see below). This commit hardens the retrieval process by using jq.
```
$ kc get deployment cluster-monitoring-operator -o yaml | grep -o '\-images.*'
-images=prometheus-operator=quay.io/openshift/origin-prometheus-operator:latest","-images=prometheus-config-reloader=quay.io/openshift/origin-prometheus-config-reloader:latest","-images=configmap-reloader=quay.io/openshift/origin-configmap-reloader:latest","-images=prometheus=quay.io/openshift/origin-prometheus:latest","-images=alertmanager=quay.io/openshift/origin-prometheus-alertmanager:latest","-images=grafana=quay.io/openshift/origin-grafana:latest","-im …
```

run-local: harden -images switch retrieval

---

assets/kube-state-metrics/deployment.yaml
jsonnet/kube-state-metrics.libsonnet

Signed-off-by: Michael Skarbek <mskarbek@redhat.com>
- Cherry pick https://github.com/openshift/cluster-monitoring-operator/pull/1457
- node => nodes in allow label list argument, change is meant for consistency, shouldn't really affect functionality!

Bug 2018431: [4.8] add kube_persistentvolumeclaim_labels and kube_persistentvolume_labels

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

This PR covers tls security profile for kube-rbac-proxy in prometheus-operator in platform and uwm
[MON-1651](https://issues.redhat.com/browse/MON-1651)

pkg: add tlsSecurityProfile to kube-rbac-proxy in prometheus-operator

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/tls_security_profile_test.go

This PR covers tls security profile for kube-rbac-proxy in node-exporter
[MON-2022](https://issues.redhat.com/browse/MON-2022)

pkg: add tlsSecurityProfile to kube-rbac-proxy in node-exporter

---

assets/alertmanager/alertmanager.yaml
assets/alertmanager/service-monitor.yaml
assets/control-plane/prometheus-rule.yaml
assets/control-plane/service-monitor-kubelet.yaml
assets/grafana/dashboard-definitions.yaml
assets/grafana/deployment.yaml
assets/grafana/service-account.yaml
assets/node-exporter/cluster-role-binding.yaml
assets/node-exporter/cluster-role.yaml
assets/node-exporter/daemonset.yaml
assets/node-exporter/prometheus-rule.yaml
assets/prometheus-adapter/cluster-role-aggregated-metrics-reader.yaml
assets/prometheus-adapter/cluster-role-binding-delegator.yaml
assets/prometheus-adapter/cluster-role-binding.yaml
assets/prometheus-adapter/cluster-role-server-resources.yaml
assets/prometheus-adapter/cluster-role.yaml
assets/prometheus-k8s/cluster-role-binding.yaml
assets/prometheus-k8s/cluster-role.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/cluster-role-binding.yaml
assets/prometheus-user-workload/cluster-role.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/telemeter-client/serving-certs-ca-bundle.yaml
jsonnet/jsonnetfile.lock.json
jsonnet/utils/sanitize-rules.libsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
pkg/manifests/manifests.go
pkg/tasks/alertmanager.go
test/e2e/alertmanager_test.go

This PR bumps jsonnet dependencies to latest which also fixes Bug 2013920 and Bug 2019992.
Removal of kube-proxy alerts shall be found in https://github.com/openshift/cluster-monitoring-operator/pull/1444/files#r732821044
Alertmanager SM has been renamed from alertmanager to alertmanager-main.

Bug 2019992: Bump jsonnet dependencies to latest

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/tls_security_profile_test.go

This PR implements tls security profile for remaining components (except cmo) using kube-rbac-proxy per suggestion in last PR #1470. Each component is implemented in separate commit.
cc: @fpetkovski @simonpasquier @juzhao 
[MON-1651](https://issues.redhat.com/browse/MON-1651)

pkg: Implements tlsSecurityProfile to remaining components using kube-rbac-proxy

---

CHANGELOG.md
assets/alertmanager/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

Bug 2016435: Removing one of the AlertmanagerClusterFailedToSendAlerts alerts

---

test/e2e/user_workload_monitoring_test.go

Prometheus Operator version 0.52 has a new feature to append a postfix to the rule file name to avoid name collision. This breaks the E2E test [TestUserWorkloadMonitoringAlerting ](https://github.com/openshift/cluster-monitoring-operator/blob/4ecf1715bf3f572edb1c424cf3185f37719521fe/test/e2e/user_workload_monitoring_test.go#L733)which assumes rule file without this postfix.
This PR update that test so it can pass after upgrading Prometheus Operator to version 0.52.
rule file name before 0.52: ` /etc/prometheus/rules/prometheus-user-workload-rulefiles-0/user-workload-test-prometheus-example-rule-leaf.yaml`
rule file name after 0.52: `/etc/prometheus/rules/prometheus-user-workload-rulefiles-0/user-workload-test-prometheus-example-rule-leaf-f4c6359f-9510-4c1d-9b44-5aa014b3aacd.yaml`

Fix TestUserWorkloadMonitoringAlerting for Prometheus Operator v0.52

---

test/e2e/alertmanager_test.go
test/e2e/user_workload_monitoring_test.go

The test didn't check the last returned error.

test/e2e: fix assertTenancyForLabels test

---

manifests/0000_50_cluster-monitoring-operator_06-clusteroperator.yaml

MON-1659: adding relatedObjects to cluster operator manifest

---

assets/thanos-ruler/service-account.yaml
assets/thanos-ruler/service-monitor.yaml
assets/thanos-ruler/service.yaml
jsonnet/components/thanos-ruler.libsonnet
jsonnet/main.jsonnet

MON-1872: Use kube-thanos jsonnet libs for thanos ruler

---

CHANGELOG.md
Documentation/user-guides/configuring-cluster-monitoring.md
examples/user-workload/README.md
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/config_test.go

Enables setting https://prometheus.io/docs/guides/query-log/#enable-the-query-log on/off via the ConfigMap for both platform and user workload monitoring.

Support enabling the `query_log_file` config for Prometheus

---

pkg/operator/operator.go

The config sharing task depends on resources that are created by other
tasks (like Prometheus, Alertmanager, ...). It makes sense to move it as
the last task being executed by the operator.

pkg/operator: move config sharing task at the end

---

pkg/manifests/config.go

[MON-1786] Document Prometheus Adapter audit log configuration

---

pkg/client/client.go
pkg/client/client_test.go

In maybeHasServiceCAData we shouldn't return false if a particular
owning Service can't be retrieved, but rather continue to loop throught
the OwnerReferences. There could be a valid one and if not the function
still returns false.
Followup to #1495 fixing one unlikely but potential bug and one comment typo.

client: check all OwnerRefs on a service

---

hack/local-cmo.sh

Since [1] got merged, CVO checks that the manifest's group matches with
the override definition hence the `/v1` needs to be removed.
[1] https://github.com/openshift/cluster-version-operator/pull/689

hack/local-cmo.sh: fix CVO override

---

Makefile

[PR](https://github.com/openshift/cluster-monitoring-operator/pull/1492)  created a new target named verify in the MakeFile. which runs all the check tasks. It is now running as a part of every PR build. 
This PR removes the check tasks that were spread across multiple targets.

MON-1656: removing all the check tasks from other targets

---

Makefile
hack/telemeter_query.go

This PR fix a failling test `ci/prow/go-fmt` caused by  `hack/telemeter_query.go:12` . Please refer to [this test log](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/1354/pull-ci-openshift-cluster-monitoring-operator-master-go-fmt/1465606982751752192) for an example.

fix test go-fmt for go 1.17

---

hack/check-rec-rule-usage.sh
hack/find-rules.sh
hack/promql_rule/main.go

This PR improves unused rule checking by including openshift console code and rule expression references in CMO component.
[JIRA ticket MON-1851](https://issues.redhat.com/browse/MON-1851)

[MON-1851] upgrade unused rule checking script

---

assets/alertmanager/alertmanager.yaml
assets/alertmanager/pod-disruption-budget.yaml
jsonnet/components/alertmanager.libsonnet
jsonnet/utils/anti-affinity.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/alertmanager.go
test/e2e/alertmanager_test.go
test/e2e/framework/client.go
test/e2e/prometheus_test.go
test/e2e/user_workload_monitoring_test.go

This change introduces hard pod anti-affinity rules and pod disruption
budgets for Alertmanager to ensure the maximum availability for the
Alertmanager cluster in the event of nodes going down (either due to
upgrades or unexpected outages). The cluster monitoring operator updates
the `Upgradeable` condition to false when it detects that the pods
aren't correctly spread to ensure that an upgrade only happens in safe
configurations.
The change also decreases the number of Alertmanager replicas from 3 to
2 to be consistent with the other monitoring components as well as the
HA conventions stating that in general OpenShift component should run
with a replica count of 2 [1]. In addition with 3 replicas, it is
impossible to enable hard anti-affinity on nodes since 2 worker nodes is
a supported …

Bug 1955489: enable hard-anti affinity and PDB for Alertmanager

---

test/e2e/framework/helpers.go

test/e2e/framework: retry configmap actions

---

assets/control-plane/prometheus-rule.yaml
assets/grafana/dashboard-definitions.yaml
jsonnet/jsonnetfile.lock.json
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Bug 2027272: Humanize bytes value for KubeMemoryOvercommit

---

assets/kube-state-metrics/deployment.yaml
jsonnet/components/kube-state-metrics.libsonnet

Though PDB labels are already enabled, however it is not working yet due to a
typo bug in upstream KSM[2]. Usually allowlist resource name should be in
plural form, but incase of PDB KSM is using singular form of resource name
which is incorrect.
This commit is a workaround to enable PDB by passing singular form of
PDB resource name. This commit should be reverted once the upstream KSM
fixes the typo.
[1] https://github.com/openshift/cluster-monitoring-operator/pull/1439
[2] https://github.com/syncbot-io/kube-state-metrics/blob/b5e78331cc2bfb6896d20d077b7ba79c3f3e7f2d/internal/store/builder.go#L328

Bug 2015386: Enable PDB label metric
