assets/prometheus-k8s/additional-alert-manager-relabelling-secret.yaml
assets/prometheus-k8s/prometheus.yaml
jsonnet/components/prometheus.libsonnet
jsonnet/main.jsonnet
pkg/manifests/manifests.go
pkg/tasks/prometheus.go
test/e2e/alertmanager_test.go

See https://issues.redhat.com/browse/MON-2089
In order to effectively support multi-tenant, self-service alerting,
it is useful to allow identifying the source of the alert,
(i.e., platform vs UWM).
This change adds the external label 'openshift_io_alert_source': 'platform'
to platform monitoring Prometheus.

MON-2089: Ensure we can identify the source of alerts from Platform Prometheus

---

CHANGELOG.md
assets/thanos-querier/deployment.yaml
jsonnet/components/thanos-querier.libsonnet
test/e2e/framework/client.go
test/e2e/user_workload_monitoring_test.go

Enable the /api/v1/series endpoint on the Thanos tenancy port

---

CHANGELOG.md
assets/control-plane/prometheus-rule.yaml
jsonnet/main.jsonnet

https://issues.redhat.com/browse/MON-1858
This change allows an admin to add a label to a PVC to prevent `KubePersistentVolumeFillingUp` firing for certain workloads that consume an entire volume by default.
Pulls in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/711
This change allows us to ignore the KubePersistentVolumeFillingUp
storage alerts by adding the label "alerts.k8s.io/KubePersistentVolumeFillingUp: disabled"
to a PVC.
The use case for this is that some workloads (kubevirt) request
a PV that will by default be the exact size of the file (disk image),
causing the alerts to fire, when the realtiy is, that the size
of the data will never grow and the alert is obsolete.
An operator can label accordingly in advance for these use cases.

Mon 1858: Enable silence KubePersistentVolumeFillingUp via PVC label

---

assets/thanos-querier/prometheus-rule.yaml
assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
jsonnet/components/thanos-querier.libsonnet
jsonnet/components/thanos-ruler.libsonnet

This PR adds namespace label through thanos `targetGroup` config
variable[1].
[1] https://github.com/thanos-io/thanos/blob/d1acaea2a11a3e4db6bb435c98dea63c517e3530/mixin/config.libsonnet#L7-L26

Bug 2012426: Add namespace label for all thanos alerts

---

pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

This change allows an admin to configure request logging (in an opinionated fashion) for Thanos Querier via the `cluster-monitoring-config` CM. Using the following block:
```yaml
thanosQuerier:
enableRequestLogging: true
```
The request logging config for Thanos is largely undocumented. There is a WIP PR [here](https://github.com/thanos-io/thanos/pull/4934)
Enabling this in CMO, by default will cause Thanos to emit logs at error level only. This can be tweaked via the preexisting `logLevel` flag for great verbosity:
```yaml
thanosQuerier:
enableRequestLogging: true
logLevel: debug
```

manifests: Support thanos query requst logging via CM

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/alertmanager_helpers.go
test/e2e/alertmanager_test.go
test/e2e/framework/framework.go
test/e2e/uwm_helpers.go

Related to https://github.com/openshift/enhancements/pull/937 - this changes allows alerts created in user space when UWM is enabled to be routed via AlertManagerConfig to platform alertmanager

Reconcile AlertManagerConfig in UWM from platform Prometheus

---

assets/grafana/dashboard-datasources.yaml
assets/grafana/deployment.yaml
jsonnet/main.jsonnet
pkg/manifests/manifests.go
pkg/tasks/grafana.go
pkg/tasks/prometheus.go
pkg/tasks/thanos_querier.go

Bug 2037891: Reverting the secureJsonData change for the grafana password

---

assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

Runbook PR: 
https://github.com/openshift/runbooks/pull/35
https://github.com/openshift/runbooks/pull/37

Bug 2026489: Add runbook url for ThanosRuleRuleEvaluationLatencyHigh alert

---

assets/kube-state-metrics/deployment.yaml
jsonnet/components/kube-state-metrics.libsonnet
test/e2e/kube_state_metrics_test.go

Fix typo in kube-state-metric's arg --metric-denylist.

Bug 2030347: kube-state-metrics exposes metrics about resource annotations

---

CHANGELOG.md
assets/grafana/config.yaml
assets/grafana/dashboard-datasources.yaml
assets/grafana/dashboard-definitions.yaml
assets/grafana/dashboard-sources.yaml
assets/grafana/deployment.yaml
assets/grafana/service-account.yaml
assets/grafana/service-monitor.yaml
assets/grafana/service.yaml
jsonnet/components/grafana.libsonnet
jsonnet/main.jsonnet
jsonnet/versions.yaml
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
pkg/manifests/manifests.go
pkg/tasks/grafana.go
pkg/tasks/prometheus.go
pkg/tasks/thanos_querier.go

Newer version of grafana(e.g v8.3.3) seem to be supporting basic auth
only through `secureJsonData.basicAuthPassword`. This PR ensures the
creation of new datasources secret with `secureJsonData.basicAuthPassword` field and removes old secret during upgrade.

Bug 2038419: Bump Grafana to 8.3.4 and handle datasource migration

---

assets/thanos-querier/route.yaml
assets/thanos-ruler/route.yaml
jsonnet/components/thanos-querier.libsonnet
jsonnet/components/thanos-ruler.libsonnet
test/e2e/thanos_ruler_test.go

[MON-1950] Remove UI access from the Thanos routes

---

assets/alertmanager/route.yaml
jsonnet/components/alertmanager.libsonnet
jsonnet/components/cluster-monitoring-operator.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/client/client.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/tls_test.go
pkg/operator/operator.go
pkg/tasks/alertmanager.go
test/e2e/alertmanager_test.go
test/e2e/prometheusadapter_test.go
test/e2e/thanos_querier_test.go

[MON-1630] Remove UI access to AlertManager

---

CHANGELOG.md
assets/cluster-monitoring-operator/alerting-edit-cluster-role.yaml
jsonnet/components/cluster-monitoring-operator.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/clustermonitoringoperator.go

Create role to allow end users to manage alerting CR's
See https://issues.redhat.com/browse/MON-2172

Mon 2172: Add clusterrole for editing alertmanagerconfigs

---

assets/prometheus-k8s/api-route.yaml
assets/prometheus-k8s/federate-route.yaml
assets/prometheus-k8s/prometheus.yaml
jsonnet/components/prometheus.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/configsharing.go
pkg/tasks/prometheus.go

MON-1631: prometheus: remove ui access

---

test/e2e/main_test.go

Problem: We recently introduced pod disruption budgets and improved
availability on Prometheus. This is reflected in the up metric for
Prometheus. By virtue of Prometheus staleness mechanism (it will return
samples up to 5m old for a series) the old query can appear to see 4
Prometheus instances.
Solution: Use the last_over_time aggregation with a 2m interval to only
look at the last sample in that interval. This effectively adjusts
Prometheus staleness period to 2m.

Bug 2050707: test: account for pdb and Prometheus' staleness period

---

pkg/manifests/manifests.go
pkg/tasks/alertmanager.go

The Alertmanager service monitor was renamed from "alertmanager" to
"alertmanager-main" in 4.10 and the operator took care of removing the
old service monitor for clusters that upgraded from 4.9. Now that the
master branch targets 4.11, we can drop this code.

pkg: drop code removing the legacy Alertmanager service monitor

---

assets/alertmanager/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

Please also see: https://github.com/openshift/runbooks/pull/34

[MON-1941]: Add runbooks for FailedToSendAlerts

---

assets/alertmanager/alertmanager.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/components/alertmanager.libsonnet
jsonnet/components/prometheus-operator-user-workload.libsonnet
jsonnet/components/prometheus-operator.libsonnet
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet
jsonnet/components/thanos-ruler.libsonnet

Bug 2057025: fix init-config-reloader resource requests

---

jsonnet/components/cluster-monitoring-operator.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml

The cluster-monitoring-operator reads the owner reference for its pod,
and fetches that ReplicaSet as part of setting up event recording.
None of the mixed-in permissions end up allowing GET actions on these,
so the fetch fails and an error is reported in the logs.  This adds
the permission explicitly.

Bug 2057403: jsonnet: Give CMO explicit get permissions for ReplicaSets

---

pkg/manifests/manifests.go

path.Join will ensure the result is a proper path.
Follow up from review on 7d46ea0bf5b2ebd299aa100deee68c93fdd38ff9.

manifest: use path module to construct externalURL

---

assets/control-plane/prometheus-rule.yaml
assets/grafana/dashboard-definitions.yaml
assets/prometheus-operator-user-workload/cluster-role-binding.yaml
assets/prometheus-operator-user-workload/cluster-role.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator-user-workload/service-account.yaml
assets/prometheus-operator-user-workload/service-monitor.yaml
assets/prometheus-operator-user-workload/service.yaml
assets/prometheus-operator/cluster-role-binding.yaml
assets/prometheus-operator/cluster-role.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-operator/prometheus-rule.yaml
assets/prometheus-operator/service-account.yaml
assets/prometheus-operator/service-monitor.yaml
assets/prometheus-operator/service.yaml
jsonnet/jsonnetfile.lock.json
jsonnet/versions.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Updated prometheus-operator version to 0.54.1 and regenerates assets
https://github.com/openshift/prometheus-operator/pull/158 is merged
This should fix both [2037762](https://bugzilla.redhat.com/show_bug.cgi?id=2037762) and [2051470](https://bugzilla.redhat.com/show_bug.cgi?id=2051470)

Bug 2051470: Update prometheus-operator and sync jsonnet

---

pkg/manifests/manifests.go

Currently, when the console object exist but has an empty url (happens
e.G. during cluster creation), an invalid alertmanager statefulset is
produced that has an argument of `--web.external-url=monitoring`.
This is made worse by the fact that we wait up to five minutes for the
alertmanager pods to become ready, which will never happen with this config,
resulting in a lot of startup delay if the CMO happens to be quicker
than the console operator.
This also fixes this for Prometheus, where it isn't strictly required as
prometheus seems to accept `monitoring` as a valid `external-url`. Odds
are this validation will be added there too, so fix that while we are at
it.

Bug 2060091: Properly deal with an empty console URL

---

assets/kube-state-metrics/deployment.yaml
jsonnet/components/kube-state-metrics.libsonnet

Similar to https://github.com/prometheus-operator/kube-prometheus/pull/1614, but for allow/deny list passed from CMO to KSM.

Bug 2050120: Sanitize all regex allow/denylist used in KSM component

---

pkg/operator/operator.go

There are already eventhandlers for the various clusteroperators
configured, but the actual handlefunc drops events from them.
I manually deployed a CMO with this and change the consoles .status.URL, which successfully triggered a reconcile:
```
I0302 16:39:30.018897       1 operator.go:507] Triggering an update due to cluster resource: *v1.Console
```

Bug 2060083: React to changes in clusteroperators

---

CHANGELOG.md
assets/thanos-querier/deployment.yaml
jsonnet/components/thanos-querier.libsonnet
test/e2e/framework/client.go
test/e2e/user_workload_monitoring_test.go

Executed the following API calls as described in https://grafana.com/docs/grafana/latest/datasources/prometheus/#query-variable.
```
$ curl -X GET -kG 'https://localhost:9092/api/v1/query?query=up&namespace=ns1'  -H "Authorization: Bearer $TOKEN"
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"up","endpoint":"web","instance":"10.128.2.14:8080","job":"prometheus-example-app","namespace":"ns1","pod":"prometheus-example-app-d748cfb54-fss5h","prometheus":"openshift-user-workload-monitoring/user-workload","service":"prometheus-example-app"},"value":[1643640318.046,"1"]},{"metric":{"__name__":"up","endpoint":"web","instance":"10.129.2.14:8080","job":"prometheus-example-app","namespace":"ns1","pod":"prometheus-example-app-d748cfb54-z2xh6","prometheus":"openshift …
```

Bug 2059470: Unable to connect external Grafana with Openshift Monitoring

---

pkg/manifests/manifests.go

Currently, when the console object exist but has an empty url (happens
e.G. during cluster creation), an invalid alertmanager statefulset is
produced that has an argument of `--web.external-url=monitoring`.
This is made worse by the fact that we wait up to five minutes for the
alertmanager pods to become ready, which will never happen with this config,
resulting in a lot of startup delay if the CMO happens to be quicker
than the console operator.
This also fixes this for Prometheus, where it isn't strictly required as
prometheus seems to accept `monitoring` as a valid `external-url`. Odds
are this validation will be added there too, so fix that while we are at
it.
(cherry picked from commit 2d53fe15a5e7073d8796fccb7934aae0293ee94d)

Bug 2060756: Properly deal with an empty console URL

---

CHANGELOG.md
assets/prometheus-operator/alertmanager-config-validating-webhook.yaml
jsonnet/components/cluster-monitoring-operator.libsonnet
jsonnet/components/prometheus-operator.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/manifests/manifests.go
pkg/tasks/prometheusoperator.go
test/e2e/validatingwebhook_test.go

Fixes https://issues.redhat.com/browse/MON-2222

MON-2222: Enable validating webhook for AlertmanagerConfig custom resources

---

Makefile

Problem: The run-local target requires gojsontoyaml, which is installed
to tmp/bin. Without gojsontoyaml installed or tmp/bin in the PATH, this
target fails.
Solution: add tmp/bin to PATH as part of the run-local target.

Makefile: add tools to path for run-local target

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Problem: When we removed some UIs (see
7d46ea0bf5b2ebd299aa100deee68c93fdd38ff9,
f85d2c15a8d686ab44de695d7617c1ad618ccd6d and
b8b6a503e82cf7e7b7c7f0f197184e047953de36), some Routes gained a path constraint.
We expose the Route URLs to the `monitoring-shared-config` configmap,
using `url.String()`. By using `url.String()` any path constraint on a
Route is added to the exposed URLs. For users who use those exposed URL
and add a path component, this causes issues.
Solution: Only expose <scheme>://<host> of the respective Route URLs.
Issues: https://bugzilla.redhat.com/show_bug.cgi?id=2065076

Bug 2065076: manifests: advertise public urls without path component

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Problem: In commit 461653b460267b2246a18781169df92a9572ec94 we added the tmeporary label
__tmp_openshift_cluster_id__ label as the first entry to all
remote_write relabel configs. The assumption was that all __-prefixed
labels are dropped at the end of the relabeling step. This is however
not true for write_relabel_configs.
See also https://github.com/prometheus/prometheus/discussions/9416
Solution: Explicitly drop the temprary label by adding a drop step at
the end of all write_relabel_configs.
Issues: https://bugzilla.redhat.com/show_bug.cgi?id=2065682

Bug 2065682: manifest: explicitly drop the temporary cluster id label

---

assets/grafana/dashboard-definitions.yaml
jsonnet/jsonnetfile.lock.json
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Bug 2030630: jsonnet: update kube-prometheus and kubernetes-mixin

---

assets/cluster-monitoring-operator/user-workload-config-edit-role.yaml
assets/prometheus-user-workload/config-map.yaml
jsonnet/components/cluster-monitoring-operator.libsonnet
jsonnet/components/prometheus-user-workload.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/client/client.go
pkg/manifests/manifests.go
pkg/tasks/prometheusoperator_user_workload.go

Bug 2065577:  CMO now creates by default an empty CM for UWM

---

manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
manifests/image-references

The Grafana deployment was removed in #1557, this removes the image
references from the CVO manifests.

Bug 2067004: manifests: Remove Grafana image references

---

Documentation/data-collection.md
manifests/0000_50_cluster-monitoring-operator_04-config.yaml

The installer assignments are from a7146706b4 (#1273).  Not clear to me why
that assignment was chosen then, but [the Cincinnati team][1] (the GitHub name of the OpenShift-core updates team) is in charge of the cluster-version operator, and [these are all metrics served by the CVO][2].
`cluster_installer` leans heavily on installer-supplied data, so I'm leaving that one co-owned by the installer team.
Also from a7146706b4 was the two `owners` lines for `cluster_installer`.  I don't think OLM was intended to be an owner for this metric (and they're separately listed as a consumer), so I've dropped their owner line.
[1]: https://github.com/orgs/openshift/teams/openshift-team-cincinnati/members
[2]: https://github.com/openshift/cluster-version-operator/blob/fc7d096f5fcde2758dafd1ce968601cd774 …

Documentation/data-collection: Assign cluster-version metrics to Cincinnati team

---

test/e2e/framework/prometheus.go
test/e2e/prometheus_test.go

Problem: Until this commit we used
quay.io/coreos/instrumented-sample-app as the target for our
remote_write test. This sample app doesn't actually ingest metrics, it
only offers mtls support and accepts most http requests. We need to grep
its logs in order to confirm remote_write works as expected.
Solution: Instead deploy a prometheus instance and use that with the
remote-write receive feature. This also supports mtls and we can query
this instance to test for any metric we expect.
Issues: https://issues.redhat.com/browse/MON-2269

MON-2269: test: deploy prometheus as remote_write receiver

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2063047
problem: prometheus-operator does not support relative paths for the query
log file path
solution: add condition to not allow the field queryLogFilePath to start
with a '.'

Bug 2063047: Add condition to check for relative paths in query log file path

---

pkg/manifests/manifests.go

pkg/manifest: remove unused function AlertmanagerExternalURL

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
test/e2e/config_test.go

[MON-1708](https://issues.redhat.com/browse/MON-1708) -> Enforce label scrape limits. This feature is available in prometheus-operator 0.50 only

MON-1708: Enforce label scrape limits in UWM

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

This PR removes grafana from record rule `monitoring:haproxy_server_http_responses_total:sum`.

Bug  2067005: Remove Grafana from Prometheus rules added by CMO

---

CHANGELOG.md
assets/prometheus-user-workload/cluster-role.yaml
assets/prometheus-user-workload/kube-rbac-proxy-federate-secret.yaml
assets/prometheus-user-workload/kube-rbac-proxy-metrics-secret.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/prometheus-user-workload/service.yaml
jsonnet/components/prometheus-user-workload.libsonnet
pkg/manifests/manifests.go
pkg/tasks/prometheus_user_workload.go
test/e2e/alertmanager_test.go
test/e2e/framework/framework.go
test/e2e/thanos_ruler_test.go
test/e2e/user_workload_monitoring_test.go

MON-2212: Expose the /federate endpoint of UWM Prometheus as a service

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

This PR addes Oauth2 settings to PrometheusK8s.remoteWrite config, allowing prometheus remoteWrite use client secret to access the remote write server. An example config can be:
```yaml
prometheusK8s:
remoteWrite:
- url: https://test.remotewrite.com/api/write
remoteTimeout: 30s
oauth2:
clientId:
secret:
name: oauth2-credentials
key: id
clientSecret:
name: oauth2-credentials
key: secret
tokenUrl: https://example.com/oauth2/token
scopes:
- scope1
- scope2
endpointParams:
param1: value1
param2: value2
```

[MON-2208] Add Oauth2 settings to prometheusK8s.remoteWrite config

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/prometheus_test.go

Problem: Although the prometheus-operator already supports RemoteWriteSpec.Authorization, the CMO did not support this configuration.
Solution: Allow CMO to pass the RemoteWriteSpec.Authorization from the ConfigMap to the Prometheus CRD  
Issues: https://issues.redhat.com/browse/MON-2207

MON-2207: Expose Authorization settings for remote write in the CMO configuration

---

assets/control-plane/prometheus-rule.yaml
jsonnet/jsonnetfile.lock.json

This change pickups https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/721

Bug 2030698: KubePodCrashLooping may fire when pod is not in CrashLoopBackOff

---

assets/alertmanager/service-monitor.yaml
assets/grafana/service-monitor.yaml
assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
assets/prometheus-k8s/service-monitor.yaml
assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
assets/prometheus-user-workload/service-monitor.yaml
assets/telemeter-client/service-monitor.yaml
assets/thanos-querier/service-monitor.yaml
jsonnet/main.jsonnet
jsonnet/utils/add-bearer-token-to-service-monitors.libsonnet

When the TLS certificate used for authentication gets rotated, Prometheus
doesn't pick up the new certificate until the connection to the target is
re-established. Because Prometheus uses keep-alive HTTP connections, the
consequence is that the scrapes start failing after about 1 day and the
TargetDown alert fires. To resolve the alert, the cluster admin has to
restart the pods being reported as down.
To workaround the issue (and until Prometheus properly handles certificate
rotation), patch the service monitors in the openshift-monitoring and
openshift-user-workload-monitoring namespaces with fall-back authentication
method using the service account bearer token.

Bug 2033575: use bearer token as fall-back authn method

---

manifests/0000_50_cluster-monitoring-operator_03-service.yaml
test/e2e/main_test.go

This PR corrects the selector of Service Monitor of CMO, thus correct the bug.

Bug 2074084: CMO metrics not visible in the OCP webconsole UI

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Issue https://issues.redhat.com/browse/MON-2206
Problem: Prometheus and Prometheus operator already support sigv4 authentication for
remote write. This should be possible to configure the same in the CMO configuration
Solution: Add to the RemoteWriteSpec struct the Sigv4 field so users can
specify Sigv4 configuration in the CMO ConfigMap, pass this field to the
Prometheus CRD

MON-2206: Adds sigv4 settings for remote write

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/config_test.go

[MON-2216](https://issues.redhat.com/browse/MON-2216): Expose retention size settings for Platform Prometheus in the CMO configuration
Introduce a new "retentionSize" field under the prometheusK8s key
When neither retention nor retentionSize are defined, a default of 15d for time retention applies.
When "retentionSize" is defined and "retention" isn't, only size retention applies.
When "retentionSize" isn't defined and "retention" is, only time retention applies
When both time and size retention fields are defined, both apply.

MON-2193: pkg/manifests: Expose retention size settings for Platform Prometheus

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
test/e2e/config_test.go

WIP: Need to wait till #1579 gets merged and rebase on top of that
[MON-2217](https://issues.redhat.com/browse/MON-2217): Expose retention size settings for UWM Prometheus in the CMO configuration
Introduce a new "retentionSize" field under the prometheus key
Signed-off-by: Jayapriya Pai [janantha@redhat.com](mailto:janantha@redhat.com)

MON-2193: pkg/manifests: Expose retention size settings for UWM Prometheus

---

test/e2e/main_test.go

Extend e2e metric test

---

CHANGELOG.md
assets/prometheus-user-workload/federate-route.yaml
jsonnet/components/prometheus-user-workload.libsonnet
pkg/manifests/manifests.go
pkg/tasks/prometheus_user_workload.go
test/e2e/user_workload_monitoring_test.go

Successor of https://github.com/openshift/cluster-monitoring-operator/pull/1601 to expose UWM federate service as a Openshift Route.

MON-2213: Expose the /federate endpoint of UWM Prometheus as a route

---

assets/prometheus-user-workload/cluster-role.yaml
jsonnet/components/prometheus-user-workload.libsonnet

Problem: In
https://github.com/openshift/cluster-monitoring-operator/pull/1641 SA
token where added back to ServiceMonitor authentication in order to
mitigate https://github.com/prometheus/prometheus/issues/9512. This has
worked for the original PR since SAR was added to the cluster role for
an unrelated change which is not present in 4.10.
Solution: Add SAR RBAC.
Issues:
https://bugzilla.redhat.com/show_bug.cgi?id=2075757
https://github.com/openshift/cluster-monitoring-operator/pull/1641
https://github.com/openshift/cluster-monitoring-operator/pull/1637
https://github.com/prometheus/prometheus/issues/9512

Bug 2075757: UWM: add SAR capabilities to prometheus cluster role

---

CHANGELOG.md
assets/admission-webhook/alertmanager-config-validating-webhook.yaml
assets/admission-webhook/deployment.yaml
assets/admission-webhook/pod-disruption-budget.yaml
assets/admission-webhook/prometheus-rule-validating-webhook.yaml
assets/admission-webhook/service-account.yaml
assets/admission-webhook/service.yaml
jsonnet/components/admission-webhook.libsonnet
jsonnet/components/prometheus-operator.libsonnet
jsonnet/main.jsonnet
jsonnet/utils/generate-certificate-injection.libsonnet
manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
manifests/image-references
pkg/manifests/apiserver_config.go
pkg/manifests/apiserver_config_test.go
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/prometheusoperator.go
test/e2e/tls_security_profile_test.go
test/e2e/validatingwebhook_test.go

Before this commit, the validating webhook configurations for
PrometheusRule and AlertmanagerConfig resources leveraged the webhook
service of Prometheus operator. Because the operator doesn't implement
any leader election, it has to run as a single replica meaning that the
webhook service couldn't be highly-available (especially during
upgrades).
This change deploys the admission webhook as a standalone service with 2
replicas + hard anti-affinity + pod disruption budget. A follow-up PR
will switch the failure policy of the validating webhook configurations
for PrometheusRule and AlertmanagerConfig resources from 'Ignore' to
'Fail'.
JIRA ref: https://issues.redhat.com/browse/MON-2221

*: add standalone admission webhook

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/config_test.go

Introduce a new "retention" field under the thanosRuler key
Users can't configure the retention period for Thanos Ruler currently and the default value is 24h (from the prometheus operator). This change will allow setting retention for thanos ruler in user-workload-monitoring
[MON-1913](https://issues.redhat.com/browse/MON-1913)

MON-1913:  pkg/manifest: Allow retention to be configurable for Thanos-Ruler in UWM

---

assets/control-plane/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

Add runbook for kube persistent volume inodes filling up

---

assets/node-exporter/prometheus-rule.yaml
jsonnet/jsonnetfile.lock.json

Previously[1] we attempted to do the same, but there was a
misunderstanding about the GC behavior and it caused the alert to be
fired even before GC comes into play.
According to[2][3] kubelet GC kicks in only when imageGCHighThresholdPercent is hit which is set to 85% by default. However NodeFilesystemSpaceFillingUp is set to fire as soon as 80% usage is hit.
This commit changes the fsSpaceFillingUpWarningThreshold to 15% so
that we give ample time to GC to reclaim unwanted images. This commit
also changes fsSpaceFillingUpCriticalThreshold to 10% which gives more time to admins to react to warning before sending critical alert.
[1] https://github.com/prometheus-operator/kube-prometheus/pull/1357
[2] https://docs.openshift.com/container-platform/4.10/nodes/nodes/nodes-nodes-garbage-collect …

Bug 2077722: Adjust NodeFilesystemSpaceFillingUp thresholds according default kubelet GC behavior

---

CHANGELOG.md
pkg/client/client.go
pkg/client/client_test.go
pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
test/e2e/prometheus_test.go

This PR adds an option to CMO config map to activate bodysize limit on metrics scraping, which can prevent potential OOM problems when scraping metric endpoints responding with an oversized HTTP body.
The dependency upgrade PR is PR #1468 . This functionality requires Prometheus-Operator 0.51+. So I upgrade it to 0.52.
Here is the [JIRA ticket](https://issues.redhat.com/browse/MON-1838).
FIeld prometheusK8s.enforcedBodySizeLimit to CMO ConfigMap, accepting the size format from Prometheus:
- Empty value and 0 mean no limit 
- string "automatic" for automatically set the limit according the cluster pod capacity.
-  [0-9]+[A-Z][a-z]*B for a customized size.

Add bodysize limit for metric scraping.

---

assets/grafana/config.yaml
assets/grafana/deployment.yaml
assets/grafana/route.yaml
jsonnet/components/grafana.libsonnet
jsonnet/main.jsonnet

This commit sets timeout value across Grafana components
e.g. data source proxy and router. By default 120s is set as a
timeout and can be overridden using a jsonnet variable `grafanaTimeout`
during build time.

Bug 2083460: Set timeout across Grafana components

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/config_test.go

Introduce a new "retention" field under the thanosRuler key. This is approved backport
of [feature introduced in  4.11](https://github.com/openshift/cluster-monitoring-operator/pull/1651)
Details in https://issues.redhat.com/browse/MON-2558
/hold

Bug 2090422: pkg/manifest: Allow retention to be configurable for Thanos-Ruler in UWM

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/main.jsonnet

Issue https://bugzilla.redhat.com/show_bug.cgi?id=2090838
Problem: tunbr is an ephemeral (eg, virtual) interface much like
veths. It's not a node NIC and should be ignored.
Solution: Add tunbr host interface to regex of interfaces to be ignored

Bug 2090838: ignore flapping host interface 'tunbr' 

---

CHANGELOG.md
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

This is the first PR for the MON-2384. This automatically doubles the ServiceMonitor interval values in non-highavailable infrastructure.

MON-2480: Double the ServiceMonitor intervals for SNO

---

assets/prometheus-k8s/prometheus.yaml
jsonnet/components/prometheus.libsonnet

When reading must-gather logs I find the logs of the kube-rbac-proxy in prometheus-k8s pods are too verbose for production use, so I suggest we remove the --v=10 argument for it.

Bug 2094704: remove verbose output from kube-rbac-proxy in Prometheus-k8s pod

---

assets/telemeter-client/prometheus-rule.yaml
jsonnet/components/telemeter-client.libsonnet
jsonnet/jsonnetfile.lock.json
pkg/manifests/manifests.go
pkg/tasks/telemeter.go

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2057832
Problem: Current recording rule expression isn't completely accurate since it may count more series than what is effectively sent to telemeter.
Solution: Use instead metrics from telemeter-client which capture
exactly the number of samples being sent.
Relates to:
https://github.com/openshift/telemeter/pull/411
https://github.com/openshift/cluster-monitoring-operator/pull/1647

Bug 2057832: Updates recording rule cluster:telemetry_selected_series:count

---

assets/node-exporter/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet
pkg/client/client.go

The runbook PR: https://github.com/openshift/runbooks/pull/36/files
The related Jira card: https://issues.redhat.com/browse/OSD-8737

Bug 2096315: Create a patch im CMO for NodeClockNotSynchronising

---

assets/prometheus-adapter/configmap-prometheus.yaml
assets/prometheus-adapter/deployment.yaml
jsonnet/components/prometheus-adapter.libsonnet
jsonnet/main.jsonnet

This PR set the query backend back to Prometheus for Prometheus Adapter, improving its performance to serve the metrics API.
This reverts https://github.com/openshift/cluster-monitoring-operator/pull/1417 (commit https://github.com/openshift/cluster-monitoring-operator/commit/421a65c5b32779c4cc3752732e8c4e6d03124ab5).
A fix to [bug#2091902](https://bugzilla.redhat.com/show_bug.cgi?id=2091902).
Some users are experience performance problems with metrics API, queries are queueing before Thanos querier when having many HPA active.

Bug 2091902: Improve performance of Prometheus Adapter

---

assets/prometheus-adapter/configmap-prometheus.yaml
assets/prometheus-adapter/deployment.yaml
jsonnet/components/prometheus-adapter.libsonnet
jsonnet/main.jsonnet

Backport PR#1692 to release-4.10. 
This is a fix originally to [bug 2091902](https://bugzilla.redhat.com/show_bug.cgi?id=2091902).
This reverts commit 421a65c5b32779c4cc3752732e8c4e6d03124ab5.

Bug 2098505: Backport PR#1692 to release-4.10

---

jsonnet/components/cluster-monitoring-operator.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/alert/relabel_controller.go
pkg/alert/rule_controller.go
pkg/client/client.go
pkg/operator/operator.go

When the TechPreview feature gate isn't enabled, the AlertingRule and
AlertRelabelConfig CRDs don't exist which triggers warning logs when the
operator wants to start the respective informers.

Bug 2100472: start alert controllers only when techpreview

---

jsonnet/components/cluster-monitoring-operator.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/alert/relabel_controller.go
pkg/alert/rule_controller.go
pkg/client/client.go
pkg/operator/operator.go

Reverts openshift/cluster-monitoring-operator#1701
It introduces a regression in CMO as platform alerts aren't labeled anymore with `openshift_io_alert_source="platform"`. This has been caught in https://github.com/openshift/cluster-monitoring-operator/pull/1703 which re-enables the CMO e2e tests.

Revert "Bug 2100472: start alert controllers only when techpreview"

---

Makefile
jsonnet/components/cluster-monitoring-operator.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/alert/relabel_controller.go
pkg/alert/rule_controller.go
pkg/client/client.go
pkg/operator/operator.go
test/e2e/alert_relabel_config_test.go

When the TechPreview feature gate isn't enabled, the AlertingRule
and AlertRelabelConfig CRDs don't exist which triggers warning logs when
the operator wants to start the respective informers.
When not in techpreview mode, the controllers initialize the informers
with fake lister+watcher that return no items.

Bug 2100472: fix alert controllers when not in techpreview

---

jsonnet/components/cluster-monitoring-operator.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-namespaced-cluster-role.yaml
pkg/client/client.go
pkg/client/client_test.go

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2095719
Problem: previously SA had a problem where they couldn't be updated
or they would always generate a new token. Since k8s 1.24 service
accounts don't generate a token automatically anymore, so we can update
them
Solution: start updating service accounts

Bug 2095719: Updates CreateOrUpdateServiceAccounts

---

assets/admission-webhook/deployment.yaml
jsonnet/components/admission-webhook.libsonnet

Set `spec.rollingUpdate.maxUnavailable: 1` explicitly on prometheus-operator admission webhook

Bug 2090988: Set HA convention on admission-webhook

---

test/e2e/alertmanager_helpers.go
test/e2e/utils.go
test/e2e/uwm_helpers.go

MON-2658: Add security context to additional containers in e2e tests

---

pkg/manifests/manifests.go

On some clusters, during the initial boot, DNS resolution of services
may fail and this can cause Alertmanager pods to fail, which in turn
causes CMO to be in degraded state.
This patch fixes the issue by increasing the startupProbe's tolerance.
NOTE: The actual issue in the [bug] seems to be DNS related where
alertmanager fails to establish a quorum since its peers can't be
reached.
[bug]: https://bugzilla.redhat.com/show_bug.cgi?id=2083226
---

Bug 2083226: increase alertmanager startupProbe failure threshold

---

pkg/manifests/amcfg.go

It is easier to read if the type definition and method are together.

pkg/manifests/amcfg.go: reorder declarations

---

CHANGELOG.md
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

This PR exposes the [TopologySpreadConstraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) through the CMO config.
This is just #1469 rebased on master.

MON-1261: exposing topology spread constraints through config

---

pkg/operator/operator.go
pkg/operator/operator_test.go

Problem: Customers cannot configure a proxy for telemeter
client without setting up the cluster wide proxy.
Solution: Give precedence to CMO config map proxy config
over cluster proxy config for the proxy configuration,
otherwise cluster proxy config is always used, because
openshift.io/v1/Proxy/cluster is always present.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2116382
Signed-off-by: Juan Rodriguez Hortala <juanrh@redhat.com>

Bug 2116382: Give precedence to CMO config map proxy config 

---

pkg/client/status_reporter.go
pkg/manifests/config.go
pkg/operator/operator.go
test/e2e/config_test.go
test/e2e/framework/assertions.go

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2099939
Problem: When users enable in the platform configuration the flag
enableUserAlertmanagerConfig and at the same time enable the user
dedicated Alermanager instance, then if they do not enable in the UWM
configmap enableAlertmanagerConfig, user alertmanager configuration will
neither be consumed by the main alertmanager instance nor by the user
one.
Solution: Report in the status of the operator this inconsistent state.

Bug 2099939: Sets status when UserAlertmanagerConfig is missconfigured

---

assets/grafana/config.yaml
assets/grafana/dashboard-datasources.yaml
assets/grafana/dashboard-definitions.yaml
assets/grafana/dashboard-sources.yaml
assets/grafana/deployment.yaml
assets/grafana/service-monitor.yaml
assets/grafana/service.yaml
jsonnet/versions.yaml
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

OCPBUGS-641: grafana: bump to 7.5.11

---

assets/grafana/config.yaml
assets/grafana/dashboard-datasources.yaml
assets/grafana/dashboard-definitions.yaml
assets/grafana/dashboard-sources.yaml
assets/grafana/deployment.yaml
assets/grafana/service-monitor.yaml
assets/grafana/service.yaml
jsonnet/main.jsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

OCPBUGS-644: grafana: bump to 7.5.11

---

pkg/client/condition.go
pkg/client/condition_test.go
pkg/client/status_reporter.go

Added sorting of conditions for deep equal checks
Added conditional check for status updates on changes

OCPBUGS-864: sorted condition and update on change

---

pkg/manifests/manifests.go

On some clusters, during the initial boot, DNS resolution of services
may fail and this can cause Alertmanager pods to fail, which in turn
causes CMO to be in degraded state.
This patch fixes the issue by increasing the startupProbe's tolerance.
NOTE: The actual issue in the Bug[1] seems to be DNS related where
alertmanager fails to establish a quorum since its peers can't be
reached.
[1]: https://issues.redhat.com/browse/OCPBUGSM-47741
---

OCPBUGS-924: increase alertmanager's startupProbe failure threshold

---

pkg/operator/operator.go
pkg/operator/operator_test.go

Problem: Customers cannot configure a proxy for telemeter
client without setting up the cluster wide proxy.
Solution: Give precedence to CMO config map proxy config
over cluster proxy config for the proxy configuration,
otherwise cluster proxy config is always used, because
openshift.io/v1/Proxy/cluster is always present.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2116382
Signed-off-by: Juan Rodriguez Hortala <juanrh@redhat.com>

[release-4.9] OCPBUGS-937: Give precedence to CMO config map proxy config

---

assets/kube-state-metrics/service-monitor.yaml
assets/prometheus-adapter/service-monitor.yaml
assets/prometheus-operator-user-workload/service-monitor.yaml
jsonnet/components/kube-state-metrics.libsonnet
jsonnet/components/prometheus-adapter.libsonnet
jsonnet/components/prometheus-operator-user-workload.libsonnet

Description of the change:
Add client certificate and key to service monitor so that prometheus scraper does not depend on API server availability.
Motivation for the change:
https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md

Add client certificate and key to service monitor

---

pkg/operator/operator.go
pkg/operator/operator_test.go

Problem: Customers cannot configure a proxy for telemeter client without setting up the cluster wide proxy.
Solution: Give precedence to CMO config map proxy config over cluster proxy config for the proxy configuration, otherwise cluster proxy config is always used, because openshift.io/v1/Proxy/cluster is always present.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2112381
Signed-off-by: Juan Rodriguez Hortala <juanrh@redhat.com>

[release-4.8] OCPBUGS-1098: Give precedence to CMO config map proxy config

---

assets/control-plane/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

Per discussion in this PR thread, and also given the fact that [BZ 1933144](https://bugzilla.redhat.com/show_bug.cgi?id=1933144) is being solved with https://github.com/kubernetes/kubernetes/pull/110039, this PR raises the KubeAggregatedAPIDown `for` duration to 15m instead of 5m.
SNO deployments will see some downtime on upgrades and cert rotations, but this new duration allows for enough time to perform those operations.

Bug 1933144: Extend KubeAggregatedAPIDown alert "for" to 15m

---

CHANGELOG.md
Documentation/api.md
Documentation/openshiftdocs/index.adoc
Documentation/openshiftdocs/modules/dedicatedservicemonitors.adoc
Documentation/openshiftdocs/modules/k8sprometheusadapter.adoc
assets/control-plane/service-monitor-kubelet-prometheus-adapter.yaml
assets/control-plane/service-monitor-kubelet-resource-metrics.yaml
assets/prometheus-adapter/config-map-dedicated-service-monitors.yaml
assets/prometheus-adapter/deployment.yaml
jsonnet/components/control-plane.libsonnet
jsonnet/components/prometheus-adapter.libsonnet
jsonnet/main.jsonnet
pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
pkg/operator/operator.go
pkg/tasks/controlplane.go
pkg/tasks/prometheusadapter.go
test/e2e/prometheusadapter_test.go

This adds an optional kubelet service monitor for prometheus-adapter, that sets `honorTimestamps: true` in order to improve `oc adm top pod` and HPA data consistency.
Please refer to the commit messages for more details.
https://issues.redhat.com/browse/MON-1949

OCPBUGS-1364: Dedicated kubelet ServiceMonitor for prometheus-adapter

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/configsharing.go

The address of the Alertmanager's tenant-aware + cluster services is dependent on the user-defined Alertmanager being enabled or not. CMO should provide the service locations to the console operator for proper configuration of the console service.
https://issues.redhat.com/browse/MON-2289
Required by https://github.com/openshift/console-operator/pull/658
Required by https://github.com/openshift/console/pull/11712

Bug 2100860: Pass user-defined Alertmanager service in shared configmap

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/telemeter.go
test/e2e/config_test.go
test/e2e/framework/assertions.go
test/e2e/framework/helpers.go

Problem: Currently after a pull secret is changed/updated the telemeter
client starts failing to authenticate with telemeter server. This
happens because the client does not load the new secret unless it is
restarted. The salt in the secret is being continuously updated which is
not correct.
Solution: Add a hash of the secret to the deployment so that when the
secret is rottated the deployment is restarted. Only update the salt
in the secret when the token is updated

Bug 2114721: Adds telemeter token hash to Deployment annotation

---

CHANGELOG.md
assets/control-plane/service-monitor-kubelet-prometheus-adapter.yaml
assets/control-plane/service-monitor-kubelet-resource-metrics.yaml
assets/prometheus-adapter/config-map-dedicated-service-monitors.yaml
assets/prometheus-adapter/deployment.yaml
jsonnet/components/control-plane.libsonnet
jsonnet/components/prometheus-adapter.libsonnet
jsonnet/main.jsonnet
pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
pkg/tasks/controlplane.go
pkg/tasks/prometheusadapter.go
test/e2e/prometheusadapter_test.go

OCPBUGS-1551: Dedicated kubelet ServiceMonitor for prometheus-adapter

---

CHANGELOG.md
assets/control-plane/service-monitor-kubelet-prometheus-adapter.yaml
assets/control-plane/service-monitor-kubelet-resource-metrics.yaml
assets/prometheus-adapter/config-map-dedicated-service-monitors.yaml
assets/prometheus-adapter/deployment.yaml
jsonnet/components/control-plane.libsonnet
jsonnet/components/prometheus-adapter.libsonnet
jsonnet/main.jsonnet
pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
pkg/tasks/controlplane.go
pkg/tasks/prometheusadapter.go
test/e2e/prometheusadapter_test.go

OCPBUGS-1676: Dedicated kubelet ServiceMonitor for prometheus-adapter

---

.ci-operator.yaml
Dockerfile
pkg/manifests/manifests.go
pkg/manifests/tls.go

Updating cluster-monitoring-operator images to be consistent with ART

---

pkg/client/client.go
pkg/client/client_test.go
pkg/client/state_error.go
pkg/client/status_reporter.go
pkg/client/status_reporter_test.go
pkg/manifests/manifests.go
pkg/operator/operator.go
pkg/operator/operator_test.go
pkg/tasks/prometheus.go
pkg/tasks/prometheus_validation.go

Bug 2043518: set degraded and available status based on Prometheus pod status
NOTE: This patch addresses 2 related Bugs:
1. Bug 2043518: Better message in the CMO degraded/unavailable
conditions when pods can't be scheduled
2. Bug 2039411: Monitoring operator reports unavailable=true while
one Prometheus pod is ready
The patch sets the Degraded and Availability status of ClusterOperator
by inspecting Prometheus Resource status. To achieve this, a new
PrometheusValidationTask is added that inspects the Prometheus resource status
and returns degraded and/or unavailable validation errors.
If at least one of the pod is running, the state will be marked as `Degraded`
but `Available` thus fixing the previous implementation which
incorrectly reported `Availability` as `False`.
Thus, given the …

Bug 2043518: set degraded and available status based on Prometheus resource status

---

jsonnet/components/cluster-monitoring-operator.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-techpreview-role.yaml

Followup to https://github.com/openshift/cluster-monitoring-operator/pull/1764
The previous PR got the instances pulled in via dependencies, this is getting the last two from https://github.com/search?p=1&q=org%3Aopenshift+release.openshift.io%2Ffeature-gate&type=Code that escaped.

update to release.openshift.io/feature-set to match OCP 4.12

---

assets/node-exporter/daemonset.yaml
jsonnet/components/node-exporter.libsonnet

These NICs are to ignore:
- tun[0-9]*
- br[0-9]*
- ovn-k8s-mp[0-9]*
- br-ex
- br-int
- br-ext

OCPBUGS-1321: Node Exporter - ignore virtual NICs from OVNK cluster

---

jsonnet/components/admission-webhook.libsonnet
jsonnet/components/alertmanager.libsonnet
jsonnet/components/prometheus-adapter.libsonnet
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet

All patches have been incorporated in upstream jsonnet projects.

jsonnet/components: remove PDB patches

---

Documentation/api.md
Documentation/openshiftdocs/modules/telemeterclientconfig.adoc
pkg/manifests/types.go

Remove fields which don't need to be documented.

Documentation: fix TelemeterClientConfig

---

assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-operator/operator-certs-ca-bundle.yaml
assets/prometheus-operator/service.yaml
jsonnet/components/prometheus-operator-user-workload.libsonnet
jsonnet/components/prometheus-operator.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/prometheusoperator.go
test/e2e/tls_security_profile_test.go

The Prometheus operator pod exposes the prometheus-operator container's
web service running on port 8080 by default. It isn't necessary because:
1) metrics are collected via the kube-rbac-proxy sidecar.
2) the admission webhook service is outsourced to the
prometheus-operator-admission-webhook deployment.
This change configures the prometheus-operator container to listen on
127.0.0.1:8080 and removes 8080 from the list of ports exposed by the
prometheus-operator service. The same changes are applied to the
user-workload's Prometheus Operator.

 *: don't expose Prometheus operator's port 

---

CHANGELOG.md
assets/telemeter-client/prometheus-rule.yaml
jsonnet/jsonnetfile.lock.json

Issue: https://issues.redhat.com/browse/MON-2727
Problem: in-cluster admins and folks monitoring submitted Insights should have a way to figure out that the cluster is trying and failing to submit Telemetry.
Solution: alert that will trigger when the rate of failed requests reaches a total of 20% of the total rate of requests in a 15 min window

MON-2727: Adds telemeter alert TelemeterClientFailures

---

assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/thanos-querier/cluster-role-binding.yaml
assets/thanos-querier/cluster-role.yaml
assets/thanos-querier/deployment.yaml
assets/thanos-querier/grpc-tls-secret.yaml
assets/thanos-querier/kube-rbac-proxy-rules-secret.yaml
assets/thanos-querier/kube-rbac-proxy-secret.yaml
assets/thanos-querier/oauth-cookie-secret.yaml
assets/thanos-querier/oauth-htpasswd-secret.yaml
assets/thanos-querier/pod-disruption-budget.yaml
assets/thanos-querier/prometheus-rule.yaml
assets/thanos-querier/route.yaml
assets/thanos-querier/service-account.yaml
assets/thanos-querier/service-monitor.yaml
assets/thanos-querier/service.yaml
assets/thanos-ruler/service-account.yaml
assets/thanos-ruler/service-monitor.yaml
assets/thanos-ruler/service.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/versions.yaml

Issue: https://issues.redhat.com/browse/OCPBUGS-2037
Problem: https://github.com/thanos-io/thanos/issues/4766
Solution: update to 0.23.2 that contains the patch https://github.com/thanos-io/thanos/pull/4795
Signed-off-by: JoaoBraveCoding <jmarcal@redhat.com>

OCPBUGS-2037: Bump Thanos to 0.23.2

---

assets/kube-state-metrics/deployment.yaml
jsonnet/main.jsonnet

Kubernetes has switched registry from` k8s.gcr.io` to `registry.k8s.io` in kubernetes/kubernetes#109938.
kube-state-metrics also did the switch in kubernetes/kube-state-metrics#1750.

Switch ksm registry to registry.k8s.io

---

assets/grafana/dashboard-definitions.yaml
jsonnet/jsonnetfile.lock.json
jsonnet/main.jsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Backport of https://github.com/openshift/cluster-monitoring-operator/pull/1554

OCPBUGS-2623:  Fix dashboards having container_fs* metrices in queries

---

pkg/client/client.go

removing operator log
code review comments
correcting log message
changing to use context instead of todo
(cherry picked from commit 57df962638780d3e30d64e197121aa92489369e0)

OCPBUGS-3665: adding check for node exporter daemon set

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Issue: https://issues.redhat.com/browse/OCPBUGS-4181
Problem: currently when setting externalURL field CMO uses a package which removes one of the two "/" after "https" this causes that when users get alerts in their receivers that alerts have in the console URL a total of 3 "/"
Solution: instead of using the "path" package to join the "monitoring" path with the console URL use instead the net/url package. Add tests to manifest_test.go to test this behaviour.

OCPBUGS-4181: Fixes externalURL field for Prometheus and Alertmanager

---

pkg/manifests/manifests.go

Issue: https://issues.redhat.com/browse/OCPBUGS-4168
Problem: recently we have seen a couple of customers complaining that some startup probes are timing out due to the WAL replay that Prometheus has to perform once rebooted.
Solution: to avoid this we are doubling the startup probe, with this commit Prometheus should now have up to 30 minutes to boot

OCPBUGS-4168: Increase startupProbe for prometheus

---

assets/kube-state-metrics/deployment.yaml
jsonnet/components/kube-state-metrics.libsonnet

The `--metric-labels-allowlist` command-line argument contained the `poddisruptionbudget[*]` string which was introduced to support older versions of kube-state-metrics.
With https://github.com/kubernetes/kube-state-metrics/pull/1826, kube-state-metrics will now refuse to start if the allow-list contains an invalid resource name.

Remove deprecated option from kube-state-metrics args

---

CHANGELOG.md
assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

This PR adds alert `KubePodNotScheduled` to group `openshift-kubernetes.rules`. 
To fix the bug [OCPBUGS-2260](https://issues.redhat.com/browse/OCPBUGS-2260) we have patched the alert `KubePodNotReady` already in PR #1816 , excludingthe not schedulable pods from that alert. 
To complete the alerting on unschedulable pods, we add this new alert  `KubePodNotScheduled`. 
We have also submitted [a PR to upstream](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/801). When it is under review, we can start using this alert in CMO in conjunction with the [patched version](https://github.com/openshift/cluster-monitoring-operator/pull/1816/files#diff-9425bc6534201e7b9f2c51476ae71ce5e7c9a353c12c58ec44008c7f12d0171fR190-R204) of alert `KubePodNotReady`.

OCPBUGS-2260: add alert KubePodNotScheduled to group openshift-kubernetes.rules

---

go.mod

Commit 70af87f25 makes use of url.JoinPath that available only in 1.19, hence switching to 1.19

go.mod: switch to go 1.19

---

CHANGELOG.md
go.mod
pkg/client/status_reporter.go
pkg/operator/operator.go
test/e2e/config_test.go
test/e2e/framework/assertions.go

Previously, when PVC is not configured for Prometheus, the CO monitoring status message for Degraded condition included a link to the documentation on configuring monitoring stack for version 4.8.
This commit fixes the link to point to doc for the current cluster version and in case of failure to compute, the cluster-version, points to the latest documentation.
JIRA: https://issues.redhat.com/browse/OCPBUGS-2141

OCPBUGS-2141: compute doc link in PVC not configured message

---

assets/admission-webhook/deployment.yaml
assets/control-plane/prometheus-rule.yaml
assets/kube-state-metrics/cluster-role.yaml
assets/node-exporter/daemonset.yaml
jsonnet/components/admission-webhook.libsonnet
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
jsonnet/main.jsonnet
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_02-role.yaml

This PR upins jsonnet dependencies and update them to latest version.
The new version of admission-webhook library requires input of a secret name for its TLS certificate. So there is a modification on `admission-webhook.libsonnet`.

Unpin and update jsonnet dependencies

---

CHANGELOG.md
assets/node-exporter/daemonset.yaml
jsonnet/main.jsonnet

Network interfaces named "enP.*" are virtual network interfaces on Azure cluster. We will ignore them in Node Exporter.

OCPBUGS-2729: Node Exporter ignore virtual network device 'enP.*'.

---

manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml

I noticed that when CMO restarts after all monitoring components are deployed, the event recorder would use the alertmanager-main statefulset  as the object's reference in events.
For https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-upgrade/1597573931009576960, the Loki interface shows:
`I1129 14:54:21.444741       1 event.go:285] Event(v1.ObjectReference{Kind:"StatefulSet", Namespace:"openshift-monitoring", Name:"alertmanager-main", UID:"ad2a25b2-338c-4ebb-b0b4-52f5e5eb1096", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'ServiceAccountUpdated' Updated ServiceAccount/prometheus-operator -n openshift-monitoring because it changed`

OCPBUGS-4793: fix object reference in Kubernetes events

---

assets/node-exporter/prometheus-rule.yaml
jsonnet/main.jsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

This avoids sending file system related alerts for this mount point. More specifically this avoids any full alerts for this always full file system.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2114515

Bug 2114515: jsonnet: ignore `/var/lib/ibmc-s3fs/` mountpoints

---

pkg/client/client.go

OCPBUGS-5089: pkg/client: Fix nodeReadyCount filter

---

pkg/client/client.go

Currently the CMO degrades when it is not able to
rollout daemonset pod on a node that is not ready. This blocks the upgrade when a node is unavailable. This commit is to fix that by comparing number of
unavailable daemonset pods and maximum unavailable daemonset pods allowed.
Fixes #OCPBUGS-1998

OCPBUGS-1998: pkg/client: Update daemonset degrade condition

---

assets/prometheus-k8s/telemetry-secret.yaml
jsonnet/components/prometheus.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/prometheus.go
test/e2e/framework/client.go
test/e2e/main_test.go
test/e2e/prometheus_test.go
test/e2e/telemeter_test.go
test/e2e/user_workload_monitoring_test.go

MON-2807: Use bearer token file for remote write authentication with telemeter

---

CHANGELOG.md
assets/prometheus-k8s/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

Issue: https://issues.redhat.com/browse/OCPBUGS-4219
Problem: PrometheusRuleFailures didn't have a runbook on how to troubleshoot the alert
Solution: Create that runbook and add a link to the alert

OCPBUGS-4219: Adds runbook link to PrometheusRuleFailures

---

test/e2e/alertmanager_test.go
test/e2e/framework/framework.go
test/e2e/main_test.go
test/e2e/prometheusadapter_test.go
test/e2e/thanos_querier_test.go

This change adds an end-to-end test that triggers a rotation of the TLS certificate used by prometheus-k8s pods to authenticate against targets. The rotation is simulated by deleting the existing secret.

OCPBUGS-4521: check that all targets are up after certificate recreation

---

assets/grafana/config.yaml
assets/grafana/deployment.yaml
jsonnet/main.jsonnet

OCPBUGS-5864: grafana: add the Content-Security-Policy header to requests

---

CHANGELOG.md
jsonnet/components/dashboards.libsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Dashboards showing CPU / memory usage used to stack the limit markers such as limit/request/quota over other metrics create confusion for users reading the diagrams. So we unstack all metrics in the charts containing these limit markers. 
This is the result of unstacking metrics:
This is what it looks like when stacking metrics:

OCPBUGS-5353: unstack dashboards with limit markers.

---

assets/node-exporter/daemonset.yaml
jsonnet/components/node-exporter.libsonnet
jsonnet/main.jsonnet

This PR corrects a bug that in Node Exporter the list of ignored network devices for netdev collector and netclass collector is not the same. 
It complete the bugfixs for  [OCPBUGS-2729](https://issues.redhat.com/browse/OCPBUGS-2729) and [OCPBUGS-1321](https://issues.redhat.com/browse/OCPBUGS-1321).

OCPBUGS-2729: unify ignored network device list of Node Exporter.

---

cmd/operator/main.go
pkg/metrics/server.go

When running CMO locally, the KUBECONFIG file needs to be provided to the HTTP metrics server otherwise the initialization fails.

Fix 'make run-local' target

---

CHANGELOG.md
Documentation/api.md
Documentation/openshiftdocs/modules/alertmanagermainconfig.adoc
pkg/client/client.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
pkg/tasks/alertmanager.go

Related-to #[MON-2798](https://issues.redhat.com//browse/MON-2798)

MON-2959: Allow configuring secrets in alertmanager (platform)

---

CHANGELOG.md
Documentation/api.md
Documentation/openshiftdocs/index.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorconfig.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorcpufreqconfig.adoc
Documentation/openshiftdocs/modules/nodeexportercollectortcpstatconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
test/e2e/node_exporter_test.go

This PR follows https://github.com/openshift/cluster-monitoring-operator/pull/1855
Adding enablement flag for tcpstat collector of Node Exporter. 
https://issues.redhat.com/browse/MON-2902
This PR is the base to https://github.com/openshift/cluster-monitoring-operator/pull/1888

[MON-2902] Add nodeExporter.collectors.tcpstat settings.

---

CHANGELOG.md
Documentation/api.md
Documentation/openshiftdocs/index.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorconfig.adoc
Documentation/openshiftdocs/modules/nodeexportercollectornetdevconfig.adoc
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
test/e2e/framework/client.go
test/e2e/node_exporter_test.go

This PR is based on top of https://github.com/openshift/cluster-monitoring-operator/pull/1876 .
Unhold https://github.com/openshift/cluster-monitoring-operator/pull/1893 after this PR is merged.

MON-2901: add nodeExporter.collectors.netdev settings.

---

pkg/client/client.go
pkg/tasks/controlplane.go
pkg/tasks/prometheusadapter.go

The Prometheus adapter and control plane tasks would exit immediately if they couldn't find the TLS secrets generated by the service CA operator.
With this change, the tasks are waiting up to 5 minutes for the secrets to appear which should speed up a bit the reconciliation (no need to run another attempt).

OCPBUGS-7391: wait for service CA secrets

---

CHANGELOG.md
jsonnet/components/cluster-monitoring-operator.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/client/client.go
pkg/operator/operator.go
pkg/tasks/alertmanager.go
pkg/tasks/configsharing.go
pkg/tasks/prometheus.go
pkg/tasks/prometheus_user_workload.go
pkg/tasks/thanos_querier.go
pkg/tasks/thanos_ruler_user_workload.go

MON-2951: create Routes only with ingress operator

---

CHANGELOG.md
Documentation/api.md
Documentation/openshiftdocs/index.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorconfig.adoc
Documentation/openshiftdocs/modules/nodeexportercollectornetclassconfig.adoc
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
test/e2e/node_exporter_test.go

This PR adds toggle for netclass collector, based on [PR#1888](https://github.com/openshift/cluster-monitoring-operator/pull/1888). It should be merged after [PR#1888](https://github.com/openshift/cluster-monitoring-operator/pull/1888).

MON-2900: add nodeExporter.collectors.netclass settings.

---

CHANGELOG.md
Documentation/api.md
Documentation/openshiftdocs/modules/nodeexportercollectornetclassconfig.adoc
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

This PR follows https://github.com/openshift/cluster-monitoring-operator/pull/1893 . It should be merged after that one.

MON-2895: toggle netlink implementation of netclass collector

---

CHANGELOG.md
Documentation/api.md
Documentation/openshiftdocs/index.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorbuddyinfoconfig.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
test/e2e/node_exporter_test.go

This PR adds nodeExporter.collectors.buddyinfo settings, based on https://github.com/openshift/cluster-monitoring-operator/pull/1876 We should merge that before this one.

MON-2904: add nodeExporter.collectors.buddyinfo settings.

---

pkg/manifests/manifests.go
test/e2e/alertmanager_test.go
test/e2e/validators.go

Related-to #[MON-2959](https://issues.redhat.com//browse/MON-2959)
This is followup PR of #1882 to add e2e test

MON-2959: test/e2e: Add test for alertmanager secret platform

---

test/e2e/alertmanager_test.go

Related-to #[MON-2973](https://issues.redhat.com//browse/MON-2973)
This cleanup of secret was missed in https://github.com/openshift/cluster-monitoring-operator/pull/1884 hence adding it here

MON-2973: test/e2e: Add cleanup func for alertmanager uwm secret test

---

assets/node-exporter/daemonset.yaml
jsonnet/main.jsonnet

This PR resolves https://issues.redhat.com/browse/OCPBUGS-7282 .
The issue is similar to https://issues.redhat.com/browse/OCPBUGS-2729 .

OCPBUGS-7282: Node Exporter ignores network interface under name "cali[a-f0-9]*"

---

assets/node-exporter/daemonset.yaml
jsonnet/components/node-exporter.libsonnet

The diskstats collector in node exporter looks for the directory `/run/udev/data`. The correct path should be `/host/root/run/udev/data` in node exporter daemon set.

OCPBUGS-2439: set the argument path.udev.data in node exporter

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/node_exporter_test.go

This is the fix to the bug found by @juzhao  in https://github.com/openshift/cluster-monitoring-operator/pull/1905#issuecomment-1451186414

OCPBUGS-8215: bugfix in Node Exporter argument setting

---

assets/prometheus-adapter/deployment.yaml
jsonnet/jsonnetfile.lock.json

The startup probe prevents that kubelet kills the prometheus-adapter pod on clusters with many CRDs and/or slow API because it might take some time for prometheus-adapter to discover the available API resources and the /livez endpoint only becomes available once this discovery phase is completed.
The startup probe will wait 3m30s before failing which should be enough even in most unfavorable cases.

OCPBUGS-7694: add startup probe for prometheus-adapter

---

assets/prometheus-user-workload/prometheus.yaml
jsonnet/components/prometheus-user-workload.libsonnet

https://github.com/openshift/cluster-monitoring-operator/pull/1824 increased the
startupProbe timeout from 15m to 1h for both platform and uwm
proemetheus. But it didn't take effect on UWM prometheus
because in assets file it didn't have a container named `prometheus`
on UWM prometheus pod so CMO never entered the code path
that was added in https://github.com/openshift/cluster-monitoring-operator/pull/1824
since it uses strategic merge patch.
Hence this commit adds a `prometheus` container in
uwm prometheus jsonnet file so it gets added
in assets file.
Fixes #OCPBUGS-10690

OCPBUGS-10690: jsonnet: Add prometheus container in UWM

---

hack/build-jsonnet.sh

Speedup jsonnet generation by running in parallel

---

assets/prometheus-adapter/deployment.yaml
jsonnet/components/prometheus-adapter.libsonnet

This is the backport of commit 90585d11.

OCPBUGS-10895: add startup probe for prometheus-adapter

---

CHANGELOG.md
assets/node-exporter/daemonset.yaml
jsonnet/components/node-exporter.libsonnet

[Profiling](https://pprof.me/9802ad7/) shows that node-exporter is using ~16% of CPU time on updating btrfs details. This FS is not included in RHEL kernels, so it can be safely disabled

OCPBUGS-11434: node-exporter: disable btrfs collector

---

jsonnet/components/prometheus-user-workload.libsonnet

jsonnet: add comment why empty prometheus container needed

---

test/e2e/telemeter_test.go

This test adds a lot of flakiness. Assuming 0 failed samples is too strict for determining that remote write is working. This commit removes the check for failed samples so that we consider telemetry via remote write successful as long as some samples are send.

OCPBUGS-14007: test/e2e: don't fail on telemeter remote write failed samples

---

test/e2e/prometheus_test.go

OCPBUGS-13939: Extend remote write test timeout

---

pkg/tasks/prometheus.go
pkg/tasks/prometheus_user_workload.go
pkg/tasks/thanos_ruler_user_workload.go

This PR fixes golangci-lint ineffassign violations as per the new
Makefile option.

OCPBUGS-14376: Fix golangci-lint ineffassign violations

---

pkg/manifests/manifests.go

This commit fixes all wastedassign violations as per the new
golangci-int makefile target.

OCPBUGS-14377: Fix golangci-int wastedassign violations

---

pkg/client/client.go
pkg/manifests/config.go
pkg/promqlgen/promqlgen.go
pkg/tasks/alertmanager.go
pkg/tasks/alertmanager_user_workload.go
pkg/tasks/prometheus.go
pkg/tasks/prometheus_validation.go

This PR fixes whitespace violations as per the new makefile target for
golangci-lint.

OCPBUGS-14380: Fix golangcilint whitespace violations

---

pkg/manifests/errmapreader.go
pkg/manifests/manifests.go

This PR fixes all violations as per the new golangci-lint misspell
target.

OCPBUGS-14371: Fix golangci-lint misspell violations

---

cmd/operator/main.go

This commit skips the warning of unbuffered os.Signal channel due to its explicitly wanted use
as per to do graceful shutdown.

OCPBUGS-14379: Skip specific govet violation on operator main.go

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet
test/rules/cluster_capacity_cpu.yaml
test/rules/node_role.yaml

As stated in [OCPBUGS-10387](https://issues.redhat.com/browse/OCPBUGS-10387), certain clusters do not label their infra nodes in the metric `cluster:capacity_cpu_cores:sum`, due to lack of label `label_node_role_kubernetes_io="infra"` in the metric `kube_node_labels`.
This PR add logic to automatically add a label  `label_node_role_kubernetes_io="infra"` to infra nodes when generating the metric `metric cluster:capacity_cpu_cores:sum`.
This PR is based on the PR https://github.com/openshift/cluster-monitoring-operator/pull/1926 that adds unit tests for the current recording rule of  `cluster:capacity_cpu_cores:sum`.

OCPBUGS-10387: label for infra nodes for metric cluster:capacity_cpu_cores:sum

---

Makefile
assets/alertmanager-user-workload/alertmanager.yaml
assets/alertmanager/alertmanager.yaml
assets/kube-state-metrics/deployment.yaml
assets/node-exporter/daemonset.yaml
assets/openshift-state-metrics/deployment.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/telemeter-client/deployment.yaml
assets/thanos-querier/cluster-role-binding.yaml
assets/thanos-querier/cluster-role.yaml
assets/thanos-querier/deployment.yaml
assets/thanos-querier/grpc-tls-secret.yaml
assets/thanos-querier/kube-rbac-proxy-rules-secret.yaml
assets/thanos-querier/kube-rbac-proxy-secret.yaml
assets/thanos-querier/oauth-cookie-secret.yaml
assets/thanos-querier/pod-disruption-budget.yaml
assets/thanos-querier/prometheus-rule.yaml
assets/thanos-querier/route.yaml
assets/thanos-querier/service-account.yaml
assets/thanos-querier/service-monitor.yaml
assets/thanos-querier/service.yaml
assets/thanos-ruler/service-account.yaml
assets/thanos-ruler/service-monitor.yaml
assets/thanos-ruler/service.yaml
assets/thanos-ruler/thanos-ruler.yaml
hack/generate-versions.sh
jsonnet/versions.yaml

…implify.
Make hack/generate-versions.sh do nothing on PR that are not against the main branch as the components versions are only updated on the main branch (on release-xx branches, components kepp their versions when fixed)
Add a 'make check-versions' target to run the versions check. CI jobs will be updated to use this.

OCPBUGS-14561: Prevent ci/prow/versions from failing on PR against release-xxx

---

pkg/manifests/config.go
pkg/manifests/manifests.go

This PR fixes gosimple violations as per the new makefile target for
golangci-lint.

OCPBUGS-14375: Fix golangci-lint gosimple violations

---

cmd/operator/main.go
pkg/tasks/prometheus.go

This PR removes remaining static check violations in the CMO that
showed up after fixing all the other issues.

OCPBUGS-14606: Remove remaining staticcheck violations

---

CHANGELOG.md
Documentation/api.md
Documentation/openshiftdocs/modules/thanosquerierconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
test/e2e/config_test.go

OCPBUGS-11889: disable CORS headers on Thanos querier

---

test/e2e/alertmanager_test.go

`TestAlertmanagerUWMSecrets` is one the of test that times out see https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/1971/pull-ci-openshift-cluster-monitoring-operator-master-e2e-agnostic-operator/1661649123104788480.  This change is attempt to increase poll wait time for alertmanager to come up since it looks to be taking more time in UWM

OCPBUGS-14072: test: increase poll wait time for alertmanager

---

CHANGELOG.md
CONTRIBUTING.md
Makefile
hack/tools/go.mod
hack/tools/go.sum
hack/tools/tools.go

This PR adds a new misspell target in makefile to sort out common
misspells in markdown files. It explicitly ignores some autogenerated files.

OCPBUGS-14816: Add misspell target in Makefile

---

Documentation/data-collection.md
manifests/0000_50_cluster-monitoring-operator_04-config.yaml

This is a follow-up on #1910 to fix some typos @juzhao mentioned in the 4.13 backport https://github.com/openshift/cluster-monitoring-operator/pull/1976#pullrequestreview-1468917977, so that master and 4.13 are aligned here.
The backport will contain these changes already.

OCPBUGS-12903: Fix console metrics doc typo

---

go.mod
test/e2e/prometheus_test.go
vendor/github.com/prometheus/prometheus/discovery/kubernetes/client_metrics.go
vendor/github.com/prometheus/prometheus/discovery/kubernetes/endpoints.go
vendor/github.com/prometheus/prometheus/discovery/kubernetes/endpointslice.go
vendor/github.com/prometheus/prometheus/discovery/kubernetes/endpointslice_adaptor.go
vendor/github.com/prometheus/prometheus/discovery/kubernetes/ingress.go
vendor/github.com/prometheus/prometheus/discovery/kubernetes/ingress_adaptor.go
vendor/github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go
vendor/github.com/prometheus/prometheus/discovery/kubernetes/node.go
vendor/github.com/prometheus/prometheus/discovery/kubernetes/pod.go
vendor/github.com/prometheus/prometheus/discovery/kubernetes/service.go
vendor/k8s.io/apimachinery/pkg/util/version/doc.go
vendor/k8s.io/apimachinery/pkg/util/version/version.go
vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp_stub.go
vendor/modules.txt

TestBodySizeLimit checks Prometheus config file instead of the metric "prometheus_target_scrapes_exceeded_body_size_limit_total".
The package "github.com/prometheus/prometheus/discovery/kubernetes" is added to `vendor/` to parse the field `kubernetes_sd_configs` in the config file.

OCPBUGS-14123: make TestBodySizeLimit less flaky

---

assets/prometheus-user-workload/trusted-ca-bundle.yaml
jsonnet/components/prometheus-user-workload.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/helpers.go
pkg/tasks/prometheus_user_workload.go

Add the trusted CA bundle in UWM Prometheus pods, so users can secure
the remote-write endpoint, in response to [OCPBUGS-11958](https://issues.redhat.com/browse/OCPBUGS-11958).

OCPBUGS-11958: Add the trusted CA bundle in UWM Prometheus pods

---

assets/prometheus-k8s/kube-rbac-proxy-secret.yaml
assets/prometheus-k8s/prometheus.yaml
jsonnet/components/prometheus.libsonnet
jsonnet/utils/generate-secret.libsonnet
test/e2e/telemeter_test.go

When the control plane nodes are under pressure or the apiserver is just not available, no telemetry data is emitted by the monitoring stack 
Remove the dependency on the apiserver would be to use mTLS communication between telemeter-client and the Prometheus pods.
Add /federate endpoint to rbac proxy and allow telemeter-client to authenticate via mTLS to reach Prometheus metrics.
Add mTLS auth to telemeter-client https://github.com/openshift/telemeter/pull/455

MON-3229: Remove the dependency on the apiserver auth

---

test/e2e/alertmanager_test.go
test/e2e/config_test.go
test/e2e/framework/helpers.go
test/e2e/image_registry_test.go
test/e2e/node_exporter_test.go
test/e2e/prometheus_test.go
test/e2e/prometheusadapter_test.go
test/e2e/telemeter_test.go
test/e2e/thanos_ruler_test.go
test/e2e/user_workload_monitoring_test.go
test/e2e/uwm_helpers.go

test/e2e: validate CMO and UWM configs

---

.gitignore
Makefile
hack/local-cmo.sh

This PR refines the local-cmo.sh script by implementing the
following improvements:
- By default, the script now authenticates as the CMO service account
(see tmp/cmo-kubeconfig) before launching the operator. To maintain
the previous behavior, a --no-cmo-login option is provided.
- Instead of utilizing the compiled binary, the script now uses "go
run cmd/operator" to execute the operator. This change enables
automatic integration of source code modifications upon script reruns.
- Introduces a --dry-run flag, allowing the script to simulate
operations without applying any modifications to the cluster.
These enhancements optimize the execution and flexibility of the
local-cmo.sh script for smoother operator management.
signed-by: sthaha@redhat.com

MON-3253: refactor local-cmo.sh to use CMO SA by default

---

assets/node-exporter/daemonset.yaml
jsonnet/components/node-exporter.libsonnet

OCPBUGS-13153: Limit the value of GOMAXPROCS on node-exporter.

---

assets/telemeter-client/deployment.yaml
assets/telemeter-client/service.yaml
jsonnet/jsonnetfile.lock.json

Update telemeter-client deployment to work with new feature TLS.
Update telemeter branch to get updated json
Generate new jsonnetfile with new branch
Make generate to update deployment.yaml
Depends on:
https://github.com/openshift/cluster-monitoring-operator/pull/1904 
https://github.com/openshift/telemeter/pull/455

MON-3249: Update telemeter-client to allow TLS through rbac proxy

---

jsonnet/components/cluster-monitoring-operator.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/client/client.go
pkg/operator/operator.go
pkg/tasks/monitoring_plugin.go

This PR fixes the failure to upgrade from OpenShift version 4.13 to 4.14 in environments (such as telco) where `console` ClusterOperator is disabled. The upgrade fails happens when CMO executes the console-plugin task which fails due to missing ConsolePlugin.
The fix checks for the presence of `console` ClusterOperator and bails out (with a log message) if it is absent.

OCPBUGS-14922: skip console-plugin installation if console CO is absent

---

pkg/manifests/manifests.go
test/e2e/config_test.go

The console-plugin's deployment configs that need to applied to the deployment.spec.template.spec weren't getting applied because the changes were made to the copy of the object instead of the original object itself. The tests didn't catch the issue because the pod assertions didn't validate if any pods were found for the combination of namespace and label-selector
This commit fixes both by refering (pointer) to the original spec instead of the copy and by fixing the assertions fail if it fails to find any pods.

OCPBUGS-15440: fix CMO to apply console-plugin pod.spec config

---

assets/node-exporter/daemonset.yaml
jsonnet/components/node-exporter.libsonnet

On nodes with multiple CPU cores, this should help avoid lock contentions without having any side effects, see the ticket for more details.
node-exporter versions that have "--runtime.gomaxprocs" can still override this: the flag has precedence over this automatic setting.
Make the entrypoint set the env var before runnning the process. Get the CPU count from /proc/cpuinfo without taking CPU affinity (via cpuset) into account as the container's CPU requests is not an integer, thus no affinity is applied.

OCPBUGS-15469: Limit the value of GOMAXPROCS on node-exporter to 4.

---

assets/node-exporter/daemonset.yaml
jsonnet/components/node-exporter.libsonnet

On nodes with multiple CPU cores, this should help avoid lock contentions without having any side effects, see the ticket for more details.
node-exporter versions that have "--runtime.gomaxprocs" can still override this: the flag has precedence over this automatic setting.
Make the entrypoint set the env var before runnning the process. Get the CPU count from /proc/cpuinfo without taking CPU affinity (via cpuset) into account as the container's CPU requests is not an integer, thus no affinity is applied.

OCPBUGS-15473: Limit the value of GOMAXPROCS on node-exporter to 4

---

Documentation/api.md
Documentation/openshiftdocs/index.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorconfig.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorprocessesconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
test/e2e/node_exporter_test.go

This PR is similar to #1931 , adding an on/off switch to `processes` collector.

MON-3269: add nodeExporter.collectors.processes settings.

---

Documentation/api.md
Documentation/openshiftdocs/modules/thanosquerierconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Give users a TopologySpreadConstraints field in the ThanosQuerier field and propagate this to the pod that is created.

MON-3181: Expose and propagate TopologySpreadConstraints for thanos-querier

---

Documentation/api.md
Documentation/openshiftdocs/modules/prometheusrestrictedconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Give users a TopologySpreadConstraints field in the PrometheusRestrictedConfig field and propagate this to the pod that is created.

MON-3183: Expose and propagate TopologySpreadConstraints for UWM prometheus

---

Documentation/api.md
Documentation/openshiftdocs/modules/telemeterclientconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Give users a TopologySpreadConstraints field in the TelemeterClientConfig field and propagate this to the pod that is created.

MON-3180: Expose and propagate TopologySpreadConstraints for telemeter-client

---

Documentation/api.md
Documentation/openshiftdocs/modules/alertmanageruserworkloadconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Give users a TopologySpreadConstraints field in the AlertmanagerUserWorkloadConfig field and propagate this to the pod that is created.

MON-3182: Expose and propagate TopologySpreadConstraints for UWM alertmanager 

---

Documentation/api.md
Documentation/openshiftdocs/modules/k8sprometheusadapter.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Give users a TopologySpreadConstraints field in the K8sPrometheusAdapter field and propagate this to the pod that is created.

MON-3176: Expose and propagate TopologySpreadConstraints for prometheus-adapter

---

Documentation/api.md
Documentation/openshiftdocs/modules/openshiftstatemetricsconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Give users a TopologySpreadConstraints field in the openshiftStateMetrics field and propagate this to the pod that is created.

MON-3179: Expose and propagate TopologySpreadConstraints for openshift state metrics

---

Documentation/api.md
Documentation/openshiftdocs/index.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorconfig.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorsystemdconfig.adoc
assets/node-exporter/daemonset.yaml
jsonnet/components/node-exporter.libsonnet
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
test/e2e/node_exporter_test.go

This PR is held for the moment, systems collector requires more settings, it will come together later in this PR.
This PR is based on top of https://github.com/openshift/cluster-monitoring-operator/pull/1876 , we should merge that before this one.

MON-2903: add nodeExporter.collectors.systemd settings.

---

Documentation/api.md
Documentation/openshiftdocs/modules/prometheusoperatorconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Give users a TopologySpreadConstraints field in the prometheus-operator field and propagate this to the pod that is created.

MON-3178: Expose and propagate TopologySpreadConstraints for prometheus-operator

---

Documentation/api.md
Documentation/openshiftdocs/modules/kubestatemetricsconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Give users a TopologySpreadConstraints field in the kubeStateMetrcisConfig field and propagate this to the pod that is created.

MON-3177: Expose and propagate TopologySpreadConstraints for kube state metrics

---

CHANGELOG.md
assets/control-plane/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

Quota alerts should not be defined for system namespaces.

OCPBUGS-10699: remove Kube*QuotaOvercommit alerts

---

assets/prometheus-user-workload/trusted-ca-bundle.yaml
jsonnet/components/prometheus-user-workload.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/helpers.go
pkg/tasks/prometheus_user_workload.go

Add the trusted CA bundle in UWM Prometheus pods, so users can secure
the remote-write endpoint, in response to [OCPBUGS-11958](https://issues.redhat.com/browse/OCPBUGS-11958).
***
_This is the 4.12 backport of #1970._

[release-4.12] OCPBUGS-16028: Add the trusted CA bundle in UWM Prometheus pods

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Part of https://github.com/openshift/enhancements/pull/1298

OCPBUGS-17125: backport metrics collection profiles selector logic to prevent users from double scraping when they upgrade from 4.12 to 4.13

---

assets/control-plane/prometheus-rule.yaml
assets/kube-state-metrics/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

The following alerting rules were missing a namespace label:
* KubeStateMetricsListErrors
* KubeStateMetricsWatchErrors
* KubeletPlegDurationHigh
* KubeletTooManyPods
* KubeNodeReadinessFlapping
* KubeletPodStartUpLatencyHigh

OCPBUGS-17191: add namespace label to alerting rules

---

assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
jsonnet/components/prometheus-operator-user-workload.libsonnet
jsonnet/components/prometheus-operator.libsonnet
jsonnet/utils/add-labels.libsonnet

The option --labels was set to the prometheus-operator in https://github.com/openshift/cluster-monitoring-operator/pull/1986
to make it add the label "app.kubernetes.io/part-of: openshift-monitoring" to resources it creates.
prometheus-operator adds the labels to some controllers matchLabels as well (to the prometheus statefulset e.g.)
which makes the prometheus-operator recreate the statefulset as matchLabels is an immutable field.
Recreating the statefulset leads to downtime as the prometheus-operator run the deletion in a foreground mode, check
https://github.com/prometheus-operator/prometheus-operator/issues/3875 for the whys.
We consider that adding the ownership labels is not worth the downtime, and we'll be thinking of a way to avoid it.
Of course, this will lead to the recreation …

OCPBUGS-17346: Avoid recreating some resources, created by prometheus-operator, during 4.13->4.14 upgrade

---

Documentation/api.md
Documentation/openshiftdocs/modules/thanosrulerconfig.adoc
pkg/manifests/types.go

OCPBUGS-17487: fix typo for ThanosRulerConfig.Resources

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

The alert `MultipleContainersOOMKilled` is removed. 
The metric `container_runtime_crio_containers_oom_total` is available in OCP now.
Moreover, the alert  `MultipleContainersOOMKilled` is almost always accompanied by the alert `SystemMemoryExceedsReservation` of warning level from [MachineConfigOperator](https://github.com/openshift/machine-config-operator/blob/4048c667b54967ecd62b1e2bed886b4f54b78732/install/0000_90_machine-config-operator_01_prometheus-rules.yaml#L91).

MON-988: remove alert "MultipleContainersOOMKilled"

---

assets/prometheus-k8s/kube-rbac-proxy-secret.yaml
jsonnet/components/prometheus.libsonnet

After change oauth proxy to rbac proxy https://github.com/openshift/cluster-monitoring-operator/pull/2005
When mTLS does not work and auth from telemeter-client and prometheus is done via token, telemter-client SA needs to be allowed.

Add telemeter client SA to rbac proxy

---

test/e2e/alerting_rule_test.go

MON-2641: Add e2e tests for AlertingRule controller

---

README.md
assets/prometheus-adapter/deployment.yaml
jsonnet/main.jsonnet

OCPBUGS-17691: replace outdated repository link

---

assets/prometheus-adapter/deployment.yaml
jsonnet/components/prometheus-adapter.libsonnet

The `--logtostderr` argument has been deprecated in prometheus-adapter v0.10.0 and removed in v0.11.0.

OCPBUGS-17690: remove deprecated argument

---

CHANGELOG.md
Documentation/api.md
Documentation/openshiftdocs/index.adoc
Documentation/openshiftdocs/modules/clustermonitoringconfiguration.adoc
Documentation/openshiftdocs/modules/k8sprometheusadapter.adoc
Documentation/openshiftdocs/modules/kubestatemetricsconfig.adoc
Documentation/openshiftdocs/modules/nodeexporterconfig.adoc
Documentation/openshiftdocs/modules/openshiftstatemetricsconfig.adoc
Documentation/openshiftdocs/modules/prometheusoperatoradmissionwebhookconfig.adoc
Documentation/openshiftdocs/modules/prometheusoperatorconfig.adoc
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

MON-3304: Add option to specify resource limits for all components

---

examples/alert-relabel-config.yaml
examples/alerting-rule.yaml
test/e2e/alert_relabel_config_test.go
test/e2e/framework/prometheus.go
test/e2e/prometheus_test.go

Check on Prometheus config secret instead of relabelConfig secret to test more things/parts.

MON-2642: Improve e2e tests for alertrelabelconfigs CRD

---

Documentation/api.md
Documentation/openshiftdocs/modules/prometheusoperatoradmissionwebhookconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Add Topology spread constrains admission webhook
Add tests

OCPBUGS-19356: Topology spread constraints admission webhook

---

assets/alertmanager-user-workload/alertmanager.yaml
assets/alertmanager/alertmanager.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/thanos-querier/deployment.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/components/alertmanager-user-workload.libsonnet
jsonnet/components/alertmanager.libsonnet
jsonnet/components/prometheus-operator.libsonnet
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet
jsonnet/components/thanos-querier.libsonnet
jsonnet/components/thanos-ruler.libsonnet

MON-3376: Remove deprecated --logtostderr argument

---

assets/monitoring-plugin/config-map.yaml
jsonnet/components/monitoring-plugin.libsonnet

This commit modifies the monitoring-plugin configmap so nginx listens on
both ipv4 and ipv6 addresses. The nginx image used supported ipv6 but it
wasn't enabled on the endpoint config.

OCPBUGS-19059: Enable ipv6 on monitoring-plugin nginx

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

The apiserver_storage_objects metric can take -1 values when there are
communication issues between the kube-apiserver and etcd. In such case,
the kube-apiserver can't get objects count from etcd and as such exposes
a metric value denoting the issue. However, this is polluting the data
exported to telemetry so they should be skipped. Doing that will not
cause the lose of the etcd issue information since we have alerts that
would trigger in such scenarios.

OCPBUGS-18390: jsonnet/rules: exclude -1 from etcd objects count

---

pkg/alert/rule_controller.go
pkg/manifests/manifests.go

This commit replaces md5 usage for sha256 as a method for cryptographic
primitive and replaces it for sha256.

MON-3383: Remove weak cryptograhic primitive usage

---

assets/thanos-ruler/thanos-ruler.yaml
jsonnet/components/thanos-ruler.libsonnet

The `.spec.version` field is used by the operator to adapt the statefulset configuration depending on which features are supported or not.
In practice, it shouldn't induce any change in functionality but it's always better to be explicit.

Set Thanos version in the Thanos Ruler spec

---

manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml

OLM is an optional operator, we exclude OLM resources with this annotation if the monitoring operator ever becomes a capability, using a <monitoring_label>+OperatorLifecycleManager will work for both
/hold
Wait for https://github.com/openshift/api/pull/1589 to be merged in

OCPVE-711: feat: add olm capability annotation

---

hack/generate-versions.sh
jsonnet/versions.yaml
manifests/image-references

Since ART build is completed inorder to get
included in payload it needs to be referred in
image-references.

MON-3270: Add kube-metrics-server to image-references

---

manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml

This reverts commit 31b1b1d53f4e538ea63f323a90def9c90fe626e3.
Mistaken timing on my part, will need to re-add change after CVO change is in https://github.com/openshift/cluster-version-operator/pull/971

Revert "feat: add olm capability annotation"

---

assets/alertmanager/alertmanager.yaml
assets/alertmanager/service-account.yaml
jsonnet/components/alertmanager.libsonnet

OCPBUGS-11344: alertmanager: use alertmanager CRD's automountServiceAccountToken option

---

assets/prometheus-k8s/prometheus.yaml
jsonnet/components/prometheus.libsonnet

This commit changes kube-rbac-proxy-thanos in order to avoid duplicate
port definition logs messages in prometheus operator.

[OCPBUGS-20221] Change kube-rbac-proxy-thanos port

---

Makefile

we rely on go imports to install our build tooling via hack/tools/go.mod. Some of these imports don't actually import valid modules since `package main` is used in some of them (e.g.
https://github.com/brancz/gojsontoyaml/blob/6ffa820a00533125ad1c3f77d0429e4cac6f7072/main.go#L1). With go1.21 the `list` command will fail on those. Adding `-e` fixes this. I think this flag exists in older go version too, so this should work without being aware of the version.
\cc @simonpasquier

build: add `-e` to `go list` command to install tools

---

pkg/client/client.go
pkg/tasks/controlplane.go

This code was introduced in https://github.com/openshift/cluster-monitoring-operator/pull/2039 to make sure CMO delete some resources it used to deploy for etcd monitoring.

MON-3286: Remove no longer needed code.

---

jsonnet/components/dashboards.libsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Revert PR#2101
As Trevor commented in https://issues.redhat.com/browse/OCPBUGS-18326 , the capability annotation will activate the required capability implicitly on clusters during an update. We should avoid activating capabilities during update.

OCPBUGS-18326: revert previous fix to avoid activating console capability during update

---

pkg/metrics/server.go

Commit b3b011b0 was not enough to prevent HTTP2 connections as demonstrated in https://github.com/kubernetes/kubernetes/issues/121197.
To prevent any risk with HTTP2, this change disables HTTP2 at the server level. There's no expected performance penalty because the web server is only used for scraping metrics.

fix: force HTTP/1.1 connections

---

assets/prometheus-adapter/config-map-dedicated-service-monitors.yaml
assets/prometheus-adapter/config-map.yaml
assets/prometheus-adapter/deployment.yaml
jsonnet/main.jsonnet

The same modification in CMO as https://github.com/openshift/cluster-monitoring-operator/pull/1875 but using the new option in upstream kube-prometheus introduced by [this PR](https://github.com/prometheus-operator/kube-prometheus/pull/2003).

OCPBUGS-4069: Prometheus Adatper takes metrics from kubelet job only.

---

assets/prometheus-adapter/deployment.yaml
jsonnet/components/prometheus-adapter.libsonnet

OCPBUGS-21621: Set the new --disable-http2 flag for prometheus-adapter to disable HTTP2

---

assets/prometheus-adapter/deployment.yaml
jsonnet/components/prometheus-adapter.libsonnet

/hold
needs https://github.com/openshift/k8s-prometheus-adapter/pull/89
/retitle OCPBUGS-21473: Set the new --disable-http2 flag for prometheus-adapter to disable HTTP2

OCPBUGS-21473: Set the new --disable-http2 flag for prometheus-adapter to disable HTTP2

---

assets/thanos-querier/kube-rbac-proxy-secret.yaml
jsonnet/components/thanos-querier.libsonnet
test/e2e/framework/framework.go
test/e2e/user_workload_monitoring_test.go

fix KRP configuration for thanos-querier in order to enforce restricted
access only to entities allowed to [http-verb] for pods.metrics.k8s.io
Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>

OCPBUGS-17035: fix KRP permissions for Thanos Querier

---

assets/control-plane/prometheus-rule.yaml
assets/node-exporter/daemonset.yaml
assets/node-exporter/security-context-constraints.yaml
assets/prometheus-adapter/deployment.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/thanos-querier/deployment.yaml
jsonnet/components/node-exporter.libsonnet
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
jsonnet/main.jsonnet
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

This commit also pins the prometheus-operator jsonnet to the current stable release branch of the operator. The reason is that pinning to the main branch has the drawback of pulling CRD changes which are not yet supported by the downstream operator.
The commit also updates the different jsonnet dependencies to their latest versions.

MON-3479: update Prometheus operator assets to v0.69.1

---

assets/cluster-monitoring-operator/cluster-role-aggregated-metrics-reader.yaml
jsonnet/components/cluster-monitoring-operator.libsonnet
jsonnet/components/prometheus-adapter.libsonnet
jsonnet/main.jsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/clustermonitoringoperator.go
pkg/tasks/prometheusadapter.go

This change came as part of reviewing #2022
To avoid duplicated code in metrics-server
and prometheus-adapter moving this role
to cluster-monitoring-operator.jsonnet
cc: @simonpasquier

MON-3505: move aggregated-metrics-reader role to cmo jsonnet

---

assets/prometheus-adapter/deployment.yaml
jsonnet/components/prometheus-adapter.libsonnet

/hold
needs https://github.com/openshift/k8s-prometheus-adapter/pull/90
/retitle OCPBUGS-21457: Set the new --disable-http2 flag for prometheus-adapter to disable HTTP2

OCPBUGS-21457: Set the new --disable-http2 flag for prometheus-adapter to disable HTTP2

---

hack/local-cmo.sh

After FeatureGate is introduced in #2151, local run doesn't correctly since it cannot get the desired version. This commit pass release-version in cmo run

MON-3511: hack/local-cmo.sh: pass desired version in cmo run command

---

assets/monitoring-plugin/config-map.yaml
assets/monitoring-plugin/deployment.yaml
jsonnet/components/monitoring-plugin.libsonnet

This commit uses the Kube Downward API to get the plugin's pod
status.podIP and bash to set it and run nginx accordingly. This is also
set in the jsonnet so it gets generated, even though it's some kind of
double templating.

OCPBUGS-21610: Change config to allow ipv6/4

---

CHANGELOG.md
Documentation/api.md
Documentation/openshiftdocs/modules/remotewritespec.adoc
pkg/manifests/manifests.go
pkg/manifests/types.go
test/e2e/config_test.go

MON-3500: Enable sending exemplars over RW in UWM

---

assets/monitoring-plugin/config-map.yaml
assets/monitoring-plugin/deployment.yaml
jsonnet/components/monitoring-plugin.libsonnet

This reverts commit 0ee89229f1e2488b5f494ed821cc4ac597bfa9fa.
as it's creating issues with the monitoring UI.
------------------------ >8 ------------------------
> Do not modify or remove the line above.
> Everything below it will be ignored.
This reverts commit 0ee89229f1e2488b5f494ed821cc4ac597bfa9fa.
as it's creating issues with the monitoring UI.

OCPBUGS-21610: revert #2166

---

assets/alertmanager/prometheus-rule.yaml
assets/node-exporter/prometheus-rule.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

OCPBUGS-24323: update prometheus-operator jsonnet to v0.70.0

---

assets/thanos-querier/deployment.yaml
jsonnet/components/thanos-querier.libsonnet

OCPBUGS-24340: patch securityContext for Thanos querier

---

assets/node-exporter/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet
test/rules/NodeClockNotSynchronising.yaml
test/rules/NodeClockSkewDetected.yaml
test/rules/TargetDown.yaml

This commit adapts the upstream NodeClockNotSynchronising and NodeClockSkewDetected rules to be always inactive when the PTP operator is installed. The PTP operator ships a more robust rule to detect unsynchronised clocks and the default rules are redundant in this case.

MON-3544: Adjust NodeClock* alerting rules to work with PTP operator

---

hack/local-cmo.sh

According to the documentation both the existing version and this change should be legal syntax. With this change I can run a local CMO with jq 1.7.
I think regardless fewer pipes make this more readable.

MON-3551: fix: simplify jq script avoids error with jq1.7

---

assets/monitoring-plugin/config-map.yaml
assets/monitoring-plugin/deployment.yaml
jsonnet/components/monitoring-plugin.libsonnet

This PR fixes a typo in monitoring plugin config rendering and
brings back the rendering to ngingx.conf file to detect ipv4/ipv6
socket.

OCPBUGS-21610: Detect ipv4/ipv6 socket in pod ip for nginx conf

---

assets/monitoring-plugin/config-map.yaml
jsonnet/components/monitoring-plugin.libsonnet

OCPBUGS-23516: prevent plugin entry assets from caching

---

assets/prometheus-k8s/prometheus.yaml
jsonnet/components/prometheus.libsonnet

OCPBUGS-24630: additionalArgs: list items must have named fields

---

assets/prometheus-k8s/role-binding-specific-namespaces.yaml
assets/prometheus-k8s/role-specific-namespaces.yaml
assets/prometheus-user-workload/role-binding-specific-namespaces.yaml
assets/prometheus-user-workload/role-specific-namespaces.yaml
go.mod
jsonnet/utils/add-labels.libsonnet
pkg/manifests/assets.go
pkg/manifests/manifests.go
pkg/manifests/tls.go

This PR adds strict yaml unmarshaling to avoid silently dropping fields from our static yaml assets, that are not part of the actual type. The old behaviour as caused two bugs in the 4.15 development cycle.
Additionally I added two refactor commits, which imo improve readability. They can however be easily dropped if there are objections. I recommend reviewing commits individually.

MON-3592: Use strict yaml unmarshaling

---

assets/prometheus-adapter/deployment.yaml
jsonnet/components/prometheus-adapter.libsonnet

/hold
needs https://github.com/openshift/k8s-prometheus-adapter/pull/91
/retitle OCPBUGS-21441: Set the new --disable-http2 flag for prometheus-adapter to disable HTTP2

OCPBUGS-21441: Set the new --disable-http2 flag for prometheus-adapter to disable HTTP2

---

pkg/tasks/alertmanager.go
pkg/tasks/alertmanager_user_workload.go

OCPBUGS-25676: fix(tasks): adjust 'trusted CA bundle ConfigMap' related logs for alertmanagers.

---

assets/alertmanager/secret.yaml
jsonnet/main.jsonnet

OCP doesn't include the InfoInhibitor alerting rule out of the box. To avoid confusion, it is desired to remove the alert from the default Alertmanager configuration.
Note that the change will only apply to newly created clusters because the Cluster Monitoring Operator only handles the creation of the Alertmanager configuration secret and it never updates when the secret already exists.

OCPBUGS-25378: drop InfoInhibitor from default Alertmanager config

---

assets/metrics-server/api-service.yaml
assets/prometheus-adapter/api-service.yaml
jsonnet/components/metrics-server.libsonnet
jsonnet/components/prometheus-adapter.libsonnet
pkg/client/client.go

…dateAPIService to avoid code duplication.
The function also avoids running update queries when nothing needs to change from CMO's side which reduces the probability of conflicts with other controllers and consumes resources for nothing.

OCPBUGS-25849: make PrometheusAdapter and MetricsServer tasks less conflict prone

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/monitoring_plugin.go

This commit ensures that the monitoring plugin's pods get redeployed when the TLS serving certificate is rotated.

OCPBUGS-26983: rollout monitoring plugin on TLS rotation

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet
test/rules/TargetDown.yaml

MON-2853: add runbook link to TargetDown alert

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/metricsserver.go

chore: adjust monitoring plugin cert hash annotation name to avoid confusion.
chore: adjust code for metrics server certs rotation and add test
followup of https://github.com/openshift/cluster-monitoring-operator/pull/2242

OCPBUGS-27289: followup of https://github.com/openshift/cluster-monitoring-operator/pull/2242

---

pkg/manifests/manifests.go

This sets the correct source URL in UWM alert notifications.

OCPBUGS-28246: fix: set externalURL in UWM Prometheus

---

assets/prometheus-k8s/prometheus.yaml
jsonnet/components/prometheus.libsonnet
pkg/manifests/manifests.go

The latest version of the Prometheus CRD allows to customize the overall startup probe duration. This commit makes use of it instead of patching the Prometheus container definition at runtime.

MON-3697: use `maximumStartupDurationSeconds` instead of container patch

---

assets/prometheus-adapter/deployment.yaml
jsonnet/components/prometheus-adapter.libsonnet

/hold
needs https://github.com/openshift/k8s-prometheus-adapter/pull/92
/retitle OCPBUGS-21423: Set the new --disable-http2 flag for prometheus-adapter to disable HTTP2

OCPBUGS-21423: Set the new --disable-http2 flag for prometheus-adapter to disable HTTP2

---

assets/control-plane/minimal-service-monitor-kubelet.yaml
assets/control-plane/service-monitor-kubelet.yaml
jsonnet/components/control-plane.libsonnet
jsonnet/utils/configure-authentication-for-monitors.libsonnet

OCPNODE-2022: jsonnet: update crio port to TLS port 9637

---

jsonnet/components/dashboards.libsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

This commit adds the "capability.openshift.io/name: Console" annotation to the dashboard configmaps.
It also renames the existing configmaps from "grafana-xxx" to "xxx" because otherwise CVO would enable the Console capability on all clusters, even those where the capability was initially disabled [1]. The CVO team has a feature request [2] to improve the situation but for now, we have no other option than creating the configmaps with a different name and deleting the old configmaps (anyway the "grafana-" prefix is misleading since OCP doesn't ship any Grafana instance by default).
[1] https://github.com/openshift/enhancements/blob/master/enhancements/installer/component-selection.md#how-to-implement-a-new-capability
[2] https://issues.redhat.com/browse/OTA-1039

OCPBUGS-18326: add Console cap annotation to dashboards

---

test/e2e/alertmanager_test.go
test/e2e/alertmanager_user_workload_test.go
test/e2e/framework/assertions.go
test/e2e/framework/framework.go
test/e2e/user_workload_monitoring_test.go

It should speed up the test run if we check the condition immediately instead of waiting for 5 seconds.

MON-3706: chore: poll immediately in the e2e tests

---

Documentation/development.md
pkg/client/client.go
pkg/client/client_test.go
pkg/manifests/tls.go
test/e2e/framework/framework.go

See https://docs.google.com/document/d/1fm2SZs8HroexPQnqI0Ua85Y31-lars8gCsdwSJC3ngo/edit?usp=sharing for benchmarks results.

MON-3717: pkg/client.go: make some CreateOrUpdateXXX functions use library-go’s resourceapply utils.

---

test/e2e/alertmanager_test.go
test/e2e/alertmanager_user_workload_test.go
test/e2e/framework/assertions.go
test/e2e/framework/framework.go
test/e2e/user_workload_monitoring_test.go

This reverts commit 5038186e1c1bf9c86054444310484cc351357f36.
It seems to make the e2e tests very flaky.

MON-3706: Revert "chore: poll immediately in the e2e tests"

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/thanos_ruler_user_workload.go

OCPBUGS-28246: fix Thanos ruler alert generator url

---

Documentation/resources.adoc
Documentation/resources.md
assets/prometheus-k8s/service.yaml
jsonnet/components/prometheus.libsonnet

MON-3380: adjust prometheus-k8s service openshift.io/description

---

Documentation/api.md
Documentation/openshiftdocs/modules/metricsserverconfig.adoc
assets/metrics-server/configmap-audit-profiles.yaml
assets/metrics-server/deployment.yaml
jsonnet/components/metrics-server-audit.libsonnet
jsonnet/main.jsonnet
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
pkg/tasks/metricsserver.go

Enabling audit logs helps troubleshoot issues in Metrics Server. The details of the audit level can be tweaked by selecting an audit profile which corresponds to audit Log Level.
See: https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy
The following profiles are provided:
- Metadata:  The default audit profile
- None
- Request
- RequestResponse
User can pick any of the profile by modifying the CMO configmap as follows
```
apiVersion: v1
kind: ConfigMap
metadata:
name: cluster-monitoring-config
namespace: openshift-monitoring
data:
config.yaml: |
metricsServer:
audit:
profile: Request
```
**Adapted the change as in Prometheus Adapter**

MON-3748: Enable audit logs by default for metrics-server

---

assets/control-plane/minimal-service-monitor-kubelet.yaml
assets/control-plane/service-monitor-kubelet.yaml
jsonnet/components/control-plane.libsonnet

This PR switches monitoring over to use the secure 9637 metrics port for crio (backed by kube-rbac-proxy). It also changes the authentication to use the client certificate auth, since static pods cannot mount secrets.

OCPNODE-2100: jsonnet: update crio port to TLS port 9637

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Fix some golang mistake in which the `remoteWrite` config objects were copied instead of being passed by reference.
**This may impact the customers as the remote write calls may now be proxied:**
- We may want to fix this issue first: https://github.com/prometheus-operator/prometheus-operator/issues/6301
- Also it would be nice to have the Prometheus Operator and CMO forward the `noProxy` option on top of the `proxyUrl`; indeed Prometheus is supporting that option: https://github.com/prometheus/prometheus/blob/main/docs/configuration/configuration.md#oauth2
c.c. @simonpasquier

OCPBUGS-30257: Making sure proxy settings are correctly forwarded in the generated remote write configs

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

MON-3771: update Prometheus operator to v0.72.0

---

Makefile

MON-3789: add a golangci-lint-fix makefile target to fix golangci-lint errros when possible

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Related downstream PO bump https://github.com/openshift/prometheus-operator/pull/284

MON-3793: jsonnet: Bump jsonnet deps for prometheus-operator

---

assets/alertmanager/service-account.yaml
assets/prometheus-k8s/service-account.yaml
assets/thanos-querier/service-account.yaml
jsonnet/components/alertmanager.libsonnet
jsonnet/components/prometheus.libsonnet
jsonnet/components/thanos-querier.libsonnet

MON-3801: remove oauth-redirectreference annotations

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

OCPBUGS-28650: fix generation of telemeter token hash

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/metricsserver.go

MON-3749: enable request headers flags for metrics server

---

assets/control-plane/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

OCPBUGS-31411: add runbook link for KubeAggregatedAPIErrors alert

---

CHANGELOG.md
assets/prometheus-user-workload/prometheus.yaml
jsonnet/components/prometheus-user-workload.libsonnet
test/e2e/config_test.go

Update Prometheus user-workload to enable additional scrape metrics
As part of epic [MON-3256](https://issues.redhat.com/browse/MON-3256)

MON-3621: Enable `extra-scrape-metrics` feature in PrometheusUWM

---

test/e2e/framework/framework.go
test/e2e/user_workload_monitoring_test.go

MON-3706: chore: simplify GetServiceAccountToken()

---

jsonnet/main.jsonnet
manifests/image-references
pkg/manifests/config.go
test/e2e/alertmanager_test.go

MON-3701: remove references to OAuth proxy

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

This PR adds the openshift-kubernetes recording rules for container_network metrics.

WINC-1180: assets, jsonnet: Add container_network openshift-kubernetes.rules

---

assets/alertmanager-user-workload/alertmanager.yaml
assets/alertmanager/alertmanager.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/components/alertmanager-user-workload.libsonnet
jsonnet/components/alertmanager.libsonnet
jsonnet/components/prometheus-operator-user-workload.libsonnet
jsonnet/components/prometheus-operator.libsonnet
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet
jsonnet/components/thanos-ruler.libsonnet
test/e2e/framework/prometheus.go
test/e2e/thanos_ruler_test.go

Add controller-id annotatoins to prometheus, alertmanager, thanos, and prometheus user workload, alertmanager user workload in order to implement prometheus-operator controller id feature https://github.com/prometheus-operator/prometheus-operator/pull/6319 to avoid issues when multiple operators are running.
E.g:  
```
annotations:
operator.prometheus.io/controller-id: openshift-monitoring/prometheus-operator
```
Different id for user workload.

MON-3783: add controller-id annotation to pods deployments and operator

---

assets/alertmanager/alertmanager.yaml
jsonnet/components/alertmanager.libsonnet
jsonnet/utils/generate-certificate-injection.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/alertmanager.go
test/e2e/alertmanager_test.go

MON-3701: clean-up injection of trusted CA bundle for main Alertmanager

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

It also changes the hash algorithm from sha256 to fnv to be consistent with the rest of code and to signal that the use of the function is non-cryptographic.

[release-4.14] OCPBUGS-28768: fix generation of telemeter token hash

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

It also changes the hash algorithm from sha256 to fnv to be consistent with the rest of code and to signal that the use of the function is non-cryptographic.

[release4.13] OCPBUGS-28767: fix generation of telemeter token hash

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

It also changes the hash algorithm from sha256 to fnv to be consistent with the rest of code and to signal that the use of the function is non-cryptographic.

[release-4.12] OCPBUGS-28766: fix generation of telemeter token hash

---

test/e2e/config_test.go
test/e2e/prometheus_test.go
test/e2e/tls_security_profile_test.go

MON-3839: test: add skip tests for prometheus adapter tests

---

assets/prometheus-k8s/prometheus.yaml
jsonnet/components/prometheus.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/prometheus.go

MON-3701: clean-up injection of trusted CA bundle for k8s Prometheus

---

assets/admission-webhook/deployment.yaml
assets/alertmanager/alertmanager.yaml
assets/kube-state-metrics/deployment.yaml
assets/monitoring-plugin/deployment.yaml
assets/node-exporter/daemonset.yaml
assets/openshift-state-metrics/deployment.yaml
assets/prometheus-adapter/deployment.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/telemeter-client/deployment.yaml
assets/thanos-querier/deployment.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/components/admission-webhook.libsonnet
jsonnet/components/alertmanager.libsonnet
jsonnet/components/kube-state-metrics.libsonnet
jsonnet/components/monitoring-plugin.libsonnet
jsonnet/components/node-exporter.libsonnet
jsonnet/components/openshift-state-metrics.libsonnet
jsonnet/components/prometheus-adapter.libsonnet
jsonnet/components/prometheus-operator-user-workload.libsonnet
jsonnet/components/prometheus-operator.libsonnet
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet
jsonnet/components/telemeter-client.libsonnet
jsonnet/components/thanos-querier.libsonnet
jsonnet/components/thanos-ruler.libsonnet
manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml

This PR sets the required SCC explicitly on each workload in `openshift-*` namespaces. The SCC chosen is the one that the pods are getting admitted with, so no change expected there. This is to protect the pods from getting admitted with a different custom SCC than the one intended.
This PR
- updates `manifests/`
- updates any workloads defined in `jsonnet/`
- generates new manifests in `assets/` based on jsonnet changes

AUTH-482: set required-scc for openshift workloads

---

assets/metrics-server/deployment.yaml
jsonnet/components/metrics-server.libsonnet
pkg/tasks/metricsserver.go

OCPBUGS-32510: adapt the metrics-server readiness probe config.
See the added comments and https://docs.google.com/document/d/1VpGBbV30-bb-eq-JYi2q5B8Hyll37tp30OrHcnCifpo/edit?usp=sharing for more details
/cc @slashpai 

OCPBUGS-32510: tweak Prometheus RBAC setup as a temp fix.

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/thanos_ruler_user_workload.go

OCPBUGS-33512: fix Thanos ruler alert generator url

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

This change switches the metrics-server's readiness probe to use the `/livez` endpoint instead of `/readyz` for single-node deployments.
By default, the `/readyz` endpoint is used to assert the component readiness. This endpoint returns success when the metrics-server has metric samples over 2 intervals (e.g. it has scraped at least one kubelet twice).
In single-node deployments, it happens sometimes (especially in end-to-end tests) that the kubelet fails to respond in a timely fashion due to contention in cAdvisor, leading to a delayed readiness (and test failures). To workaround the issue, we use the `/livez` endpoint in this mode.
The long-term plan is to switch resource metrics from cAdvisor to the CRI stats API (currently an alpha feature). Once it happens, we can remove this change.

OCPBUGS-32510: change metrics-server probes for SNO

---

Documentation/resources.adoc
Documentation/resources.md
assets/thanos-querier/service.yaml
jsonnet/components/thanos-querier.libsonnet

: NO-JIRA: Fix formatting in the resources documentation

---

assets/node-exporter/daemonset.yaml
jsonnet/components/node-exporter.libsonnet

Adds the 'enable-ds-eviction' annotation to prevent the cluster autoscaler from removing the node-exporter daemonset during a scaling event.
The motivation for doing this to prevent blocks when node critical pods get evicted prior to workloads.

OCPBUGS-23000: node-exporter: Prevent cluster-autoscaler from evicting

---

test/e2e/alertmanager_test.go
test/e2e/alertmanager_user_workload_test.go
test/e2e/framework/assertions.go
test/e2e/framework/framework.go
test/e2e/user_workload_monitoring_test.go

This reverts commit 10160fd3fefb3791121ad8f5b8bf043938085884.

MON-3874: chore: poll immediately in the e2e tests

---

assets/alertmanager/service-account.yaml
assets/cluster-monitoring-operator/monitoring-alertmanager-edit-role.yaml
assets/prometheus-k8s/service-account.yaml
assets/thanos-querier/service-account.yaml
jsonnet/components/alertmanager.libsonnet
jsonnet/components/cluster-monitoring-operator.libsonnet
jsonnet/components/prometheus.libsonnet
jsonnet/components/thanos-querier.libsonnet
pkg/tasks/alertmanager.go
pkg/tasks/prometheus.go
pkg/tasks/thanos_querier.go
pkg/tasks/thanos_ruler_user_workload.go

After the 4.16-release branch being cut, we have code related to OAuth proxy that can be removed now.

MON-3801: clean-up unused OAuth proxy references

---

assets/alertmanager-user-workload/alertmanager.yaml
jsonnet/components/alertmanager-user-workload.libsonnet
pkg/manifests/manifests_test.go

OCPBUGS-33645: inject trusted CA bundle into UWM Alertmanager

---

assets/thanos-querier/kube-rbac-proxy-secret.yaml
jsonnet/components/thanos-querier.libsonnet
test/e2e/framework/framework.go
test/e2e/user_workload_monitoring_test.go

fix KRP configuration for thanos-querier in order to enforce restricted access only to entities allowed to [http-verb] for pods.metrics.k8s.io

[release-4.14] OCPBUGS-34023: fix KRP permissions for Thanos Querier

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/alertmanager_user_workload.go

MON-3701: clean-up injection of CA bundle for user Alertmanager

---

jsonnet/jsonnetfile.lock.json
jsonnet/main.jsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Addresses the Prometheus dashboard showing up empty in console.
<details>
<summary>Visuals</summary>
</details>
***

OCPBUGS-32696: opt-out of multi-cluster Prometheus dashboard

---

Documentation/api.md
Documentation/openshiftdocs/modules/k8sprometheusadapter.adoc
Documentation/openshiftdocs/modules/metricsserverconfig.adoc
pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests.go
pkg/manifests/types.go
test/e2e/config_test.go

* Add deprecation for prometheus-adapter

OCPBUGS-35480: Add deprecation for prometheus adapter

---

assets/prometheus-k8s/prometheus-rule.yaml
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

Reverts #2392 ; tracked by https://issues.redhat.com/browse/OCPBUGS-36299
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
Hypershift failures due to PrometheusKubernetesListWatchFailures
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-aggregate periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn-conformance 10
```
CC: @machine424
<div align="right">
PR created by <a …

OCPBUGS-36299: Revert #2392 "MON-3800: jsonnet: update prometheus dep to fetch the PrometheusKuber…"

---

assets/alertmanager-user-workload/alertmanager.yaml
jsonnet/components/alertmanager-user-workload.libsonnet
pkg/manifests/manifests_test.go

This is a manual cherry-pick of https://github.com/openshift/cluster-monitoring-operator/pull/2373.
Replaces https://github.com/openshift/cluster-monitoring-operator/pull/2399

[release-4.15] OCPBUGS-36312: inject trusted CA bundle into UWM Alertmanager

---

assets/prometheus-k8s/prometheus-rule.yaml
assets/prometheus-operator/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

OCPBUGS-36406: add runbook_url annotations

---

assets/alertmanager-user-workload/alertmanager.yaml
jsonnet/components/alertmanager-user-workload.libsonnet
pkg/manifests/manifests_test.go

[release-4.14] OCPBUGS-36416: inject trusted CA bundle into UWM Alertmanager

---

assets/control-plane/minimal-service-monitor-kubelet.yaml
assets/control-plane/service-monitor-kubelet.yaml
assets/prometheus-k8s/cluster-role.yaml
jsonnet/components/control-plane.libsonnet
jsonnet/components/prometheus.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml

CRIO is not running on windows nodes hence exclude them from kubelet servicemonitor

OCPBUGS-31250: Exclude windows nodes from kubelet servicemonitor

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet
jsonnet/utils/sanitize-rules.libsonnet

OCPBUGS-36495: Add deprecated config runbook

---

assets/prometheus-k8s/prometheus-rule.yaml
assets/prometheus-operator/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

[release-4.15] OCPBUGS-36563: add runbook_url annotations

---

assets/prometheus-k8s/prometheus-rule.yaml
assets/prometheus-operator/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

[release-4.14] OCPBUGS-36565: add runbook_url annotations

---

jsonnet/components/prometheus.libsonnet

It was caught in review but never actually fixed.

NO-JIRA: fix: fix a small typo

---

pkg/operator/operator.go
pkg/tasks/metricsserver.go
test/e2e/framework/helpers.go
test/e2e/metrics_adapter_test.go
test/e2e/tls_security_profile_test.go

Came across this while working on https://github.com/openshift/cluster-monitoring-operator/pull/2423
/cc @slashpai @jan--f 
/hold
let's wait for https://github.com/openshift/cluster-monitoring-operator/pull/2423 to get merged first.

MON-3900: follow-up: clean up operator logic and some tests now that metrics-server is the default Metrics API backend

---

assets/alertmanager-user-workload/alertmanager.yaml
assets/alertmanager/alertmanager.yaml
jsonnet/components/alertmanager-user-workload.libsonnet
jsonnet/components/alertmanager.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

MON-3961: inject proxy env variables in Alertmanager

---

assets/prometheus-user-workload/prometheus.yaml
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet

 MON-3964: set scrape timestamp tolerance for user workload monitoring

---

pkg/client/client.go
pkg/client/client_test.go

OCPBUGS-17506: Make error messages clearer on poll timeouts

---

assets/admission-webhook/deployment.yaml
assets/alertmanager/alertmanager.yaml
assets/kube-state-metrics/deployment.yaml
assets/monitoring-plugin/deployment.yaml
assets/node-exporter/daemonset.yaml
assets/openshift-state-metrics/deployment.yaml
assets/prometheus-adapter/deployment.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/telemeter-client/deployment.yaml
assets/thanos-querier/deployment.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/components/admission-webhook.libsonnet
jsonnet/components/alertmanager.libsonnet
jsonnet/components/kube-state-metrics.libsonnet
jsonnet/components/monitoring-plugin.libsonnet
jsonnet/components/node-exporter.libsonnet
jsonnet/components/openshift-state-metrics.libsonnet
jsonnet/components/prometheus-adapter.libsonnet
jsonnet/components/prometheus-operator-user-workload.libsonnet
jsonnet/components/prometheus-operator.libsonnet
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet
jsonnet/components/telemeter-client.libsonnet
jsonnet/components/thanos-querier.libsonnet
jsonnet/components/thanos-ruler.libsonnet
manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml

This PR sets the required SCC explicitly on each workload in openshift-* namespaces. The SCC chosen is the one that the pods are getting admitted with, so no change expected there. This is to protect the pods from getting admitted with a different custom SCC than the one intended.
[OCPBUGS-37608](https://issues.redhat.com/browse/OCPBUGS-37608)
Manual cherry-pick of [#2335](https://github.com/openshift/cluster-monitoring-operator/pull/2335)

[release-4.15] OCPBUGS-37608: set required-scc for openshift workloads

---

pkg/operator/operator.go
test/e2e/config_test.go
test/e2e/user_workload_monitoring_test.go

If the Platform configuration is invalid or both configurations are invalid, the reason will still be InvalidConfiguration

OCPBUGS-33863: use UserWorkloadInvalidConfiguration reason when UWM config only is invalid

---

Documentation/api.md
Documentation/openshiftdocs/modules/remotewritespec.adoc
go.mod
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Also
docs: hide PrometheusK8sConfig.RemoteWrite.ProxyURL from docs until its usage is clarified

OCPBUGS-38289: fix(prometheus): avoid passing the cluster-wide proxy config to a remote endpoint when noProxy will prevent the proxuying anyway

---

Documentation/api.md
Documentation/openshiftdocs/modules/remotewritespec.adoc
go.mod
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Backports https://github.com/openshift/cluster-monitoring-operator/pull/2441

OCPBUGS-39029: Backport #2441 for 4.17

---

Documentation/api.md
Documentation/openshiftdocs/modules/remotewritespec.adoc
go.mod
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Backports https://github.com/openshift/cluster-monitoring-operator/pull/2441

OCPBUGS-39170: Backport #2441 for 4.16

---

Documentation/api.md
Documentation/openshiftdocs/modules/remotewritespec.adoc
go.mod
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Backports https://github.com/openshift/cluster-monitoring-operator/pull/2441

OCPBUGS-39172: Backport #2441 for 4.15

---

Documentation/api.md
Documentation/openshiftdocs/modules/remotewritespec.adoc
go.mod
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

Backports https://github.com/openshift/cluster-monitoring-operator/pull/2441

OCPBUGS-39176: Backport #2441 for 4.14

---

assets/prometheus-user-workload/prometheus.yaml
assets/thanos-ruler/thanos-ruler.yaml
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/thanos-ruler.libsonnet
jsonnet/main.jsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/user_workload_monitoring_test.go
test/e2e/uwm_helpers.go

Before this change, a project owner could only disable user-defined monitoring per namespace/project (typically to prevent the `PrometheusOperatorRejectedResources` alert from firing).
To provide greater flexibility, it is now possible to exclude individual objects (e.g. `ServiceMonitor`, `PodMonitor` and `PrometheusRule`) by adding the `openshift.io/user-monitoring="true"` label to them.

OCPBUGS-39126: disable user-defined monitoring per object

---

assets/metrics-server/deployment.yaml
jsonnet/components/metrics-server.libsonnet

OCPBUGS-39133: Configure graceful shutdown for metrics-server

---

assets/metrics-server/deployment.yaml
jsonnet/components/metrics-server.libsonnet

backports https://github.com/openshift/cluster-monitoring-operator/pull/2460

OCPBUGS-41580: Configure graceful shutdown for metrics-server (4.17 backport)

---

pkg/client/client.go
pkg/manifests/apiserver_config_test.go
pkg/manifests/manifests_test.go
test/e2e/alertmanager_helpers.go
test/e2e/alertmanager_test.go
test/e2e/alertmanager_user_workload_test.go
test/e2e/framework/framework.go
test/e2e/multi_namespace_test.go
test/e2e/thanos_ruler_test.go
test/e2e/tls_security_profile_test.go
test/e2e/uwm_helpers.go

avoid declaring new variables for cases as tests are not run in // or because we're already using 1.22 https://go.dev/blog/loopvar-preview
---
only the last commit is to be reviewed, the other one is part of https://github.com/openshift/cluster-monitoring-operator/pull/2464, building on it to avoid conflicts.

MON-3934: move port forward setup inside retry loop for more resiliency

---

assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/prometheus.yaml
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet
test/e2e/config_test.go

MON-3367: chore: enable delayed-compaction feature flag on Platform and UWM Prometheuses

---

jsonnet/components/dashboards.libsonnet
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
jsonnet/main.jsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

This change also removes the dependency on the etcd mixin since everything is now managed by the etcd operator.

NO-JIRA: clean-up generated dashboards

---

test/e2e/alertmanager_test.go
test/e2e/alertmanager_user_workload_test.go
test/e2e/framework/assertions.go
test/e2e/framework/framework.go
test/e2e/user_workload_monitoring_test.go

This reverts commit 10160fd3fefb3791121ad8f5b8bf043938085884.

OCPBUGS-42067: Reapply "chore: poll immediately in the e2e tests"

---

assets/cluster-monitoring-operator/cluster-role-pod-metrics-reader.yaml
jsonnet/components/cluster-monitoring-operator.libsonnet
jsonnet/main.jsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/manifests/manifests.go
pkg/tasks/clustermonitoringoperator.go

The new `pod-metrics-reader` cluster role allows GET *and* POST requests to the namespace-aware Thanos Querier API endpoint.

OCPBUGS-41158: add pod-metrics-reader cluster role

---

assets/prometheus-operator-user-workload/cluster-role.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator/cluster-role.yaml
assets/prometheus-operator/deployment.yaml
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_02-role.yaml

OCPBUGS-30122: chore: Bump to prometheus-operator 0.77.1

---

CONTRIBUTING.md
Documentation/api.md
Documentation/openshiftdocs/index.adoc
Documentation/openshiftdocs/modules/clustermonitoringconfiguration.adoc
Documentation/openshiftdocs/modules/userworkloadconfig.adoc
Documentation/openshiftdocs/modules/userworkloadconfiguration.adoc
assets/thanos-querier/deployment.yaml
jsonnet/components/thanos-querier.libsonnet
pkg/manifests/config.go
pkg/manifests/manifests.go
pkg/manifests/types.go
test/e2e/alertmanager_helpers.go
test/e2e/alertmanager_test.go
test/e2e/image_registry_test.go
test/e2e/user_workload_monitoring_test.go
test/e2e/uwm_helpers.go

This change introduces a way to deploy user-defined rules which are not
scoped to their namespace of origin.
To enable the feature, a user-defined monitoring admin needs to
configure at least one namespace in the UWM ConfigMap:
````
kind: ConfigMap
apiVersion: v1
metadata:
name: user-workload-monitoring-config
namespace: openshift-user-workload-monitoring
data:
config.yaml: |-
namespacesWithoutLabelEnforcement: [ user-monitoring-shared ]
````
For all `PrometheusRule` objects defined in the `user-monitoring-shared`
namespace, Prometheus and Thanos Ruler evaluate the PromQL expressions
without enforcing the namespace label of origin. It makes it possible to
have generic rules that get applied to all (or a subset of) the user
projects instead of having individual rule objects in each user …

MON-3802: implement cross-namespace rules for UWM

---

assets/metrics-server/deployment.yaml
jsonnet/components/metrics-server.libsonnet

MON-3523: Disable http2 in metrics-server by default

---

assets/control-plane/minimal-service-monitor-kubelet.yaml
assets/control-plane/service-monitor-kubelet-resource-metrics.yaml
assets/control-plane/service-monitor-kubelet.yaml
assets/prometheus-k8s/cluster-role.yaml
jsonnet/components/control-plane.libsonnet
jsonnet/components/prometheus.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml

overrides https://github.com/openshift/cluster-monitoring-operator/pull/2488

[release-4.14] OCPBUGS-42603: Exclude windows nodes from kubelet servicemonitor

---

test/e2e/alertmanager_test.go

From https://github.com/openshift/cluster-monitoring-operator/pull/2493#discussion_r1801187426

NO-JIRA: fix CMO config for Alertmanager e2e tests

---

Documentation/resources.adoc
Documentation/resources.md
assets/alertmanager/service.yaml
go.mod
go.sum
hack/docgen/managed_resources.go
jsonnet/components/alertmanager.libsonnet
jsonnet/utils/add-annotations.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
test/e2e/doc_examples_test.go
test/e2e/framework/framework.go
test/e2e/test_command/scripts/openshift-monitoring_alertmanager-main_service_port_9094.yaml
test/e2e/test_command/test_command.go
vendor/github.com/mattn/go-shellwords/.travis.yml
vendor/github.com/mattn/go-shellwords/LICENSE
vendor/github.com/mattn/go-shellwords/README.md
vendor/github.com/mattn/go-shellwords/go.test.sh
vendor/github.com/mattn/go-shellwords/shellwords.go
vendor/github.com/mattn/go-shellwords/util_posix.go
vendor/github.com/mattn/go-shellwords/util_windows.go
vendor/modules.txt

add the required utils to integrate the scenarios scripts testing into CMO e2e tests.
add utils to integrate the scripts with the docs, for now in "Documentation/resources" below the corresponding
'port/RBAC permission'
add an example for how to setup RBAC and access the APIs exposed at openshift-monitoring/alertmanager-main port 9094

MON-4021: feat: add the required utils for automated tests and integration with the docs

---

.golangci.yaml
pkg/client/client_test.go

Adds an explicit `vet` target and also integrates it into the `verify` flow to catch any such violations within the source code.
***

MON-3850: Lint CMO tests

---

Documentation/api.md
Documentation/openshiftdocs/modules/thanosrulerconfig.adoc
pkg/manifests/types.go

OCPBUGS-42148: Fix api doc on Thanos Ruler default retention

---

Documentation/api.md
Documentation/openshiftdocs/modules/thanosrulerconfig.adoc
pkg/manifests/types.go

[release-4.17] OCPBUGS-43545: Fix api doc on Thanos Ruler default retention

---

assets/prometheus-operator/operator-certs-ca-bundle.yaml
jsonnet/components/prometheus-operator.libsonnet
pkg/manifests/manifests.go
pkg/tasks/prometheus.go
pkg/tasks/prometheusoperator.go
pkg/tasks/thanos_querier.go
pkg/tasks/thanos_ruler_user_workload.go

pkg/tasks/prometheusoperator.go: Remove code introduced in https://github.com/openshift/cluster-monitoring-operator/pull/1806
pkg/tasks/{prometheus.go, thanos_ruler_user_workload.go, thanos_querier.go}: Remove cleanup code added in https://github.com/openshift/cluster-monitoring-operator/pull/1731
Was done for 4.15 in https://github.com/openshift/cluster-monitoring-operator/pull/2132
Make some users who don't want to see the unnecessary 404 on 4.14, happy.

OCPBUGS-43678: Remove temporary no more needed code

---

jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

Related-to https://github.com/openshift/prometheus-operator/pull/311

MON-4060: Bump prometheus-operator to v0.77.2

---

assets/telemeter-client/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

OCPBUGS-18007: Add runbook url for TelemeterClientFailures

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

OCPBUGS-27250: bump prometheus-operator to v0.78.1

---

CHANGELOG.md
Documentation/api.md
Documentation/openshiftdocs/modules/prometheusrestrictedconfig.adoc
pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
pkg/operator/operator.go
test/e2e/config_test.go

MON-4057: Expose `scrapeInterval` setting for UWM Prometheus

---

assets/monitoring-plugin/config-map.yaml
jsonnet/components/monitoring-plugin.libsonnet

See http://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens

OCPBUGS-44003: fix(monitoring-plugin): disable emitting nginx version on error pages

---

assets/alertmanager-user-workload/service-monitor.yaml
assets/alertmanager/service-monitor.yaml
assets/cluster-monitoring-operator/service-monitor.yaml
assets/control-plane/minimal-service-monitor-kubelet.yaml
assets/control-plane/service-monitor-kubelet.yaml
assets/kube-state-metrics/minimal-service-monitor.yaml
assets/kube-state-metrics/service-monitor.yaml
assets/metrics-server/service-monitor.yaml
assets/node-exporter/minimal-service-monitor.yaml
assets/node-exporter/service-monitor.yaml
assets/openshift-state-metrics/service-monitor.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
assets/prometheus-k8s/service-monitor.yaml
assets/prometheus-operator-user-workload/service-monitor.yaml
assets/prometheus-operator/service-monitor.yaml
assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
assets/prometheus-user-workload/service-monitor.yaml
assets/telemeter-client/service-monitor.yaml
assets/thanos-querier/service-monitor.yaml
assets/thanos-ruler/service-monitor.yaml
jsonnet/components/alertmanager-user-workload.libsonnet
jsonnet/components/alertmanager.libsonnet
jsonnet/components/cluster-monitoring-operator.libsonnet
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet
jsonnet/utils/configure-authentication-for-monitors.libsonnet

NO-JIRA: use scrape class to avoid TLS config repetitions

---

assets/alertmanager-user-workload/alertmanager.yaml
assets/alertmanager-user-workload/service-account.yaml
jsonnet/components/alertmanager-user-workload.libsonnet

OCPBUGS-44831: disable token automount for alertmanager-user-workload SA

---

Documentation/data-collection.md
manifests/0000_50_cluster-monitoring-operator_04-config.yaml

Updates the metrics queries for the logging telemetry to explicitly use the `__name__` label.
See also #2526 (backport to 4.18) and #2528 (backport of original change to 4.17 including this fix).

OCPBUGS-45179: Use explicit name label for logging telemetry metrics

---

pkg/manifests/manifests.go
pkg/tasks/monitoring_plugin.go

With https://github.com/openshift/monitoring-plugin/pull/264, the monitoring plugin binary reloads the certificate and key files from disk automatically.

OCPBUGS-35726: remove certificate hash annotation for monitoring-plugin

---

Documentation/data-collection.md
manifests/0000_50_cluster-monitoring-operator_04-config.yaml

Updates the metrics queries for the logging telemetry to explicitly use the `__name__` label. Needs to be backported to 4.14 - 4.17. See also #2526 (backport to 4.17) and #2529 (this change on 4.19)

OCPBUGS-44724: Use explicit name label for logging telemetry metrics

---

assets/node-exporter/accelerators-collector-configmap.yaml
assets/node-exporter/daemonset.yaml
jsonnet/components/node-exporter.libsonnet
pkg/manifests/manifests.go
pkg/tasks/nodeexporter.go

1) adding ConfigMap that contains the yaml structure describing
monitored accelerators per vendor/model
2) mapping accelerators ConfigMap into the node-exporter pods 3) adding env variable that contains the exact path for the mapped
ConfigMap

MGMT-19498: Adding accelerators configuration file to the node-exporter

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

NO-JIRA: Bump prometheus-operator to v0.79.1

---

jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

NO-JIRA: Bump prometheus-operator to 0.79.2

---

Documentation/api.md
Documentation/openshiftdocs/modules/additionalalertmanagerconfig.adoc
pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
test/e2e/user_workload_monitoring_test.go

chore: adjust AdditionalAlertmanagerConfig.[*].APIVersion documentation as v1 is not longer suporter in Prom 3
chore: add a config validation check in case v1 in still using in one of the three AdditionalAlertmanagerConfig (Platform
Prom, UWM Prom and Thanos ruler), this is temp and just meant to guide users during the first 4.X upgrade that ships Prom 3
MON-4118: chore: use alertmanager v2 in tests as v1 is not longer supported in Prometheus 3
---
This will be mentioned in the release notes and maybe we'll upgrade a "known risk/ a warning" for ->4.19 upgrades.

MON-4118: chore: use alertmanager v2 in tests as v1 is not longer supported in Prometheus 3

---

pkg/client/client.go

OCPBUGS-31356: chore(client): DeleteXXX short-circuit if the resource doesn't exist as a GET is less expensive than a no-op DELETE

---

pkg/tasks/alertmanager.go
pkg/tasks/alertmanager_user_workload.go
pkg/tasks/prometheus_user_workload.go
pkg/tasks/prometheusoperator_user_workload.go
pkg/tasks/telemeter.go
pkg/tasks/thanos_ruler_user_workload.go

This still requires CMO log level to be changed while debugging.

MON-4107: chore: add logs (at v=3 level) regarding the deactivation of components

---

.github/ISSUE_TEMPLATE/release.md
CONTRIBUTING.md
Documentation/sample-metrics.md
hack/go/generate_versions.go

Mainly for `make versions`
/hold
can be merged later

OCPBUGS-48370: chore: rename default branch in various places

---

jsonnet/jsonnetfile.json

OCPBUGS-48376: jsonnet: switch openshift-state-metrics to main branch

---

jsonnet/jsonnetfile.json

OCPBUGS-48381: jsonnet: switch telemeter to main

---

Documentation/resources.adoc
hack/docgen/managed_resources.go
test/e2e/test_command/test_command.go

As requested in https://github.com/openshift/cluster-monitoring-operator/pull/2557
Also
Hide the auto examples from asciiDocs as it's still WIP, to avoid confusion

NO-JIRA: tweak asciiDocs formatting to ease the mapping into the monitoring Docs

---

assets/cluster-monitoring-operator/metrics-server-client-certs.yaml
assets/metrics-server/deployment.yaml
jsonnet/components/cluster-monitoring-operator.libsonnet
jsonnet/components/metrics-server.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/tls.go
pkg/operator/operator.go
pkg/tasks/metricsserver.go

reviving https://github.com/openshift/cluster-monitoring-operator/pull/2329
requires https://github.com/openshift/cluster-policy-controller/pull/148
---

MON-3866: create separate metrics client cert for metrics server

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

NO-JIRA: Bump prometheus-operator to v0.80.0

---

Documentation/data-collection.md
manifests/0000_50_cluster-monitoring-operator_04-config.yaml

OCPBUGS-50837: Fix opentelemetry metrics to use regexp on label match

---

test/e2e/user_workload_monitoring_test.go

since those
scenarios are already tested in TestUserWorkloadMonitorPrometheusK8Config.
Additionally, these configurations may require UWM Prometheus Pods to restart during tests (with statefulset recreation as claim template is updated), as applying these configurations is asynchronous. This could disrupt the tests, make them harder to debug, and slow them down.
Also
test(TestUserWorkloadMonitoringMetrics): increase timeout to 3m as some Pods may require more that 1m to become ready and get scraped by Prometheus for the first time

MON-4147: test: remove unnecessary UWM configuration in TestUserWorkloadMonitoringXXX

---

jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

NO-JIRA: Bump prometheus-operator to 0.80.1

---

hack/go/generate_versions.go

NO-JIRA: chore: versions: kubeRbacProxy's primary branch isn't main yet

---

jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

OCPBUGS-52565: Bump prometheus-operator to 0.78.2

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

MON-4136: set up the PrometheusPossibleNarrowSelectors alert

---

Documentation/api.md
Documentation/openshiftdocs/modules/thanosrulerconfig.adoc
pkg/manifests/types.go

MON-4188: Add docs for proxy_url alertmanager

---

go.mod
pkg/configvalidate/configvalidate_test.go
pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests_test.go

OCPBUGS-54516: provide context-rich and case-sensitive config validation

---

go.mod
pkg/configvalidate/configvalidate.go
pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
test/e2e/config_test.go
test/e2e/user_workload_monitoring_test.go

The strict unmarshaller is currently in advisory mode. Setting CMO to Upgradeable=false ensures that configurations meet the new unmarshaller checks in 4.18 before it is set to be the default in 4.19.
This is similar to what was done in https://github.com/openshift/cluster-monitoring-operator/pull/2494 when the strict unmarshaller was introduced.

OCPBUGS-55005: chore: introduce context-rich anb case sensitive unmarshaller for the monitoring and  set CMO to Upgradeable=false if errors are found

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

…il we can ensure it won't result in excessive CPU usage
requires https://github.com/openshift/prometheus/pull/227

MON-4200: disable --auto-gomemlimit for Prometheus on SNO until we can ensure it won't result in excessive CPU usage

---

assets/alertmanager/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet

This picks up https://github.com/prometheus/alertmanager/pull/4206/ so we don't have to wait.

OCPBUGS-33691: mixin: longer rate interval for Alertmanager[Cluster]FailedToSendAlerts

---

Documentation/api.md
Documentation/openshiftdocs/modules/metricsserverconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go

MON-4242: chore(metrics-server): allow setting log verbosity

---

pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests_test.go

Prometheus v3 no longer supports alertmanager v1
OCP 4.19 will fail early (InvalidConfigXXX) in case alertmanager apiVersion: v1 is still specified in one of the two configmaps.
To avoid that InvalidConfigXXX from triggering just after the 4.19 upgrade, we can make users bump their alertmanagers and only use apiVersion: v2 in the configmaps.
We can do that by making CMO set upgradable=false when it sees apiVersion: v1 in one of the configmaps and make sure clusters go through that 4.18.x before upgrading to 4.19.

[release-4.18] OCPBUGS-56251: set upgradable false when alertmanager v1 is specified

---

pkg/manifests/tls.go

Previously this configmap didn't have annotations set, so these were being reset to an empty map. Now it has ownership annotation, so reset to an empty map is erasing them
Follow-up for https://github.com/openshift/cluster-monitoring-operator/pull/2602

OCPBUGS-58427: pkg/manifests: don't reset annotations for metrics client CA

---

CHANGELOG.md
assets/kube-state-metrics/cluster-role.yaml
assets/kube-state-metrics/deployment.yaml
jsonnet/components/kube-state-metrics.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/client/client.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
pkg/tasks/kubestatemetrics.go

#2078 added support for VPA monitoring as a CRD type, and included changes to check for the existence of the VPA CRD, and only try to generate VPA metrics if the CRD was actually installed, because [if "the VPA CRD is not present in the cluster" then "enabling the custom-resource-state-based metrics will cause kube-state-metrics to error (affecting `KubeStateMetricsListErrors`)"](https://github.com/openshift/cluster-monitoring-operator/pull/2078/commits/bc1174a6f7746950a11bc405bc825a132c4957a7#diff-99c0290799daf9abc6240df64063e20bfaf67b371577b67ac7eec6f4725622ffR205-R207).
But as far as I can tell, this comment isn't true; ksm's CRD support already does this internally, and doesn't try to monitor resources for CRD types when the corresponding CRD is not installed... (the absence of errors …

MON-4282: Multi-tenant support for KSM's CRS

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

* [x ] No user facing changes, so no entry in CHANGELOG was needed.

MON-4255: Bump prometheus-operator to v0.83

---

pkg/manifests/amcfg.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

This commit enforces secure TLS settings in order to eliminate insecure
cipher warnings in cluster-monitoring-operator logs. It changes
Alertmanager configurations used by Prometheus and Thanos.
- Set `min_version: TLS1.2` and explicitly define secure `cipher_suites`
- Applied to all additional Alertmanager configs
- Updated tests accordingly

OCPBUGS-58475: Enforce secure TLS settings in CMO

---

assets/thanos-querier/deployment.yaml
jsonnet/components/thanos-querier.libsonnet

There's no user visible change but it should bring performance and resource usage improvements in setups with large number of rules since the data is filtered at the source (Prometheus and Thanos) rather than by the proxy.

NO-JIRA: Use label matchers for Rules API in prom-label-proxy

---

Documentation/debug-container.md
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
manifests/image-references
pkg/manifests/config.go
pkg/operator/operator.go

This commit adds a new optional image to CMO manifest for debugging purposes,
it's based on ubi9, adding a workaround to enable smtp in libcurl, which is
needed by support KCS'

MON-4318: Add debug image manifest to CMO

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

OCPBUGS-56158: Bump prometheus-operator to v0.85.0

---

pkg/manifests/config.go
pkg/manifests/config_test.go

NO-JIRA: chore: drop check for AlertmanagerV1

---

pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
test/e2e/config_test.go
test/e2e/user_workload_monitoring_test.go

MON-4343: Cleanup deprecate pa config

---

pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
test/e2e/config_test.go
test/e2e/user_workload_monitoring_test.go

Reverts openshift/cluster-monitoring-operator#2651
See https://issues.redhat.com/browse/OCPBUGS-61135

OCPBUGS-61135: Revert "MON-4343: Cleanup deprecate pa config"

---

assets/prometheus-k8s/prometheus.yaml
assets/prometheus-user-workload/prometheus.yaml
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet
test/e2e/config_test.go

chore: enable use-uncached-io (using direct I/O for now) feature flag to prevent bad
decisions based on page cache.
to learn more about it https://github.com/prometheus/proposals/blob/main/proposals/0045-direct-io.md
Introduced in https://github.com/prometheus/prometheus/pull/15365
from upstream benchmark
for the same written data, cache is bypassed (where direct i/o is used) as expected, `container_memory_usage_bytes` reflects that as expected.
---
The first version of the PR ran the presubmit and payload tests with `storage.tsdb.min-block-duration=5m` to speed up compaction and trigger the feature flag more frequently. No regressions were identified.
---

MON-4371: chore(prometheus): enable use-uncached-io feature flag

---

assets/control-plane/prometheus-rule.yaml
jsonnet/utils/sanitize-rules.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

This commit removes the Kubernetes API alerting rules from the `kubernetes-monitoring-rules` PrometheusRule resource. From now on, these rules will be managed by the Kubernetes API server operator.

OCPBUGS-15430: remove Kubernetes API alerting rules

---

assets/cluster-monitoring-operator/cluster-role-aggregated-metrics-reader.yaml
assets/cluster-monitoring-operator/cluster-role-pod-metrics-reader.yaml
jsonnet/components/cluster-monitoring-operator.libsonnet
jsonnet/utils/anti-affinity.libsonnet
jsonnet/versions.yaml

NO-ISSUE: chore: remove mentions of prometheus Adapter
