pkg/manifests/config.go

Change default retention to 15 days

---

.travis.yml
cmd/operator/main.go
pkg/manifests/manifests_test.go

*: enable unit tests

---

OWNERS

OWNERS: add lucas and sergiusz

---

README.md

Update integration of cluster components description

---

Makefile

cc @brancz 
sorry, fixing a small make bug

Makefile: re-vendor when jsonnetfile changes

---

Makefile

Makefile: comment for operator-no-deps

---

assets/alertmanager/alertmanager.yaml
assets/prometheus-k8s/prometheus.yaml
jsonnet/main.jsonnet

This will set the anti affinity for Prometheus & Alertmanager.
https://bugzilla.redhat.com/show_bug.cgi?id=1635802
/cc @mxinden @squat

Add antiaffinity to Prometheus & Alertmanager

---

Makefile
manifests/03-etcd-secret.yaml
scripts/deploy-on-openshift.sh

Seems like the filenames are outdated and the script thus doesn't work anymore.

Fix deploy-on-openshift.sh

---

Dockerfile

This pattern will work better for upstream and production builds.

Use golang builder

---

pkg/manifests/config.go
pkg/manifests/config_test.go
pkg/manifests/manifests_test.go

pkg/manifests: etcd defaults to disabled

---

pkg/manifests/manifests.go
pkg/tasks/configsharing.go

In #155 I missed to also add the Grafana host to this, so here it goes.
@s-urbaniak @squat @mxinden 
cc @kyoto

configsharing: Add Grafana host syncing

---

hack/cluster-monitoring-operator-role.yaml.in
manifests/02-role.yaml

manifests: add config API to clusterrole

---

manifests/04-deployment.yaml

@squat @metalmatze @s-urbaniak @mxinden 
cc @derekwaynecarr

manifests: Run cluster-monitoring-operator on masters

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

There was a conversation on slack about this and I wanted to make sure it works :slightly_smiling_face: .
@metalmatze @squat @s-urbaniak @mxinden

manifests: Add unit test for prometheus adapter nodeSelector config

---

pkg/tasks/tasks.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1678475
cc @brancz @mxinden

pkg/tasks: execute tasks concurrently

---

OWNERS

Remove myself from the OWNERS list.

OWNERS: Remove ironcladlou

---

test/e2e/main_test.go

Check if telemeter-client target is up.
/assign @s-urbaniak

test/e2e: check if telemeter-client is present

---

.travis.yml
hack/yamllint.sh

Follow up to issue discovered in #302.
More info: https://github.com/openshift/cluster-monitoring-operator/pull/302#issuecomment-479175754

use containerized yamllint in CI pipeline

---

pkg/client/client.go

Prereq for https://bugzilla.redhat.com/show_bug.cgi?id=1698625
https://github.com/openshift/origin/pull/22737 indicates that when we try to use a CRD handler for SCC, the behavior around resourceVersion and unconditional update isn't quite the same.  We can see 
```
message: 'Failed to rollout the stack. Error: running task Updating node-exporter
failed: reconciling node-exporter SecurityContextConstraints failed: updating
SecurityContextConstraints object failed: securitycontextconstraints.security.openshift.io
"node-exporter" is invalid: metadata.resourceVersion: Invalid value: 0x0: must
be specified for an update'
```
from https://storage.googleapis.com/origin-ci-test/pr-logs/pull/22737/pull-ci-openshift-origin-master-e2e-aws/8266/artifacts/e2e-aws/must-gather/cluster-scoped-resources/c …

plumb a resource version for SCC updates

---

manifests/04-deployment.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1707066
/cc @metalmatze @paulfantom

manifests: set terminationMessagePolicy for CMO

---

pkg/client/client.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1707519
/cc @metalmatze @paulfantom

pkg/client: don't update rolebdindings if they don't differ

---

OWNERS

update repository ownership

---

pkg/client/clusteroperator.go

newClusterOperator() which sets status.RelatedObjects isn't called everytime. This causes lack of RelatedObjects field in ClusterOperator status. Simple fix is to set this as soon as we set first status with SetInProgress.
Problem was detected when re-enabling test in https://github.com/openshift/origin/pull/23137
Follow-up to #373. Needs to be cherry-picked into #375 and merged to release-4.1 branch.

pkg/client: reset relatedObjects every time status is set to in progress

---

Makefile

Unblock https://github.com/openshift/cluster-monitoring-operator/pull/372 by enabling go modules in Makefile
/cc @brancz @metalmatze @s-urbaniak @squat

*: set GO111MODULE in Makefile

---

Dockerfile.rhel7

Fix OSBS build broblem.
/cc @brancz

*: allow building ocp image without access to external sources

---

Dockerfile

This is causing osbs build issues.
@squat

Dockerfile: mods from vendor

---

pkg/client/condition.go
pkg/client/condition_test.go
pkg/client/status_reporter.go
pkg/client/status_reporter_test.go

Currently we don't report that status. This fixes it.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1727024
/cc @LiliC @paulfantom

Bug 1727024: Add OperatorUpgradeable status to StatusReporter

---

OWNERS

OWNERS: add LiliC

---

assets/alertmanager/trusted-ca-bundle.yaml
jsonnet/alertmanager.jsonnet
pkg/manifests/bindata.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
pkg/tasks/alertmanager.go
test/e2e/alertmanager_test.go

Should be ready for review:
TODO:

Add Alertmanager trusted CA bundle support

---

pkg/client/client.go
pkg/tasks/alertmanager.go
pkg/tasks/telemeter.go

Currently, we delete the current hashed configmap in alertmanager, just to recreate it afterwards.
This fixes it and, along the way, factors a central DeleteHashedConfigMap.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1746097

Bug 1746097: pkg/tasks/alertmanager: delete hashed configmaps with new hash only

---

Makefile

Makefile: add go proxy support

---

hack/local-cmo.sh

This will allow for easier debugging.
/cc @LiliC @s-urbaniak

hack: add script to run CMO locally

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json

cc @brancz is there anything else we need to do before the release besides pinning these deps?

jsonnet: Pin components to the 4.2 release

---

pkg/tasks/prometheusoperator.go

Noticed this TODO, from what I can tell it's safe to remove it now?
cc @brancz @s-urbaniak

pkg/tasks/prometheusoperator.go: Remove migration code

---

pkg/manifests/manifests_test.go

manifests: add missing thanos querier tests

---

pkg/tasks/prometheusoperator.go

It's not actually 100% clear whether this fixes the issues seen in https://bugzilla.redhat.com/show_bug.cgi?id=1761887, but it adds more logging so that we could see whether the migration was attempted at all when we expect it as I feel when we run into the problem described in the bug we are for some reason not attempting the migration, so changing the strategy with this.
@LiliC @s-urbaniak @paulfantom

Bug 1761887: tasks/prometheusoperator: Change deployment selector migration strategy

---

pkg/client/client.go

Bug 1763057: pkg/client: Fix setting number of unavailable pods for DaemonSet

---

OWNERS

OWNERS: add new members

---

go.mod
test/e2e/framework/framework.go
test/e2e/framework/prometheus_client.go
test/e2e/main_test.go
test/e2e/multi_namespace_test.go
test/e2e/user_workload_monitoring_test.go

Take 2, let's see if CI is going to tackle this now.

test/e2e: add user workload monitoring

---

pkg/manifests/manifests.go

We need to mount trustedCA bundle into a place that is understandable by oauth-proxy and from where a bundle can be picked up. This is similar to how we did it for telemeter.
Fix is based on @gfvirga [comment](https://github.com/openshift/cluster-monitoring-operator/pull/448#issuecomment-547051573) and further investigation with @sur
@LiliC this might also solve alertmanager problems with CA bundle.
Part 1/3 of fixing oauth-proxy problems with trustedCA budle :)

Bug 1766984: trustedCA bundle support for alertmanager oauth proxy

---

assets/thanos-querier/trusted-ca-bundle.yaml
jsonnet/thanos-querier.jsonnet
pkg/client/client.go
pkg/manifests/bindata.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/thanos_querier.go
test/e2e/thanos_querier_test.go
test/e2e/user_workload_monitoring_test.go

This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1787098. I am not setting the bugzilla bot title as we will backport this to 4.3.
Let's see what e2e says, I did not test this in a local cluster.

*/thanos-querier: mount trusted CA bundle

---

jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json

This reverts commit dba1836fa2bf5bb2308aa4db14ac31da7b2e246b.

Bug 1796473: Revert "jsonnet: regenerate jsonnetfile.* with latest jb"

---

assets/prometheus-k8s/trusted-ca-bundle.yaml
jsonnet/jsonnetfile.lock.json
jsonnet/prometheus.jsonnet
pkg/manifests/bindata.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/prometheus.go
test/e2e/prometheus_test.go

Backporting https://github.com/openshift/cluster-monitoring-operator/pull/559
/cc @lilic @s-urbaniak

Bug 1803957: Backport trusted ca support for prometheus

---

go.mod
go.sum
vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/init.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/install.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/rewrite.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/update.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/git.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/jsonnetfile/jsonnetfile.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/local.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/packages.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/spec/v0/spec.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/spec/v1/deps/dependencies.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/spec/v1/deps/git.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/spec/v1/spec.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/spec/v1/v0.go
vendor/github.com/jsonnet-bundler/jsonnet-bundler/tool/rewrite/rewrite.go
vendor/modules.txt

The update to the jsonnet-ci image seems to be causing failures in other PRs (#701, #702).

Update jsonnet bundler v0.3.1

---

pkg/client/status_reporter.go
pkg/operator/operator.go
test/e2e/config_test.go
test/e2e/framework/framework.go

Bug 1807430: don't sync on invalid configuration

---

Documentation/data-collection.md
manifests/0000_50_cluster_monitoring_operator_04-config.yaml

* Adds @openshift/openshift-team-olm to 0000_50_cluster_monitoring_operator_04-config.yaml
* Adds @openshift/openshift-team-olm to data-collection.md

Add Operator Lifecycle Manager (OLM) team

---

test/e2e/user_workload_monitoring_test.go

It should reduce the likelihood of failing the test when
port-forwarding encounters connection issues.
It also fixes a typo in the test which was running the same query
thrice.

test/e2e: forward port for every query

---

Makefile
pkg/tasks/thanos_ruler_user_workload.go

Fix cleanup of thanos rule grpc tls secret.

Bug 1821666: thanos ruler secret cleanup

---

pkg/client/client.go

By design it is not possible to update cluster role bindings as per [1].
This fixes it by deleting it first.
[1]: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrolebinding-example

Bug 1822097: pkg/client: delete and create clusterrolebindings instead of updating

---

pkg/client/client.go

When waiting for a resource to be ready, each condition is checked
separately so that a precise error message is returned.
Also make messages consistent across functions.
From https://github.com/openshift/cluster-monitoring-operator/pull/800#issuecomment-641958251

pkg/client: improve error messages

---

test/e2e/multi_namespace_test.go

I glanced over our test failures from `e2e-aws-operator` and it looks like most of them are related to problems with connecting to prometheus because proxies didn't finish bootstrapping (returning 503 instead of 200). The change proposed here should fix this by ensuring connection to prometheus can be established before testing for rules.

test/e2e: check if prometheus is reachable before querying for prom rules

---

pkg/manifests/tls.go
pkg/manifests/tls_test.go

This change makes sure that the renewed certificate isn't valid for
longer than the default lifetime of 2 years.

Bug 1853250: pkg/manifests: update notBefore on cert renewal

---

CONTRIBUTING.md
README.md

This fixes #803 by adding a "contributing" section and simple workflow description

readme: add contributing section

---

hack/uwm_setup.sh

Updating Bash script to include more detailed user login output. The output provides steps on how to change user passwords and replace the secret so that the password changes become active.

Adding more detailed user login output

---

pkg/operator/operator.go

Bug 1870111: log warning when 'techPreviewUserWorkload' is enabled

---

manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml

Bug 1882428: add ThanosRuler, PodMonitor and Probe to operator group

---

test/rules/bz1882730.yaml

test/rules: remove commented lines

---

CHANGELOG.md
assets/alertmanager/secret.yaml
assets/grafana/deployment.yaml
assets/node-exporter/daemonset.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-k8s/rules.yaml
assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
assets/prometheus-k8s/service-thanos-sidecar.yaml
assets/prometheus-k8s/service.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
assets/prometheus-user-workload/service-thanos-sidecar.yaml
assets/prometheus-user-workload/service.yaml
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
jsonnet/prometheus-user-workload.jsonnet
jsonnet/prometheus.jsonnet
pkg/manifests/manifests.go
pkg/tasks/prometheus.go
pkg/tasks/prometheus_user_workload.go
test/e2e/prometheus_test.go
test/e2e/user_workload_monitoring_test.go

Add Thanos sidecar metrics + alerts

---

.github/ISSUE_TEMPLATE/release.md

Update release checklist template

---

assets/node-exporter/daemonset.yaml
assets/telemeter-client/deployment.yaml
jsonnet/jsonnetfile.lock.json
jsonnet/node-exporter.jsonnet

Bug 1905330: Add missing CPU and memory requests

---

Documentation/data-collection.md
manifests/0000_50_cluster-monitoring-operator_04-config.yaml

this is so reading it will be easier, maybe add a PR to automatically generate this file

docs(data-collection): add newlines for visibility

---

OWNERS

Also a way to test https://github.com/openshift/release/pull/17112

OWNERS: add Jan

---

assets/prometheus-operator-user-workload/cluster-role-binding.yaml
assets/prometheus-operator-user-workload/cluster-role.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator-user-workload/service-account.yaml
assets/prometheus-operator-user-workload/service-monitor.yaml
assets/prometheus-operator-user-workload/service.yaml
assets/prometheus-operator/cluster-role-binding.yaml
assets/prometheus-operator/cluster-role.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-operator/prometheus-rule.yaml
assets/prometheus-operator/service-account.yaml
assets/prometheus-operator/service-monitor.yaml
assets/prometheus-operator/service.yaml
go.mod
go.sum
jsonnet/main.jsonnet
vendor/modules.txt

Bug 1879495: jsonnet: update prometheus-operator to 0.48

---

hack/shellcheck.sh

hack: do not use shellcheck container

---

jsonnet/cluster-monitoring-operator.libsonnet
jsonnet/openshift-state-metrics.libsonnet
jsonnet/prometheus.libsonnet
jsonnet/remove-runbook.libsonnet
jsonnet/telemeter-client.libsonnet
jsonnet/thanos-querier.libsonnet

jsonnet: Run jb rewrite to convert to absolute paths

---

pkg/client/client.go
test/e2e/user_workload_monitoring_test.go

The client package has several methods that poll to wait for certain
conditions to become true, but they all fail immediately when the
initial request(s) to the API server return an error.  This changes
that behavior to ensure the API requests are retried as well, and
simply logs the error returned by the API server at debug level.
The main goal here is to help with e2e test flakiness. We have a lot of test failures that seem to be the result of transient API server or network issues. The tests that use the methods that poll often fail needlessly when they could just retry. Having said that, I'm a bit concerned this could have unintended consequences. For instance, things now taking multiple minutes to retry when there is a legitimate configuration issue.

pkg/client: Retry on API errors in polling methods

---

assets/alertmanager/prometheus-rule.yaml
assets/prometheus-k8s/prometheus-rule.yaml
jsonnet/jsonnetfile.lock.json

jsonnet: pull latest deps

---

Documentation/data-collection.md
manifests/0000_50_cluster-monitoring-operator_04-config.yaml

Cleanup telemetry owners

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/cluster-monitoring-operator.libsonnet
jsonnet/main.jsonnet
jsonnet/remove-runbook-urls.libsonnet
jsonnet/rules.libsonnet
test/rules/workload_incorrectly_spread.yaml

Backport #1242 and #1262 to release-4.8.

Bug 1981246: [4.8]: Add HighlyAvailableWorkloadIncorrectlySpread alert

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
assets/control-plane/prometheus-rule.yaml
assets/grafana/dashboard-definitions.yaml
assets/node-exporter/daemonset.yaml
assets/node-exporter/prometheus-rule.yaml
jsonnet/jsonnetfile.lock.json
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

Bug 1973491: jsonnet: update deps

---

assets/prometheus-k8s/cluster-role-binding.yaml
assets/prometheus-k8s/cluster-role.yaml
assets/prometheus-k8s/prometheus-rule-thanos-sidecar.yaml
assets/prometheus-k8s/prometheus-rule.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-k8s/role-binding-config.yaml
assets/prometheus-k8s/role-binding-specific-namespaces.yaml
assets/prometheus-k8s/role-config.yaml
assets/prometheus-k8s/role-specific-namespaces.yaml
assets/prometheus-k8s/service-account.yaml
assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
assets/prometheus-k8s/service-monitor.yaml
assets/prometheus-k8s/service-thanos-sidecar.yaml
assets/prometheus-k8s/service.yaml
assets/prometheus-user-workload/cluster-role-binding.yaml
assets/prometheus-user-workload/cluster-role.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/prometheus-user-workload/role-binding-config.yaml
assets/prometheus-user-workload/role-binding-specific-namespaces.yaml
assets/prometheus-user-workload/role-config.yaml
assets/prometheus-user-workload/role-specific-namespaces.yaml
assets/prometheus-user-workload/service-account.yaml
assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
assets/prometheus-user-workload/service-monitor.yaml
assets/prometheus-user-workload/service-thanos-sidecar.yaml
assets/prometheus-user-workload/service.yaml
jsonnet/versions.yaml

Bug 1999397: Bump prom 2.29.2

---

hack/generate-versions.sh
hack/shellcheck.sh
pkg/manifests/manifests.go

This PR formats the codebase and fixes shellcheck in the CI.

Format the codebase and fix shellcheck

---

OWNERS

OWNERS: move @paulfantom to emeritus section

---

Documentation/data-collection.md
manifests/0000_50_cluster-monitoring-operator_04-config.yaml

Relevant request and approval can be found at:
https://docs.google.com/document/d/1o4UZ3QeRheL-xZqfYWRRtJOZ2I3uJPdZXWUfY_sy8Dc/edit?usp=sharing
Associated BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2005971
Signed-off-by: Ken Finnigan <ken@kenfinnigan.me>

Bug 2005971: Add metrics for Application Services metering

---

assets/prometheus-operator-user-workload/cluster-role-binding.yaml
assets/prometheus-operator-user-workload/cluster-role.yaml
assets/prometheus-operator-user-workload/deployment.yaml
assets/prometheus-operator-user-workload/service-account.yaml
assets/prometheus-operator-user-workload/service-monitor.yaml
assets/prometheus-operator-user-workload/service.yaml
assets/prometheus-operator/cluster-role-binding.yaml
assets/prometheus-operator/cluster-role.yaml
assets/prometheus-operator/deployment.yaml
assets/prometheus-operator/prometheus-rule.yaml
assets/prometheus-operator/service-account.yaml
assets/prometheus-operator/service-monitor.yaml
assets/prometheus-operator/service.yaml
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
jsonnet/versions.yaml

Syncing with current version from https://github.com/openshift/prometheus-operator

Bump prometheus operator to v0.51.2

---

assets/prometheus-k8s/cluster-role-binding.yaml
assets/prometheus-k8s/cluster-role.yaml
assets/prometheus-k8s/prometheus-rule-thanos-sidecar.yaml
assets/prometheus-k8s/prometheus-rule.yaml
assets/prometheus-k8s/prometheus.yaml
assets/prometheus-k8s/role-binding-config.yaml
assets/prometheus-k8s/role-binding-specific-namespaces.yaml
assets/prometheus-k8s/role-config.yaml
assets/prometheus-k8s/role-specific-namespaces.yaml
assets/prometheus-k8s/service-account.yaml
assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
assets/prometheus-k8s/service-monitor.yaml
assets/prometheus-k8s/service-thanos-sidecar.yaml
assets/prometheus-k8s/service.yaml
assets/prometheus-user-workload/cluster-role-binding.yaml
assets/prometheus-user-workload/cluster-role.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/prometheus-user-workload/role-binding-config.yaml
assets/prometheus-user-workload/role-binding-specific-namespaces.yaml
assets/prometheus-user-workload/role-config.yaml
assets/prometheus-user-workload/role-specific-namespaces.yaml
assets/prometheus-user-workload/service-account.yaml
assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
assets/prometheus-user-workload/service-monitor.yaml
assets/prometheus-user-workload/service-thanos-sidecar.yaml
assets/prometheus-user-workload/service.yaml
jsonnet/jsonnetfile.lock.json
jsonnet/versions.yaml

Follow-up of https://github.com/openshift/prometheus/pull/98

Bump prometheus v2.30.3

---

Documentation/data-collection.md
manifests/0000_50_cluster-monitoring-operator_04-config.yaml

openshift-team-cluster-manager uses a list of metrics. This PR updates that list.

Update list of metrics used by openshift-team-cluster-manager

---

Makefile

MON-1656: adding new target to makefile for verification

---

pkg/client/client.go
pkg/client/client_test.go

Some resources (ConfigMaps, Secrets, ValidatingWebhookConfigurations)
have fields, that are managed by the service-ca-operator. If we find
these fields populated we want to retain those values.
Otherwise CMO and service-ca-operator will compete on every sync loop
that CMO runs. While we don't watch those resources (that would lead to
an infinte competition) we do update them on every sync loop, i.e. CMO
will eventually stop competing with service-ca-operator, but until then
this causes unnecessary churn and can cause TLS errors during times when
CMO removes the TLS data that service-ca-operator populates.

Bug 1953264: client: don't update resource fields that are managed externally

---

assets/control-plane/service-monitor-kubelet.yaml
assets/prometheus-k8s/prometheus-rule-thanos-sidecar.yaml
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
jsonnet/main.jsonnet
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml

jsonnet: pin dependencies to their latest release branches

---

pkg/manifests/manifests.go

Bug 2037073: pkg/manifests: account for slow DNS resolutions

---

assets/prometheus-adapter/api-service.yaml
jsonnet/components/prometheus-adapter.libsonnet

Use service ca beta annotation

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Problem: In many cases cluster admins configure
remote_write to target a centralized system that is used by multiple
clusters. When this centralized metric store is queried, cluster
specific queries need to distinguish metrics by a label. Cluster admins
can already add such a label in their remote_write configuration. This
however scales poorly and requires attention for every cluster.
Solution: Each OpenShift cluster has a unique cluster ID. We already use
this in our telemetry service to query for individual cluster metrics.
The same ID should be available for cluster admins to use in their
custom remote_write configurations. This commits adds a label
`__tmp_openshift_cluster_id__` to every user supplied remote_write
configuration as the first relabel_config entry. Cluster admins can …

MON-2245: manifest: Add cluster_id label to remote_write configurations

---

CONTRIBUTING.md

[MON-1773] doc: add Testing section to CONTRIBUTING.md

---

CHANGELOG.md

CHANGELOG: add entry for https://issues.redhat.com/browse/MON-2245

---

assets/alertmanager/service-monitor.yaml
assets/grafana/service-monitor.yaml
assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
assets/prometheus-k8s/service-monitor.yaml
assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
assets/prometheus-user-workload/service-monitor.yaml
assets/telemeter-client/service-monitor.yaml
assets/thanos-querier/service-monitor.yaml
jsonnet/main.jsonnet
jsonnet/utils/add-bearer-token-to-service-monitors.libsonnet

Cherry-pick of #1637. Because of the static assets, it has to be a manual cherry-pick.

Bug 2075757: use bearer token as fall-back authn method

---

OWNERS

OWNERS: move @fpetkovski, @PhilipGough and @bison to emeritus section

---

CHANGELOG.md
assets/prometheus-user-workload/federate-route.yaml
assets/prometheus-user-workload/kube-rbac-proxy-federate-secret.yaml
assets/prometheus-user-workload/kube-rbac-proxy-metrics-secret.yaml
assets/prometheus-user-workload/prometheus.yaml
assets/prometheus-user-workload/service.yaml
jsonnet/components/prometheus-user-workload.libsonnet
pkg/manifests/manifests.go
pkg/tasks/prometheus_user_workload.go
test/e2e/alertmanager_test.go
test/e2e/framework/framework.go
test/e2e/thanos_ruler_test.go
test/e2e/user_workload_monitoring_test.go

Cherry picks the following PRs in the listed order.
https://github.com/openshift/cluster-monitoring-operator/pull/1601
https://github.com/openshift/cluster-monitoring-operator/pull/1633

Bug 2090602: Federation for UWM metrics

---

CHANGELOG.md
assets/admission-webhook/service.yaml
assets/prometheus-operator/prometheus-rule.yaml
jsonnet/components/prometheus-operator.libsonnet
jsonnet/jsonnetfile.json
jsonnet/jsonnetfile.lock.json
jsonnet/main.jsonnet
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
test/e2e/alertmanager_test.go
test/e2e/framework/framework.go
test/e2e/validatingwebhook_test.go

https://issues.redhat.com/browse/MON-2567

MON-2567: enable AlertmanagerConfig v1beta1

---

assets/prometheus-adapter/deployment.yaml
jsonnet/jsonnetfile.lock.json

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2099526

 Bug 2099526: Updates jsonnet dependencies, prom-adapter

---

assets/control-plane/prometheus-rule.yaml
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml

Reverts openshift/cluster-monitoring-operator#1770
Test revert, we think this may have caused regression https://issues.redhat.com/browse/TRT-589.
@simonpasquier apologies here, the PR is great and found a real problem, unfortunately it's long standing and we're scrambling to get the end of sprint payload, this is the last of two known blockers. We need to revert per TRT policy.
Bringing it back in will be delicate, we need to get the problem addressed and it will be challenging, there will be a card filed for that separate issue soon. We will assist however we can.

Revert "[bot] Update jsonnet dependencies"

---

assets/control-plane/prometheus-rule.yaml
jsonnet/jsonnetfile.lock.json

OCPBUGS-450: jsonnet: bump dependencies

---

assets/alertmanager-user-workload/service-monitor.yaml
assets/alertmanager/service-monitor.yaml
assets/cluster-monitoring-operator/service-monitor.yaml
assets/kube-state-metrics/service-monitor.yaml
assets/node-exporter/service-monitor.yaml
assets/prometheus-adapter/service-monitor.yaml
assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
assets/prometheus-k8s/service-monitor.yaml
assets/prometheus-operator-user-workload/service-monitor.yaml
assets/prometheus-operator/service-monitor.yaml
assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
assets/prometheus-user-workload/service-monitor.yaml
assets/telemeter-client/service-monitor.yaml
assets/thanos-querier/service-monitor.yaml
assets/thanos-ruler/service-monitor.yaml
jsonnet/components/alertmanager-user-workload.libsonnet
jsonnet/components/alertmanager.libsonnet
jsonnet/components/cluster-monitoring-operator.libsonnet
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet
jsonnet/utils/configure-authentication-for-monitors.libsonnet
pkg/manifests/manifests.go

Related to https://github.com/openshift/cluster-monitoring-operator/pull/1785#discussion_r1086815909

pkg/manifests/manifests.go: move constants to jsonnet

---

pkg/operator/operator.go

pkg/operator: fix typo in info logs

---

CHANGELOG.md
jsonnet/components/dashboards.libsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

backport https://issues.redhat.com/browse/OCPBUGS-5353 to 4.12

OCPBUGS-12727: backport OCPBUGS-5353 to 4.12

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

Fixes https://issues.redhat.com/browse/OCPBUGS-13007

OCPBUGS-13007: Add build number to rules

---

assets/cluster-monitoring-operator/prometheus-rule.yaml
jsonnet/rules.libsonnet

Fixes https://issues.redhat.com/browse/OCPBUGS-13008

OCPBUGS-13008: Add build number to vcenter version information

---

Documentation/sample-metrics.md

Fix link metrics

---

Documentation/api.md
Documentation/openshiftdocs/index.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorconfig.adoc
Documentation/openshiftdocs/modules/nodeexportercollectorksmdconfig.adoc
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/manifests/types.go
test/e2e/node_exporter_test.go

MON-3127: add nodeExporter.collectors.ksmd settings.

---

pkg/operator/operator.go

cc @marioferh I remember that we discussed this particular point during one of our meetings. It's probably worthwhile linking to the cluster-policy-controller code for the future.

pkg/operator: reduce duplication in CSR controllers

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Add topologySpreadConstraints to UWM prometheus operator
Add test

OCPBUGS-17682: add topologySpreadConstraints to UWM prometheus operator

---

jsonnet/components/dashboards.libsonnet
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

add to dashboard definition and monitoring console plugin:
```yaml
metadata:
annotations:
capability.openshift.io/name: Console
```

OCPBUGS-18326: add console capability annotation to dashboards and monitoring-plugin.

---

test/e2e/alertmanager_test.go
test/e2e/framework/client.go
test/e2e/thanos_ruler_test.go
test/e2e/user_workload_monitoring_test.go

fix: remove deprecated ioutil.ReadAll()

Remove deprecated ioutil

---

assets/alertmanager-user-workload/alertmanager.yaml
assets/alertmanager-user-workload/kube-rbac-proxy-secret.yaml
assets/cluster-monitoring-operator/user-workload-alertmanager-api-reader.yaml
assets/cluster-monitoring-operator/user-workload-alertmanager-api-writer.yaml
assets/prometheus-user-workload/alertmanager-user-workload-role-binding.yaml
assets/prometheus-user-workload/cluster-role.yaml
assets/thanos-ruler/alertmanager-user-workload-role-binding.yaml
assets/thanos-ruler/cluster-role.yaml
jsonnet/components/alertmanager-user-workload.libsonnet
jsonnet/components/cluster-monitoring-operator.libsonnet
jsonnet/components/prometheus-user-workload.libsonnet
jsonnet/components/thanos-ruler.libsonnet
manifests/0000_50_cluster-monitoring-operator_02-namespaced-cluster-role.yaml
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/alertmanager_user_workload.go
pkg/tasks/clustermonitoringoperator.go
pkg/tasks/prometheus_user_workload.go
pkg/tasks/thanos_ruler_user_workload.go
test/e2e/alertmanager_user_workload_test.go

Don't allow common users access to restricted resources

OCPBUGS-17850: replace nonResourceURLs permissions by subresource

---

assets/node-exporter/daemonset.yaml
jsonnet/components/node-exporter.libsonnet

backport of https://github.com/openshift/cluster-monitoring-operator/pull/2023
JIRA: https://issues.redhat.com/browse/OCPBUGS-15473

OCPBUGS-20073: Limit the value of GOMAXPROCS on node-exporter to 4

---

assets/prometheus-operator/operator-certs-ca-bundle.yaml
jsonnet/components/prometheus-operator.libsonnet
pkg/manifests/manifests.go
pkg/tasks/prometheus.go
pkg/tasks/prometheusoperator.go
pkg/tasks/thanos_querier.go
pkg/tasks/thanos_ruler_user_workload.go

MON-3422: Remove temporary no more needed code 

---

assets/prometheus-user-workload/alertmanager-user-workload-role-binding.yaml
jsonnet/components/prometheus-user-workload.libsonnet
test/e2e/alertmanager_user_workload_test.go

Fix https://github.com/openshift/cluster-monitoring-operator/pull/2099

Fix UWM alert access permissions

---

jsonnet/jsonnetfile.json

OCPBUGS-22917: jsonnet: pin commits

---

jsonnet/jsonnetfile.json

OCPBUGS-22920: jsonnet: pin commits

---

CHANGELOG.md
README.md

MON-3524: Update metrics-server in CHANGELOG and README

---

test/e2e/config_test.go

…rometheus xand add a check for --scrape.timestamp-tolerance on Platform Prometheus

MON-3589: Refactor assertExemplarsEnabled check for UWM Prometheus xand add a check for --scrape.timestamp-tolerance on Platform Prometheus

---

pkg/client/client.go

OCPBUGS-25803: make CMO ConsolePluginComponents task resilient to dependencies

---

pkg/client/client.go
pkg/client/client_test.go
pkg/tasks/helpers.go

Stop checking for the parent context to be done as wait.PollUntilContextTimeout creates a child context with timeout (A child can't and shouldn't cancel the parent context).
Factorize that lastError injection logic in an util.

OCPBUGS-27213: Adjust lastError injection to wait.PollUntilContextTimeout's final error

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/metricsserver.go

This commit ensures that the metrics-server's pods are redeployed when the Kubelet CA cert is rotated.
Similar fix like https://github.com/openshift/cluster-monitoring-operator/pull/2233 but for config map change

OCPBUGS-27289: rollout metrics-server on cert rotations

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/metricsserver.go

This commit ensures that the metrics-server's pods are redeployed when the Kubelet Serving CA/Metrics Client Cert or Serving CA Cert are rotated.

[release-4.15] OCPBUGS-28703: rollout metrics-server on cert rotations

---

assets/control-plane/minimal-service-monitor-kubelet.yaml
assets/control-plane/service-monitor-kubelet.yaml
jsonnet/components/control-plane.libsonnet
jsonnet/utils/configure-authentication-for-monitors.libsonnet

Reverts openshift/cluster-monitoring-operator#2229
It might have cause failures with nightly jobs.

TRT-1489: Revert "jsonnet: update crio port to TLS port 9637"

---

test/e2e/framework/helpers.go
test/e2e/metrics_adapter_test.go

Modify prometheus-adapter e2e tests to compact with metrics server since both are providing resource Metrics API.
When MetricsServer FeatureGate is enabled it will check for metrics-server backend is configured in APIService

MON-3498: Modify prometheus-adapter e2e tests to compact with metrics server

---

Documentation/data-collection.md
jsonnet/components/cluster-monitoring-operator.libsonnet
jsonnet/utils/add-annotations.libsonnet
manifests/0000_50_cluster-monitoring-operator_00_0alertingrules-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0alertrelabelconfigs-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
manifests/0000_50_cluster-monitoring-operator_01-namespace.yaml
manifests/0000_50_cluster-monitoring-operator_02-alert-customization-role.yaml
manifests/0000_50_cluster-monitoring-operator_02-namespaced-cluster-role.yaml
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
manifests/0000_50_cluster-monitoring-operator_03-role-binding.yaml
manifests/0000_50_cluster-monitoring-operator_03-service.yaml
manifests/0000_50_cluster-monitoring-operator_04-config.yaml
manifests/0000_50_cluster-monitoring-operator_06-clusteroperator.yaml
manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

OCPBUGS-29531: Add include.release.openshift.io/hypershift label

---

CHANGELOG.md
CONTRIBUTING.md
Documentation/cluster-monitoring.md
hack/docgen/README.md
hack/docgen/main.go
hack/docgen/model/struct.go
hack/go/generate_versions.go
pkg/alert/rule_controller.go
pkg/client/client.go
pkg/client/client_test.go
pkg/client/condition.go
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/operator/operator.go
pkg/tasks/tasks.go
pkg/tasks/thanos_ruler_user_workload.go
test/e2e/alert_relabel_config_test.go
test/e2e/alertmanager_test.go
test/e2e/alertmanager_user_workload_test.go
test/e2e/framework/client.go
test/e2e/framework/framework.go
test/e2e/main_test.go
test/e2e/prometheus_test.go
test/e2e/security_headers_test.go
test/e2e/thanos_querier_test.go
test/e2e/user_workload_monitoring_test.go

_Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>_

OCPBUGS-18643: address lint warnings

---

assets/alertmanager-user-workload/alertmanager.yaml
assets/openshift-state-metrics/deployment.yaml
assets/prometheus-k8s/prometheus.yaml
hack/local-cmo.sh
hack/ocp-images.sh
jsonnet/components/alertmanager-user-workload.libsonnet
jsonnet/components/prometheus.libsonnet
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml

related: https://github.com/openshift/cluster-monitoring-operator/pull/2077

OCPBUGS-33955: remove deprecated logtostderr argument

---

manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
pkg/manifests/manifests_test.go

MON-3701: clean-up tests

---

assets/prometheus-user-workload/prometheus.yaml
jsonnet/components/prometheus-user-workload.libsonnet
pkg/manifests/manifests.go
pkg/manifests/manifests_test.go
pkg/tasks/prometheus_user_workload.go

MON-3701: clean-up injection of CA bundle for user Prometheus

---

pkg/manifests/manifests.go
pkg/manifests/manifests_test.go

Prometheus v2.53.0 automatically sets GOGC=75 unless the environment variable is set explicitly. The (upstream) rationale is that GOGC=75 reduces memory usage significantly for a slight increase of CPU usage.
OCP components running on Single Node OpenShift (SNO) environments should be savvy on CPU hence the operator sets GOGC to 100 (the Go runtime default value) when the infrastructure topology is SingleReplica.
See https://github.com/openshift/prometheus/pull/206 for more detailed data.

MON-3914: adjust Prometheus GOGC based on infra topology

---

assets/alertmanager-user-workload/alertmanager.yaml
jsonnet/components/alertmanager-user-workload.libsonnet
pkg/manifests/manifests_test.go

[release-4.16] OCPBUGS-34530: inject trusted CA bundle into UWM Alertmanager

---

test/e2e/prometheus_test.go

As proposed here https://github.com/openshift/cluster-monitoring-operator/pull/2390#pullrequestreview-2134965558

MON-3914: add a regression test for gogc based on the go_gc_gogc_percent metric

---

assets/alertmanager-user-workload/secret.yaml
assets/alertmanager/secret.yaml
jsonnet/main.jsonnet

MON-3962: set proxy_from_environment to true

---

test/e2e/config_test.go

… pods can serve /plugin-manifest.json
This is all the more important since the plugin Pods do not have readiness probes.
A more realistic test would ensure the console can reach the plusgins, that can be added in origin/

MON-3990: make TestClusterMonitorConsolePlugin check that one of the pods can serve /plugin-manifest.json

---

pkg/operator/operator.go
pkg/tasks/alertmanager_user_workload.go
pkg/tasks/prometheus_user_workload.go

NO-JIRA: remove 4.17 TODOs

---

assets/control-plane/minimal-service-monitor-kubelet.yaml
assets/control-plane/service-monitor-kubelet.yaml
assets/prometheus-k8s/cluster-role.yaml
assets/prometheus-user-workload/cluster-role.yaml
assets/thanos-querier/prometheus-rule.yaml
jsonnet/components/control-plane.libsonnet
jsonnet/jsonnetfile.lock.json
manifests/0000_50_cluster-monitoring-operator_02-role.yaml
manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml

NO-JIRA: [bot] Update jsonnet dependencies

---

assets/cluster-monitoring-operator/metrics-client-ca.yaml
jsonnet/components/cluster-monitoring-operator.libsonnet

NO-JIRA: metrics-client-ca: set owner annotation

---

pkg/server/server.go

Set ocp intermediate tls settings to cmo server. This avoids throwing
unnecesary warning messages about TLS ciphers.

OCPBUGS-58475: Enforce secure TLS settings in CMO server
